window.TEST_QUESTIONS = {
  mock1: [
    {
      q: "crista, ae f. so‘zining negizini aniqlang.",
      a: ["cris-", "crist-", "crista-", "cristae-", "cri-"],
      correct: 1,
    },
    {
      q: "collum, i n so‘zi uchun turlanish va rodni aniqlang.",
      a: [
        "I turlanish, femininum",
        "II turlanish, masculinum",
        "II turlanish, neutrum",
        "III turlanish, neutrum",
        "IV turlanish, neutrum",
      ],
      correct: 2,
    },
    {
      q: "facies, ei f. so‘zining Genitiv birlik (Gen. Sg.) shaklini tanlang.",
      a: ["facies", "faciei", "facium", "facii", "facie"],
      correct: 1,
    },
    {
      q: "labium, i n. so‘zining Nominativ ko‘plik (Nom. Pl.) shaklini tanlang.",
      a: ["labii", "labia", "labios", "labiae", "labiora"],
      correct: 1,
    },
    {
      q: "Qaysi juftlik Nominativ → Genitiv birlik jihatdan to‘g‘ri mos keladi?",
      a: [
        "foramen → foramina",
        "processus → processi",
        "genu → genui",
        "os (suyak) → ossis",
        "arcus → arcu",
      ],
      correct: 3,
    },
    {
      q: "Qaysi so‘z IV turlanish, neutrum ot hisoblanadi?",
      a: ["meatus", "ductus", "genu", "textus", "sinus"],
      correct: 2,
    },
    {
      q: "Qaysi Genitiv birlik shakli so‘zning III turlanishga mansubligini aniq ko‘rsatadi?",
      a: ["cristae", "colli", "cordis", "arcus", "faciei"],
      correct: 2,
    },
    {
      q: "Qaysi ibora moslashmagan aniqlovchiga mos keladi?",
      a: [
        "arcus aortae",
        "vena magna",
        "linea alba",
        "labium lingua",
        "nervus ligamentum",
      ],
      correct: 4,
    },
    {
      q: "nervus, i m. so‘zining Genitiv birlik shaklini tanlang.",
      a: ["nervi", "nervae", "nervis", "nervorum", "nervuum"],
      correct: 0,
    },
    {
      q: "Qaysi juftlikda II turlanish, neutrum otning Genitiv birlik shakli to‘g‘ri berilgan?",
      a: [
        "sternum → sternia",
        "collum → coll",
        "manubrium → manubriium",
        "labium → labii",
        "septum → septa",
      ],
      correct: 4,
    },
    {
      q: "“articulatio genus” birikmasida “genus” qaysi kelishikda?",
      a: [
        "Nominativus ko‘plik",
        "Genitivus birlik",
        "Genitivus ko‘plik",
        "Nominatus birlik",
        "Ablativ birlik",
      ],
      correct: 1,
    },
    {
      q: "Qaysi Genitiv shakl IV turlanish uchun noto‘g‘ri?",
      a: [
        "meatus → meatus",
        "ductus → ducti",
        "processus → processus",
        "sinus → sinus",
        "genu → genus",
      ],
      correct: 1,
    },
    {
      q: "Qaysi moslik to‘g‘ri?",
      a: [
        "labium, i n → I turlanish femininum",
        "costa, ae f → II turlanish femininum",
        "os, ossis n → III turlanish neutrum",
        "arcus, us m → II turlanish masculinum",
        "facies, ei f → IV turlanish femininum",
      ],
      correct: 2,
    },
    {
      q: "Qaysi o‘zak hosil qilinishi to‘g‘ri?",
      a: [
        "colli → coll-",
        "cristae → cris-",
        "faciei → facie-",
        "foraminis → foramen-",
        "processus → processu-",
      ],
      correct: 0,
    },
    {
      q: "os (suyak) so‘zining Genitiv birlik shaklini tanlang.",
      a: ["osi", "oris", "osse", "ossis", "ossii"],
      correct: 3,
    },
    {
      q: "Qaysi lug‘aviy shakl noto‘g‘ri (rod yoki turlanish xato)?",
      a: [
        "arcus, us m",
        "vena, ae f",
        "corpus, oris m",
        "labium, i n",
        "facies, ei f",
      ],
      correct: 2,
    },
    {
      q: "scapula, vertebra, ala so‘zlari qaysi turlanishga mansub va ularning nominativ ko‘plik shakllari qaysi variantda to‘g‘ri berilgan?",
      a: [
        "I turlanish, scapulae – vertebrae – alae",
        "II turlanish, scapuli – vertebri – alae",
        "I turlanish, scapula – vertebra – ala",
        "III turlanish, scapulas – vertebras – alas",
        "I turlanish, scapulae – vertebra – alae",
      ],
      correct: 0,
    },
    {
      q: "foramen magnum, animal domesticum, rete articulare birikmalarida neutrum otlarning ko‘plik shakli qaysi variantda to‘liq va to‘g‘ri berilgan?",
      a: [
        "foramina magni – animalia domestici – retia articulata",
        "foramenes magni – animales domestici – retia articularia",
        "foramina magnum – animalia domesticum – rete articularia",
        "foramina magna – animalia domestica – retia articularia",
        "foramenia magna – animalia domestica – retia articulata",
      ],
      correct: 0,
    },
    {
      q: "Quyidagi qaysi variantda III turlanish neutrum qoidasiga zid holat mavjud?",
      a: [
        "pulvinar → pulvinaria",
        "animal → animalia",
        "rete → retia",
        "foramen → foramenes",
        "cartilago → cartilagines",
      ],
      correct: 3,
    },
    {
      q: "cartilago, dens, corpus so‘zlari uchun qaysi javobda turlanish + ko‘plik to‘liq to‘g‘ri berilgan?",
      a: [
        "III turlanish: cartilagines – dentes – corpora",
        "I turlanish: cartilagoe – dentae – corpora",
        "III turlanish: cartilagini – denti – corpora",
        "II turlanish: cartilagi – dentes – corpuses",
        "III turlanish: cartilagines – dentia – corpora",
      ],
      correct: 0,
    },
    {
      q: "vena cava inferior birikmasining nominativ ko‘plik shakli qaysi variantda to‘g‘ri?",
      a: [
        "venae cavae inferiores",
        "vena cavae inferiora",
        "venae cavi inferiori",
        "venae cava inferioris",
        "vena cava inferiores",
      ],
      correct: 0,
    },
    {
      q: "Qaysi qatorda sifat ot bilan rod va son jihatdan to‘liq moslashgan?",
      a: [
        "arteriiae elasticae",
        "arteria elastici",
        "arteriae elasticum",
        "arterias elastica",
        "arteria elasticae",
      ],
      correct: 4,
    },
    {
      q: "minor / minus sifatlari ishtirok etgan qaysi variant grammatik jihatdan to‘g‘ri?",
      a: [
        "ducti minor – foramina minor",
        "ductus minora – foramina minores",
        "ductus minores – foramina minora",
        "ductus minores – foramina minores",
        "ductus minoris – foramina minora",
      ],
      correct: 3,
    },
    {
      q: "frontālis, e sifatining ko‘plik shakli qaysi variantda neutrum uchun to‘g‘ri berilgan?",
      a: ["frontalia", "frontales", "frontalis", "frontalium", "frontalis"],
      correct: 0,
    },
    {
      q: "glandula sublingualis minor birikmasining to‘g‘ri ko‘plik shakli qaysi?",
      a: [
        "glandulae sublinguales minores",
        "glandula sublingualia minora",
        "glandulae sublingualis minora",
        "glandulae sublingualis minores",
        "glandulae sublinguales minor",
      ],
      correct: 0,
    },
    {
      q: "Qaysi variantda qisqartma va to‘liq shakl mos keladi?",
      a: [
        "Forr. → foramina",
        "Gll. → glanduli",
        "Aa. → arterii",
        "Nn. → nervae",
        "Vv. → venarum",
      ],
      correct: 1,
    },
    {
      q: "foramen ovale magnum birikmasida:foramen qaysi turlanish, ko‘plik shakli qanday va sifatlar qanday moslashadi?",
      a: [
        "IV turl., foramina ovalia magni",
        "II turl., foramenes ovales magni",
        "III turl., foramina ovales magna",
        "III turl., foramina ovalia magna",
        "III turl., foramenia ovalia magna",
      ],
      correct: 3,
    },
    {
      q: "rete venosum profundum birikmasining nominativ ko‘plik shakli qaysi javobda to‘liq va grammatik jihatdan to‘g‘ri?",
      a: [
        "retia venosa profundes",
        "rete venosa profunda",
        "retia venosum profunda",
        "retia venosa profunda",
        "rete venosum profundum",
      ],
      correct: 0,
    },
    {
      q: "Quyidagi so‘zlardan qaysi biri III turlanish neutrum bo‘lib, ko‘plikda -ia oladi?",
      a: ["dens", "corpus", "animal", "vena", "sutura"],
      correct: 2,
    },
    {
      q: "animal domesticum parvum birikmasining to‘g‘ri ko‘plik shakli qaysi?",
      a: [
        "animales domestici parvi",
        "animals domesticos parvos",
        "animalia domesticum parvum",
        "animalia domestica parva",
        "animalia domestici parva",
      ],
      correct: 3,
    },
    {
      q: "Qaysi qatorda III turlanish masculinum/femininum otlarning ko‘plik shakli to‘g‘ri berilgan?",
      a: [
        "tumor → tumores",
        "virus → vira",
        "corpus → corpora",
        "foramen → foramina",
        "rete → retia",
      ],
      correct: 0,
    },
    {
      q: "ductus sublingualis minor birikmasining ko‘plik shaklini aniqlang.",
      a: [
        "ductus sublinguales minores",
        "ducti sublingualia minora",
        "ductus sublingualis minora",
        "ducti sublinguales minor",
        "ductus sublingualia minores",
      ],
      correct: 0,
    },
    {
      q: "Qaysi variantda ot va sifatlar o’zaro rod va sonda moslashmagan?",
      a: [
        "arteriae elasticae",
        "pulmones resilientes",
        "corpora vulnerabilia",
        "morbi incurabiles",
        "vena cava inferiores",
      ],
      correct: 4,
    },
    {
      q: "frontālis, e va brevis, e sifatlari uchun qaysi javobda neutrum ko‘plik to‘g‘ri berilgan?",
      a: [
        "frontalia – breves",
        "frontales – breves",
        "frontalis – brevis",
        "frontalia – brevia",
        "frontales – brevia",
      ],
      correct: 3,
    },
    {
      q: "for. magnum qisqartmasining to‘liq va ko‘plik shakli qaysi?",
      a: [
        "foramina magna",
        "foramenes magni",
        "foramina magnum",
        "foramenia magna",
        "foramina magni",
      ],
      correct: 0,
    },
    {
      q: "Qaysi javobda birikmadagi barcha so‘zlar grammatik jihatdan to’g’ri moslashgan?",
      a: [
        "vena nasales externa",
        "venae nasales externae",
        "vena nasalia externae",
        "venae nasalis externi",
        "vena nasalium externa",
      ],
      correct: 1,
    },
    {
      q: "cartilago articularis tenuis birikmasining ko‘plik shakli:",
      a: [
        "cartilagines articulares tenues",
        "cartilago articularia tenuia",
        "cartilagini articulares tenues",
        "cartilagines articularis tenuis",
        "cartilagines articulata tenues",
      ],
      correct: 0,
    },
    {
      q: "Qaysi variantda neutrum qoidasi buzilgan?",
      a: [
        "corpora ossea",
        "foramina incisiva",
        "animalia domestica",
        "canales transversi",
        "retia articulata",
      ],
      correct: 3,
    },
    {
      q: "processus mastoideus brevis birikmasining to‘g‘ri ko‘plik shakli:",
      a: [
        "processi mastoidei brevis",
        "processi mastoidei brevia",
        "processus mastoideus brevia",
        "processus mastoidei breves",
        "processus mastoidea brevia",
      ],
      correct: 3,
    },
    {
      q: "vena jugularis interna birikmasida qaysi variant to‘liq to‘g‘ri?",
      a: [
        "venae jugularis interni",
        "vena jugularia interna",
        "venae jugulares internae",
        "vena jugulares internae",
        "venae jugularia internum",
      ],
      correct: 2,
    },
    {
      q: "Qaysi qatorda barcha so‘zlar III turlanishga neutrumga mansub?",
      a: [
        "dens – tumor – cartilago",
        "vena – sutura – glandula",
        "corpus – animal – rete",
        "ductus – sinus – processus",
        "ala – scapula – vertebra",
      ],
      correct: 2,
    },
    {
      q: "cornu posterius longum birikmasida:cornu qaysi turlanish, ko‘plik shakli qanday va sifatlar qanday moslashadi?",
      a: [
        "IV turl., cornua posterioris longa",
        "II turl., cornua posteriora longa",
        "IV turl., cornus posteriores longi",
        "III turl., cornua posteriores longa",
        "IV turl., cornua posteriora longa",
      ],
      correct: 0,
    },
    {
      q: "facies articularis superior birikmasining to‘g‘ri nominativ ko‘plik shakli qaysi?",
      a: [
        "faciei articularia superiora",
        "facies articulares superiores",
        "facies articularis superiores",
        "facies articulatae superiores",
        "facies articularia superior",
      ],
      correct: 1,
    },
    {
      q: "Qaysi variantda V turlanish ot to‘g‘ri ko‘plikka o‘tkazilgan?",
      a: [
        "dies → dio",
        "dies → diae",
        "dies → dies",
        "dies → dia",
        "dies → dii",
      ],
      correct: 2,
    },
    {
      q: "os temporale parvum birikmasining to‘g‘ri ko‘plik shakli:",
      a: [
        "ossa temporalia parva",
        "os temporales parvi",
        "ossa temporales parva",
        "ossa temporalia parvi",
        "os temporalia parva",
      ],
      correct: 0,
    },
    {
      q: "Qaysi variantda IV turlanish neutrum qoidasi to‘liq saqlangan?",
      a: [
        "genu → genia",
        "genu → genui",
        "genu → genera",
        "genu → genua",
        "genu → genues",
      ],
      correct: 3,
    },
    {
      q: "ligamentum transversum longius birikmasining to‘g‘ri ko‘plik shakli:",
      a: [
        "ligamenta transversa longiora",
        "ligamenta transversia longiora",
        "ligamentes transversos longiores",
        "ligamenta transversum longiora",
        "ligamenta transversa longiores",
      ],
      correct: 0,
    },
    {
      q: "crus osseum breve birikmasining ko‘plik shakli:",
      a: [
        "crura ossea brevia",
        "crura ossei breves",
        "crus ossea brevia",
        "crura osseum brevia",
        "crura osseae brevia",
      ],
      correct: 0,
    },
    {
      q: "Qaysi variantda qiyosiy darajadagi sifat neutrumda noto‘g‘ri ishlatilgan?",
      a: [
        "spatia minora",
        "cornua minora",
        "foramina minora",
        "ossa minores",
        "retia minora",
      ],
      correct: 3,
    },
    {
      q: "valvula venosa profunda birikmasining to‘g‘ri ko‘plik shakli:",
      a: [
        "valvulae venosae profundae",
        "valvula venosa profunda",
        "valvulae venosum profunda",
        "valvulae venosa profundes",
        "valvula venosa profundae",
      ],
      correct: 0,
    },
    {
      q: "Qaysi qatorda II turlanish masculinum otlar noto‘g‘ri ko‘plikka o‘tkazilgan?",
      a: [
        "nervus → nervi",
        "bronchus → bronchi",
        "virus → viri",
        "musculus → musculi",
        "sulcus → sulci",
      ],
      correct: 2,
    },
    {
      q: "tuberculum articulare anterius birikmasining ko‘plik shakli:",
      a: [
        "tubercula articulata anteriora",
        "tuberculi articulares anteriores",
        "tubercula articularis anteriora",
        "tubercula articularia anteriora",
        "tubercula articularia anteriorem",
      ],
      correct: 3,
    },
    {
      q: "Qaysi variantda ot va sifat turli turlanishga mansub bo‘lsa-da to‘g‘ri moslashgan?",
      a: [
        "processus transversi",
        "processus transversa",
        "processi transversus",
        "processus transversum",
        "processi transversa",
      ],
      correct: 0,
    },
    {
      q: "sinus venosus profundus birikmasining to‘g‘ri ko‘plik shakli:",
      a: [
        "sinūs venosi profundes",
        "sinūs venosa profunda",
        "sinus venosum profundum",
        "sinus venosi profundi",
        "sinus venosa profundes",
      ],
      correct: 0,
    },
    {
      q: "Qaysi qatorda III turlanish femininum to‘g‘ri ko‘plikka o‘tkazilgan?",
      a: [
        "cavitas → cavitates",
        "sutura → suturae",
        "ala → alae",
        "vena → venae",
        "fibula → fibulae",
      ],
      correct: 0,
    },
    {
      q: "labium inferius latum birikmasining ko‘plik shakli:",
      a: [
        "labium inferiora lata",
        "labia inferiores lata",
        "labia inferiora lata",
        "labia inferius latum",
        "labia inferiora latus",
      ],
      correct: 2,
    },
    {
      q: "Qaysi variantda neutrum ot + I guruh sifat noto‘g‘ri moslashgan?",
      a: [
        "corpora vulnerabilia",
        "ossa fragilia",
        "foramina larga",
        "retia elasticum",
        "spatia ampla",
      ],
      correct: 3,
    },
    {
      q: "incisura jugularis profunda birikmasining ko‘plik shakli:",
      a: [
        "incisura jugulares profundae",
        "incisura jugularia profunda",
        "incisurae jugularis profundes",
        "incisurae jugularia profundum",
        "incisurae jugulares profundae",
      ],
      correct: 4,
    },
    {
      q: "Qaysi qatorda IV turlanish masculinum to‘g‘ri ishlatilgan?",
      a: [
        "ductus → ductes",
        "ductus → ducti",
        "ductus → ductua",
        "ductus → ductūs",
        "ductus → ductae",
      ],
      correct: 1,
    },
    {
      q: "arcus palmaris profundus birikmasining ko‘plik shakli:",
      a: [
        "arcūs palmaris profundes",
        "arcus palmares profundi",
        "arcus palmaria profunda",
        "arcus palmares profundum",
        "arcūs palmari profundi",
      ],
      correct: 0,
    },
    {
      q: "Qaysi variantda ot ko‘plikda, sifat birlikda bo‘lib grammatik xato bor?",
      a: [
        "arteriae caroticae",
        "venae pulmonales",
        "ossa parvum",
        "nervi spinales",
        "glandulae salivariae",
      ],
      correct: 2,
    },
    {
      q: "fossa cranialis media birikmasining to‘g‘ri ko‘plik shakli:",
      a: [
        "fossa cranialia media",
        "fossae craniales mediae",
        "fossae cranialis media",
        "fossae cranialia medium",
        "fossa craniales mediae",
      ],
      correct: 1,
    },
    {
      q: "Qaysi variantda III turlanish masculinum noto‘g‘ri berilgan?",
      a: [
        "canalis → canales",
        "axis → axes",
        "margo → margines",
        "dens → dentia",
        "pes → pedes",
      ],
      correct: 3,
    },
    {
      q: "cavitas, auris, pars so‘zlari uchun to‘g‘ri tavsifni toping.",
      a: [
        "II turl. femininum",
        "III turl. femininum",
        "III turl. masculinum",
        "I turl. femininum",
        "V turl. femininum",
      ],
      correct: 1,
    },
    {
      q: "Quyidagi qaysi so‘z -is bilan tugab, femininum?",
      a: ["pulvis", "axis", "auris", "canalis", "dens"],
      correct: 2,
    },
    {
      q: "radix dentis birikmasida radix so‘zi qaysi xususiyatga ega?",
      a: [
        "III turl. masculinum",
        "II turl. femininum",
        "III turl. femininum",
        "IV turl. femininum",
        "I turl. femininum",
      ],
      correct: 2,
    },
    {
      q: "Qaysi so‘z -go bilan tugab, III turlanish femininum?",
      a: ["margo", "cartilago", "thorax", "coccyx", "hirudo"],
      correct: 1,
    },
    {
      q: "cartilago thyroidea birikmasining ko‘plik shakli qaysi?",
      a: [
        "cartilago thyroideae",
        "cartilagini thyroidea",
        "cartilagines thyroideae",
        "cartilagines thyroideus",
        "cartilaginum thyroideae",
      ],
      correct: 2,
    },
    {
      q: "Qaysi so‘z femininum ko‘rinishli, lekin masculinum rodiga xos bo’lgan istisno so‘z?",
      a: ["auris", "pelvis", "atlas", "basis", "cavitas"],
      correct: 2,
    },
    {
      q: "meninx, meningis so‘zi uchun to‘g‘ri javobni toping.",
      a: [
        "III turl. neutrum",
        "II turl. femininum",
        "III turl. femininum",
        "I turl. femininum",
        "V turl. femininum",
      ],
      correct: 2,
    },
    {
      q: "Qaysi qatorda faqat III turlanish femininum otlar bor?",
      a: [
        "auris – pelvis – cavitas",
        "pulvis – sanguis – dens",
        "atlas – axis – canalis",
        "pancreas – vas – cornu",
        "margo – tendo – thorax",
      ],
      correct: 0,
    },
    {
      q: "auris externa birikmasida rod moslashuvi qanday?",
      a: [
        "xato",
        "faqat ot to‘g‘ri",
        "faqat sifat to‘g‘ri",
        "to‘liq moslashgan",
        "neytral",
      ],
      correct: 0,
    },
    {
      q: "Qaysi so‘z -x bilan tugab femininum?",
      a: ["thorax", "larynx", "pharynx", "radix", "coccyx"],
      correct: 3,
    },
    {
      q: "pyramis renalis birikmasida pyramis qanday ot?",
      a: [
        "III turl. masculinum",
        "III turl. femininum",
        "II turl. femininum",
        "IV turl. femininum",
        "V turl. femininum",
      ],
      correct: 1,
    },
    {
      q: "Qaysi so‘z III tur femininum qo’shimchaga ega bo’lsa ham neutrum rodiga tegishli istisno so’z hisoblanadi?",
      a: ["auris", "pelvis", "cartilago", "pancreas", "cavitas"],
      correct: 3,
    },
    {
      q: "pars libera gingivae birikmasida pars rod va turlanishga tegishli bo’ladi?",
      a: [
        "II turl. femininum",
        "III turl. masculinum",
        "III turl. femininum",
        "I turl. femininum",
        "IV turl. femininum",
      ],
      correct: 2,
    },
    {
      q: "Qaysi qatorda kasallik nomlari (III turl. f.) berilgan?",
      a: [
        "curatio – incisio – solutio",
        "cirrhosis – mycosis – febris",
        "auris – pelvis – basis",
        "pulvis – vas – pancreas",
        "atlas – dens – axis",
      ],
      correct: 1,
    },
    {
      q: "diagnosis, synthesis, metastasis so‘zlari uchun umumiy belgi:",
      a: [
        "II turlanish",
        "IV turlanish",
        "V turlanish",
        "III turlanish femininum",
        "III turlanish masculinum",
      ],
      correct: 3,
    },
    {
      q: "Qaysi so‘z -s bilan tugab femininum?",
      a: ["dens", "axis", "pars", "unguis", "canalis"],
      correct: 2,
    },
    {
      q: "hypophysis so‘zi qaysi turga kiradi?",
      a: [
        "III turl. masculinum",
        "III turl. femininum",
        "II turl. femininum",
        "IV turl. femininum",
        "V turl. femininum",
      ],
      correct: 1,
    },
    {
      q: "Qaysi qatorda dorivor o‘simliklar (III turl. femininum.) berilgan?",
      a: [
        "digitalis – filix – thermopsis",
        "adonis – pulvis – solutio",
        "borax – pix – vas",
        "apis – mays – ribes",
        "sinapis – pancreas – pelvis",
      ],
      correct: 0,
    },
    {
      q: "pix liquida birikmasida pix qanday?",
      a: ["neutrum", "masculinum", "femininum", "II turl.", "IV turl."],
      correct: 2,
    },
    {
      q: "incisio, perforatio, amputatio qaysi turlanishga kiradi va Nom.sing.Gen.sing qo’shimchalarini ko’rsating.",
      a: [
        "II tur -is / -idis",
        "III tur -as / -atis",
        "III tur -x / -cis",
        "III tur --io / -onis",
        "I tur --go / -ginis",
      ],
      correct: 1,
    },
    {
      q: "vas lymphaticum birikmasida vas qaysi rod?",
      a: ["femininum", "masculinum", "neutrum", "commune", "incertum"],
      correct: 1,
    },
    {
      q: "Qaysi qatorda faqat III turl. femininum rodiga tegishli ot so’z turkumiga oid so’z bor?",
      a: [
        "auris – cavitas – pelvis",
        "dens – pulvis – axis",
        "pancreas – vas – cornu",
        "atlas – canalis – unguis",
        "margo – tendo – thorax",
      ],
      correct: 0,
    },
    {
      q: "basis cranii birikmasida basis qanday ot?",
      a: [
        "III turl. masculinum",
        "II turl. femininum",
        "III turl. femininum",
        "I turl. femininum",
        "V turl. Femininum",
      ],
      correct: 2,
    },
    {
      q: "cavitas thoracis birikmasida cavitas so‘zi Nom.Sing va Gen.Sing .qo’shimchasini ko’rsating.",
      a: [
        "-is / -idis",
        "-io / -onis",
        "-as / -atis",
        "-x / -cis",
        "-go / -ginis",
      ],
      correct: 0,
    },
    {
      q: "meninx cerebri birikmasida meninx so‘zi uchun to‘g‘ri tavsifni toping.",
      a: [
        "III turlanish, masculinum",
        "III turlanish, femininum",
        "III turlanish, neutrum",
        "II turlanish, femininum",
        "V turlanish, femininum",
      ],
      correct: 1,
    },
    {
      q: "Qaysi qatorda dorivor o‘simlik nomi (III turlanish, f.) mavjud?",
      a: ["thermopsis", "adonis", "mays", "ribes", "vas"],
      correct: 0,
    },
    {
      q: "suspensio pharmaceutica birikmasida suspensio qaysi turlanishga mansub?",
      a: [
        "I turlanish",
        "II turlanish",
        "III turlanish",
        "IV turlanish",
        "V turlanish",
      ],
      correct: 2,
    },
    {
      q: "mucilago plantaginis birikmasida mucilago qanday ot?",
      a: [
        "II turlanish, femininum",
        "III turlanish, femininum",
        "III turlanish, masculinum",
        "IV turlanish, femininum",
        "V turlanish, femininum",
      ],
      correct: 1,
    },
    {
      q: "hepar, abdomen, femur so‘zlari uchun qaysi variantda turlanish, rod va nominativ ko‘plik to‘liq va to‘g‘ri berilgan?",
      a: [
        "III turl. n — hepara, abdomena, femura",
        "III turl. n — heparia, abdomina, femora",
        "III turl. n — heparia, abdomines, femures",
        "III turl. m — hepares, abdomines, femores",
        "II turl. n — hepara, abdomina, femora",
      ],
      correct: 1,
    },
    {
      q: "caput, corpus, pectus so‘zlari uchun qaysi javobda ularning genitiv birlik shakllari to‘g‘ri berilgan?",
      a: [
        "capitis – corporum – pectorum",
        "caputis – corpusis – pectusis",
        "capiti – corpori – pectori",
        "capitis – corporis – pectoris",
        "capitum – corporum – pectorum",
      ],
      correct: 3,
    },
    {
      q: "Quyidagi qaysi qatorda III turlanish neutrum -ar / -e / -en bilan tugagan otlar berilgan?",
      a: [
        "lien – ren – thorax",
        "ulcar – corpus – ulcus",
        "hepar – abdomen– carcinoma",
        "hepar-mellis-abdomen",
        "hepar – secale – semen",
      ],
      correct: 0,
    },
    {
      q: "zygoma, systema, carcinoma so‘zlari uchun qaysi tavsif to‘g‘ri?",
      a: [
        "I turlanish femininum",
        "III turlanish neutrum",
        "III turlanish masculinum",
        "II turlanish neutrum",
        "IV turlanish neutrum",
      ],
      correct: 1,
    },
    {
      q: "Qaysi qatorda -ma bilan tugab, lekin I turlanish femininum bo‘lgan otlar berilgan?",
      a: [
        "zygoma – systema – trauma",
        "diaphragma – carcinoma – oedema",
        "squama – struma",
        "stroma – parenchyma – platysma",
        "bregma – chiasma – rhizoma",
      ],
      correct: 2,
    },
    {
      q: "foramen occipitale, foramen incisivum, foramen mentale birikmalarida foramen uchun qaysi xulosa to‘g‘ri?",
      a: [
        "II turlanish neutrum",
        "III turlanish neutrum",
        "III turlanish masculinum",
        "I turlanish femininum",
        "IV turlanish neutrum",
      ],
      correct: 0,
    },
    {
      q: "crus, genu, pectus so‘zlari uchun qaysi variantda ularning nominativ ko‘plik shakli to‘g‘ri berilgan?",
      a: [
        "crura – genera – pectora",
        "cruses – genuses – pectuses",
        "crura – genora – pectura",
        "crures – genua– pectores",
        "crura – genua– pectora",
      ],
      correct: 4,
    },
    {
      q: "Quyidagi qaysi so‘zlar tugashi neutrumga o‘xshasa ham, aslida masculinum rodiga tegishli?",
      a: [
        "corpus, femur",
        "lien, ren",
        "zygoma, systema",
        "caput, crus",
        "ulcus, pectus",
      ],
      correct: 1,
    },
    {
      q: "rete, semen, ulcus so‘zlari uchun qaysi javobda ularning genitiv birlik shakllari to‘g‘ri berilgan?",
      a: [
        "retis – seminis – ulceris",
        "rete – semen – ulcus",
        "retum – seminum – ulcerum",
        "retis – semenis – ulcitis",
        "reti – semini – ulceri",
      ],
      correct: 0,
    },
    {
      q: "abdomen, foramen, semen so‘zlarining umumiy belgisi qaysi?",
      a: [
        "II turlanish",
        "III turlanish neutrum",
        "III turlanish femininum",
        "IV turlanish",
        "V turlanish",
      ],
      correct: 1,
    },
    {
      q: "caput longum, caput breve, caput laterale birikmalarida caput uchun qaysi xulosa to‘g‘ri?",
      a: [
        "II turlanish masculinum",
        "III turlanish neutrum",
        "I turlanish femininum",
        "IV turlanish neutrum",
        "III turlanish masculinum",
      ],
      correct: 1,
    },
    {
      q: "Qaysi qatorda onkologik atamalar (III turlanish neutrum) berilgan?",
      a: [
        "carcinoma – sarcoma – neoplasma",
        "cirrhosis – mycosis – febris",
        "squama – struma",
        "glaucoma – oedema – sarcoma",
        "adenoma – oedema – symptoma",
      ],
      correct: 0,
    },
    {
      q: "ulcus ventriculi, vulnus apertum birikmalarida ulcus va vulnus uchun qaysi tavsif to‘g‘ri?",
      a: [
        "I turlanish femininum",
        "II turlanish neutrum",
        "III turlanish neutrum",
        "III turlanish masculinum",
        "IV turlanish neutrum",
      ],
      correct: 2,
    },
    {
      q: "Qaysi variantda III turlanish neutrum otlarning ko‘plik qoidasiga to‘liq mos keladi?",
      a: [
        "corpores, femures, capites",
        "corpi, femuri, capiti",
        "corporae, femorae, capitae",
        "corpora, femora, capita",
        "corpus, femur, caput",
      ],
      correct: 3,
    },
    {
      q: "pectus, corpus, tempus so‘zlari uchun qaysi xususiyat umumiy?",
      a: [
        "III turlanish masculinum gen. -oris/-oris",
        "III turlanish femininum",
        "III turlanish neutrum, gen. -oris/-oris",
        "III turlanish femininum oris/oris",
        "II turlanish neutrum",
      ],
      correct: 2,
    },
    {
      q: "Qaysi qatorda -us bilan tugab, III turlanish neutrum bo‘lgan otlar berilgan?",
      a: [
        "pectus – ulcus – ductus",
        "sinus – ductus",
        "corpus – tempus – pectus",
        "ulcus – nervus – corpus",
        "nervus, angulus, musculus",
      ],
      correct: 2,
    },
    {
      q: "diaphragma, systema, oedema so‘zlari uchun to‘g‘ri tavsifni toping.",
      a: [
        "I turlanish femininum",
        "III turlanish neutrum",
        "III turlanish masculinum",
        "II turlanish neutrum",
        "IV turlanish neutrum",
      ],
      correct: 1,
    },
    {
      q: "foramen magnum, foramen mastoideum birikmalarining ko‘plik shakli qaysi qatorda to‘g‘ri berilgan?",
      a: [
        "foramina magnus, mastoideus",
        "foramenes magni, mastoidei",
        "foramina magni, mastoidei",
        "foramina magna, mastoidea",
        "foramina magnum, mastoideum",
      ],
      correct: 2,
    },
    {
      q: "mel, lac so‘zlari uchun qaysi javob to‘g‘ri?",
      a: [
        "II turlanish masculinum",
        "III turlanish neutrum",
        "I turlanish femininum",
        "IV turlanish neutrum",
        "V turlanish neutrum",
      ],
      correct: 1,
    },
    {
      q: "Qaysi qatorda ichki a’zolar nomlari (III turlanish neutrum) berilgan?",
      a: [
        "hepar – pectus – corpus",
        "auris – oculus – dens",
        "lien – ren – abdomen",
        "squama – struma",
        "basis – pelvis",
      ],
      correct: 0,
    },
    {
      q: "mel, lac, caput so‘zlari uchun qaysi javobda ularning genitiv birlik shakllari to‘g‘ri berilgan?",
      a: [
        "melis – lacis – capitis",
        "mellis – lactis – capitis",
        "melis – lactis – caputis",
        "mellum – lactum – caputum",
        "mellis – lactis – caputis",
      ],
      correct: 1,
    },
    {
      q: "Quyidagi qaysi qatorda -en bilan tugab, III turlanish neutrum bo‘lgan otlar berilgan?",
      a: [
        "semen – foramen – abdomen",
        "genus – tempus – pectus",
        "foramen – abdomen – lien",
        "zygoma – systema – oedema",
        "lien – ren",
      ],
      correct: 0,
    },
    {
      q: "Quyidagi qaysi qatorda tugashi neutrumga o‘xshab, aslida masculinum bo‘lgan otlar berilgan?",
      a: [
        "lien – ren",
        "corpus – tempus",
        "ulcus – vulnus",
        "zygoma – systema",
        "caput – crus",
      ],
      correct: 0,
    },
    {
      q: "abdomen, semen, foramen so‘zlarining umumiy belgisi qaysi?",
      a: [
        "I turlanish",
        "III turlanish femininum",
        "III turlanish neutrum, gen. -inis",
        "III turlanish neutrum gen. -onis",
        "IV turlanish",
      ],
      correct: 3,
    },
    {
      q: "Qaysi qatorda -us bilan tugab, III turlanish neutrum bo‘lgan otlar berilgan?",
      a: [
        "sinus – ductus",
        "pectus – corpus – tempus",
        "lien – ren – thorax",
        "angulus, musculus",
        "nervus, purus, albus",
      ],
      correct: 1,
    },
    {
      q: "Qaysi qatorda III turlanish neutrum + patologik holat berilgan?",
      a: [
        "oedema – ulcus – vulnus",
        "cirrhosis – mycosis – febris",
        "auris – pelvis – basis",
        "lien – ren – margo",
        "squama – struma",
      ],
      correct: 0,
    },
    {
      q: "Qaysi variantda barcha so‘zlar III turlanish neutrum hisoblanadi?",
      a: [
        "hepar – femur – corpus",
        "lien – ren – thorax",
        "squama – struma",
        "auris – pelvis – basis",
        "atlas – dens – canalis",
      ],
      correct: 0,
    },
    {
      q: "alveolus so‘zi haqida qaysi xulosa to‘g‘ri?",
      a: [
        "I turl., f, -ae",
        "II turl., m, -i",
        "III turl., n, -is",
        "IV turl., m, -us",
        "V turl., f, -ei",
      ],
      correct: 1,
    },
    {
      q: "corpus so‘zi uchun qaysi ko’rinish to‘g‘ri hisoblanadi?",
      a: [
        "II turl., m, corpora",
        "III turl., n, corporis",
        "III turl., m, corpora",
        "IV turl., n, corpus",
        "V turl., n, corporei",
      ],
      correct: 1,
    },
    {
      q: "anguli shakli haqida qaysi tavsif to‘g‘ri?",
      a: [
        "Nom. Sg. – “burchak”",
        "Gen. Sg. – “burchakning”",
        "Nom. Pl. – “burchaklar”",
        "Dat. Pl. – “burchaklarga”",
        "Abl. Pl. – “burchaklardan”",
      ],
      correct: 0,
    },
    {
      q: "processus so‘zi uchun bosh kelishik (Nom. Sg.) oxiri qaysi qo‘shimcha bilan tugaydi va qaysi turlanishga kiradi?",
      a: ["–is / III", "–us / IV", "–um / II", "–a / I", "–ei / V"],
      correct: 1,
    },
    {
      q: "Quyidagi qaysi so‘z neutrum rodiga mansub emas, lekin shaklan chalg‘ituvchi?",
      a: ["corpus", "os (suyak)", "facies", "lien", "foramen"],
      correct: 2,
    },
    {
      q: "os (suyak) va os (og‘iz) so‘zlarini farqlashda qaysi belgi ENG MUHIM?",
      a: [
        "Nominativ shakli",
        "sifat ko’rinishi",
        "Genitiv birlik shakli",
        "Ko‘plik shakli",
        "Turlanish nomi",
      ],
      correct: 2,
    },
    {
      q: "Quyidagi qaysi variantda ikkinchi turlanish, neutrum oti berilgan?",
      a: ["anguli", "skeleton", "apex", "arcus", "corpus"],
      correct: 4,
    },
    {
      q: "species so‘zi uchun qaysi tavsif to‘g‘ri?",
      a: [
        "I turl., f",
        "II turl., f",
        "III turl., f",
        "IV turl., f",
        "V turl., f",
      ],
      correct: 1,
    },
    {
      q: "cornu so‘zi haqida qaysi ma’lumot to‘g‘ri?",
      a: [
        "II turl., m, “cho‘qqi”",
        "III turl., n, “ravoch”",
        "IV turl., n, “shoh,muguz”",
        "V turl., f, “to‘qima”",
        "I turl., n, “teshik”",
      ],
      correct: 2,
    },
    {
      q: "tuberculum so‘zi uchun to‘g‘ri tavsifni toping.",
      a: [
        "I turl., f, nerv",
        "II turl., n, do‘mboqcha",
        "III turl., m, lab",
        "IV turl., n, ravoq",
        "V turl., f, nerv",
      ],
      correct: 1,
    },
    {
      q: "Uchinchi turlanish otlarida qaratqich kelishik (Gen. Sg.) qaysi qo‘shimcha bilan yasaladi?",
      a: ["–ae", "–is", "–us", "–ei", "–i"],
      correct: 1,
    },
    {
      q: "hiatus so‘zi qanday tarjima qilinadi va qaysi turlanishga mansub?",
      a: [
        "yo‘l / II",
        "cho‘ntak / III",
        "tirqish / IV",
        "chigal / I",
        "to‘qima / V",
      ],
      correct: 1,
    },
    {
      q: "arcus so‘zi uchun qaysi grammatik tavsif to‘g‘ri?",
      a: [
        "II turl., m",
        "III turl., n",
        "IV turl., m",
        "V turl., f",
        "I turl., m",
      ],
      correct: 0,
    },
    {
      q: "cortex so‘zi uchun qaysi tavsif to‘g‘ri?",
      a: [
        "I turl., f",
        "II turl., m",
        "III turl., m",
        "IV turl., n",
        "V turl., f",
      ],
      correct: 2,
    },
    {
      q: 'Og‘riq yoki sezgilar haqida so‘z borganda, qaysi atama "o‘tkirroq" degan ma’noni anglatadi?',
      a: ["Acutior", "Melior", "Tardior", "Fortior"],
      correct: 0,
    },
    {
      q: 'Qaysi sifat "kattaroq" qon tomirlariga ishora qiladi?',
      a: ["Major", "Minor", "Gravior", "Longior"],
      correct: 0,
    },
    {
      q: 'Qaysi atama "yaxshiroq" sharoit yoki davolanishni bildiradi?',
      a: ["Deterior", "Melior", "Saturatior", "Efficientior"],
      correct: 1,
    },
    {
      q: 'Agar jarohatlar "kichikroq" bo‘lsa, qaysi sifat ishlatiladi?',
      a: ["Brevisior", "Inferior", "Minor", "Simplicior"],
      correct: 2,
    },
    {
      q: 'Fiziologik jarayonning tezligi haqida so‘z borganda, "sekinroq" nimani anglatadi?',
      a: ["Gravior", "Longior", "Tardior", "Salubrior"],
      correct: 2,
    },
    {
      q: '"Og‘irroq" yoki jiddiyroq kasalliklar uchun qaysi atama ishlatiladi?',
      a: ["Brevisior", "Gravior", "Simplicior", "Acutior"],
      correct: 1,
    },
    {
      q: 'Ayrim tibbiy muolajalarni "qisqaroq" deb ta’riflash uchun qanday sifat ishlatiladi?',
      a: ["Salubrior", "Brevisior", "Major", "Fortior"],
      correct: 1,
    },
    {
      q: 'Agar dori-darmonlar yoki davolash ta’sirlari "kuchliroq" bo‘lsa, qaysi atama ishlatiladi?',
      a: ["Saturatior", "Minor", "Fortior", "Tardior"],
      correct: 2,
    },
    {
      q: 'Sog‘liq yoki holat yomonlashganda qaysi atama "yomonroq" degan ma’noni anglatadi?',
      a: ["Deterior", "Acutior", "Efficientior", "Gravior"],
      correct: 0,
    },
    {
      q: 'Davolash rejalari yoki muolajalari kontekstida qaysi atama "oddiyroq" degan ma’noni anglatadi?',
      a: ["Inferior", "Simplicior", "Major", "Nasalis"],
      correct: 1,
    },
    {
      q: 'Qondagi kislorod darajasi kontekstida "ko‘proq to‘yingan" ma’nosida qanday atama ishlatiladi?',
      a: ["Efficientior", "Saturatior", "Nasalis", "Ethmoidalis"],
      correct: 1,
    },
    {
      q: 'Tibbiy aralashuvlarni ta’riflashda qaysi atama "samaraliroq" degan ma’noni anglatadi?',
      a: ["Efficientior", "Tardior", "Gravior", "Nasalis"],
      correct: 0,
    },
    {
      q: 'Anatomik tuzilmalar yoki xususiyatlarga ishora qilib, qaysi atama "pastki" degan ma’noni anglatadi?',
      a: ["Inferior", "Minor", "Major", "Salubrior"],
      correct: 0,
    },
    {
      q: 'Turmush tarzi yoki odatlar haqidagi munozaralarda qaysi atama "sog‘lomroq" degan ma’noni anglatadi?',
      a: ["Salubrior", "Fortior", "Simplicior", "Acutior"],
      correct: 0,
    },
    {
      q: "vena cava superior birikmasida superior so‘zi uchun qaysi tavsif to‘g‘ri?",
      a: [
        "Oddiy daraja, II turlanish",
        "Qiyosiy daraja, III turlanish",
        "Orttirma daraja, I turlanish",
        "Qiyosiy daraja, II turlanish",
        "Oddiy daraja, III turlanish",
      ],
      correct: 3,
    },
    {
      q: "musculus pectoralis major et minor birikmasida major va minor so‘zlari haqida qaysi xulosa to‘g‘ri?",
      a: [
        "Oddiy daraja sifatlar",
        "Qiyosiy daraja, III turlanish",
        "Orttirma daraja, I turlanish",
        "Oddiy daraja, II turlanish",
        "Son sifatlari",
      ],
      correct: 0,
    },
    {
      q: "major, jus sifatining lug‘aviy shakli nimani bildiradi?",
      a: [
        "qiyosiy daraja faqat masculinum shaklini",
        "qiyosiy daraja faqat femininum shaklini",
        "qiyosiy daraja masculinum/femininum va neutrum shakllarini",
        "qiyosiy daraja faqat neutrum shaklini",
        "orttirma darajani",
      ],
      correct: 2,
    },
    {
      q: "cornu posterius medullae spinalis birikmasida posterius so‘zi qaysi rodga moslashgan?",
      a: ["Masculinum", "Femininum", "Neutrum", "Umumiy rod", "Aniqlanmaydi"],
      correct: 0,
    },
    {
      q: "fossa cranii anterior va fossa cranii posterior birikmalarida sifatlarning joylashuvi nimani ko‘rsatadi?",
      a: [
        "Tasodifiy tartib",
        "Lotin tilida sifat doim otdan oldin keladi",
        "Anatomik terminlarda aniqlovchi oxirida keladi",
        "Qiyosiy daraja ishlatilmagan",
        "Faqat klinik uslub",
      ],
      correct: 2,
    },
    {
      q: "laesio gravior cerebri birikmasida gravior so‘zi nimani bildiradi?",
      a: [
        "Oddiy holat(positivus)",
        "Orttirma daraja",
        "Qiyosiy daraja (og‘irroq)",
        "Son miqdori",
        "O‘lchamni ko’rsatadi",
      ],
      correct: 2,
    },
    {
      q: "foramen superior variantlarida to‘g‘ri shakl qaysi?",
      a: [
        "foramen superior",
        "foramen superius",
        "foramina superior",
        "foramina superiora",
        "foramen superiora",
      ],
      correct: 0,
    },
    {
      q: "major, jus va minor, us sifatlari qaysi umumiy belgiga ega?",
      a: [
        "Oddiy daraja",
        "Qiyosiy daraja",
        "Orttirma daraja",
        "Darak shakl",
        "O‘zgarmas shakl",
      ],
      correct: 1,
    },
    {
      q: "respiratio difficilior birikmasida difficilior qanday ma’noni bildiradi?",
      a: ["qiyin", "eng qiyin", "qiyinroq", "osonroq", "oddiy"],
      correct: 2,
    },
    {
      q: "Qaysi sifat qiyosiy daraja emas?",
      a: ["anterior", "posterior", "major", "maximus", "inferior"],
      correct: 0,
    },
    {
      q: "Qaysi variantda qiyosiy daraja sifati emas?",
      a: ["longior", "brevius", "purior", "facilior", "simplicissimus"],
      correct: 4,
    },
    {
      q: "Qaysi sifat klinik holatni og‘irroq ekanini bildiradi?",
      a: ["gravis", "gravior", "gravissimus", "graviter", "gravitas"],
      correct: 1,
    },
    {
      q: "Qaysi qatorda neutrum shakllar to‘g‘ri berilgan?",
      a: [
        "inferior – superior – anterior",
        "inferius – superius – anterius",
        "inferiores – superiores – anteriores",
        "inferiora – superiora – anteriora",
        "inferioris – superioris – anterioris",
      ],
      correct: 1,
    },
    {
      q: "Qaysi variantda qiyosiy daraja sifati noto‘g‘ri joylashgan?",
      a: [
        "nervus lateralis inferior",
        "vena cava superior",
        "musculus major pectoralis",
        "laesio cerebri gravior",
        "status clinicus gravior",
      ],
      correct: 2,
    },
    {
      q: "longus sifatidan yasalgan orttirma daraja va uning masculinum shakli qaysi variantda to‘g‘ri berilgan?",
      a: [
        "longior",
        "longissimus",
        "longissimum",
        "longissimus, -a, -um",
        "longior, -ius",
      ],
      correct: 3,
    },
    {
      q: "Musculus longissimus birikmasida longissimus so‘zi nimani bildiradi?",
      a: [
        "oddiy uzunlik",
        "nisbatda uzunlik",
        "eng yuqori darajadagi uzunlik",
        "taqqoslanmagan belgi",
        "vaqtinchalik holat",
      ],
      correct: 2,
    },
    {
      q: "Quyidagi qaysi sifat “-issimus, -a, -um” modeli bilan orttirma daraja hosil qiladi?",
      a: ["facilis", "magnus", "acer", "niger", "parvus"],
      correct: 0,
    },
    {
      q: "niger sifatining orttirma darajasi qaysi variantda to‘g‘ri yasalgan?",
      a: ["nigissimus", "nigerrimus", "nigerissimus", "nigrior", "nigerrior"],
      correct: 1,
    },
    {
      q: "Operatio facillima birikmasida qaysi jihatlar to‘g‘ri?",
      a: [
        "qiyosiy daraja + noto‘g‘ri rod",
        "orttirma daraja + femininum moslashuv",
        "oddiy daraja + masculinum",
        "qiyosiy daraja + neutrum",
        "orttirma daraja + noto‘g‘ri son",
      ],
      correct: 1,
    },
    {
      q: "magnus → maximus o‘zgarishi qanday hodisa hisoblanadi?",
      a: [
        "oddiy qo‘shimcha qo‘shish",
        "qiyosiy daraja",
        "istisno orttirma daraja",
        "noto‘g‘ri yasalish",
        "fonetik o‘zgarishsiz holat",
      ],
      correct: 2,
    },
    {
      q: "nigerrimus prognosis birikmasida nigerrimus qanday ma’noni anglatadi?",
      a: [
        "yaxshi prognoz",
        "o‘rtacha prognoz",
        "eng yomon prognoz",
        "yaxshiroq prognoz",
        "qisqa muddat",
      ],
      correct: 2,
    },
    {
      q: "optimus medicus birikmasida optimus nimani bildiradi?",
      a: [
        "yaxshi shifokor",
        "eng yaxshi shifokor",
        "yomon shifokor",
        "kuchli shifokor",
        "tajribasiz shifokor",
      ],
      correct: 1,
    },
    {
      q: "ovum fertilissimum birikmasida fertilissimum nimani bildiradi?",
      a: [
        "unumdor",
        "unumdorroq",
        "eng unumdor",
        "kam unumdor",
        "vaqtinchalik",
      ],
      correct: 2,
    },
    {
      q: "Qaysi sifat oddiy–qiyosiy–orttirma darajalar zanjirida to‘g‘ri berilgan?",
      a: [
        "fortis – fortior – fortissimus",
        "magnus – magnior – magnissimus",
        "longus – longior – longimus",
        "parvus – parvior – parvimus",
        "dignus – dignior – dignimus",
      ],
      correct: 0,
    },
    {
      q: "tardissimus pulsus birikmasida tardissimus qaysi holatni bildiradi?",
      a: [
        "tez urish",
        "eng sekin urish",
        "o‘rtacha urish",
        "tezroq urish",
        "notekis urish",
      ],
      correct: 1,
    },
    {
      q: "respiratio velocissimus birikmasida xatolik nimada?",
      a: [
        "sifat noto‘g‘ri darajada",
        "ot va sifat rodi mos emas",
        "qiyosiy daraja ishlatilgan",
        "so‘z tartibi to‘g‘ri",
        "xatolik yo‘q",
      ],
      correct: 1,
    },
    {
      q: "Purus sifatining ma’nosini aniqlang va neutrum Nom. Pl. shaklini toping.",
      a: [
        "toza – purium",
        "toza – purorum",
        "toza – purae",
        "toza – purius",
        "toza – pura",
      ],
      correct: 4,
    },
    {
      q: "Ruber, bra, brum sifatining o‘zbekcha tarjimasi va femininum Nom. Pl. shakli:",
      a: [
        "qora – nigrae",
        "qizil – rubrae",
        "oq – albae",
        "achchiq – amarae",
        "iliq – calidae",
      ],
      correct: 1,
    },
    {
      q: "Qaysi variantda sifat va ot rod va sonda to‘g‘ri moslashgan?",
      a: [
        "musculi alba",
        "vena rubrum",
        "ossa pura",
        "arteriae purum",
        "nervus rubrae",
      ],
      correct: 2,
    },
    {
      q: "Purus sifati bilan vena (f.) so‘zini ko‘plikda to‘g‘ri biriktiring.",
      a: [
        "venae puri",
        "venae pura",
        "venae purum",
        "venae purae",
        "venae purorum",
      ],
      correct: 3,
    },
    {
      q: "Qaysi qatorda berilgan birikmalar neutrum plural emas?",
      a: [
        "ossa alba",
        "ligamenta pura",
        "viscera rubra",
        "nerva alba",
        "foramina pura",
      ],
      correct: 3,
    },
    {
      q: "Purus sifati bilan ligamentum (n.) so‘zini ko‘plikda to‘g‘ri yozing.",
      a: [
        "ligamenta puri",
        "ligamenta purum",
        "ligamenta pura",
        "ligamenta purae",
        "ligamenta purorum",
      ],
      correct: 2,
    },
    {
      q: "Osteum fragile birikmasida sifat qaysi xususiyatga moslashgan?",
      a: [
        "Faqat rodga",
        "Faqat songa",
        "Rod va songa",
        "Rod, son va kelishikka",
        "Faqat kelishikka",
      ],
      correct: 2,
    },
    {
      q: "Tumor benignus → ko‘plik (Nom. Pl.) ga to‘g‘ri o‘tkazing.",
      a: [
        "tumores benigna",
        "tumores benigni",
        "tumoribus benignis",
        "tumor benignorum",
        "tumorum benignorum",
      ],
      correct: 1,
    },
    {
      q: "Cancer malignus birikmasidagi malignus nima sababli -us bilan tugaydi?",
      a: [
        "Ko‘plik bo‘lgani uchun",
        "Femininum rod sababli",
        "Masculinum rod sababli",
        "Neutrum rod sababli",
        "Kelishik sababli",
      ],
      correct: 2,
    },
    {
      q: "Qaysi variantda rod moslashuvi buzilgan?",
      a: [
        "corpus callosum",
        "ulcus pepticum",
        "pneumonia acutus",
        "synovitis acuta",
        "cardiopathia chronica",
      ],
      correct: 4,
    },
    {
      q: "Pneumonia acuta so’zida acuta qaysi grammatik shaklda?",
      a: [
        "Masc. Nom. Sing.",
        "Fem. Nom. Sing.",
        "Neut. Nom. Sing.",
        "Fem. Acc. Pl.",
        "Masc. Gen. Sing.",
      ],
      correct: 1,
    },
    {
      q: "Pneumoniae acutae nimani anglatadi?",
      a: [
        "O‘tkir pnevmoniya",
        "O‘tkir pnevmoniyalar",
        "Surunkali pnevmoniya",
        "Virusli pnevmoniya",
        "O‘tkir bronxit",
      ],
      correct: 1,
    },
    {
      q: "Diabetes mellitus birikmasida qaysi qoida ishlatilgan?",
      a: [
        "III turlanish",
        "Ot–sifat moslashuvi",
        "Egalik kelishigi",
        "Fe’l birikmasi",
        "Ravishli aniqlovchi",
      ],
      correct: 2,
    },
    {
      q: "Osteoporosis senilis da senilis qanday sifat?",
      a: [
        "I– guruh sifat",
        "II guruh sifat",
        "O‘zgarmas sifat",
        "Son sifat",
        "III tur ot",
      ],
      correct: 1,
    },
    {
      q: "Osteoporoses seniles da sifat nima sababli -es bilan tugaydi?",
      a: [
        "Masculinum",
        "Femininum plural",
        "Neutrum plural",
        "Genitiv plural",
        "Akkuzativ",
      ],
      correct: 1,
    },
    {
      q: "Asthma bronchiale da bronchiale qaysi sabab bilan -e bilan tugaydi?",
      a: [
        "asthma so’zi femininum bo’lgani uchun",
        "asthma so’zi neutrum bo’lgani uchun",
        "asthma so’zi masculinum bo’lgani uchun",
        "Ko‘plik bo‘lgani sabab",
        "Genitiv bo’lgani sabab",
      ],
      correct: 0,
    },
    {
      q: '"Corpus callosum" so\'zi qanday tarjima qilinadi?',
      a: [
        "Miya chandiqli tanasi",
        "O'tkir sinovit",
        "Bo'yin venasi",
        "Surunkali yurak kasalligi",
        "O'smalar",
      ],
      correct: 0,
    },
    {
      q: '"Corpora callosa" so\'zining tarjimasi nima?',
      a: [
        "Miya chandiqli tanalari",
        "Yaxshi sifatli o'smalar",
        "Qarilik osteoporozlari",
        "O'smalar",
        "Surunkali yurak kasalliklari",
      ],
      correct: 0,
    },
    {
      q: '"Tumor benignus" so\'zining tarjimasi nima?',
      a: [
        "O'smalar",
        "O'tkir pnevmoniya",
        "Yaxshi sifatli o'sma",
        "Yomon sifatli saraton",
        "O'tkir sinovit",
      ],
      correct: 2,
    },
    {
      q: '"Tumores benigni" tarjimasi nima?',
      a: [
        "O'smalar",
        "Yaxshi sifatli o'smalar",
        "Yomon sifatli saratonlar",
        "Qarilik osteoporozlari",
        "Miya chandiqli tanalari",
      ],
      correct: 1,
    },
    {
      q: '"Cancer malignus" so\'zi qanday tarjima qilinadi?',
      a: [
        "Mo'rt suyak",
        "O'smalar",
        "Yomon sifatli saraton",
        "Surunkali yurak kasalligi",
        "Oshqozon yara",
      ],
      correct: 2,
    },
    {
      q: '"Cancres maligni" tarjimasi nima?',
      a: [
        "O'smalar",
        "Yomon sifatli saratonlar",
        "Uzun mushaklar",
        "O'tkir pnevmoniya",
        "Yaxshi sifatli o'smalar",
      ],
      correct: 1,
    },
    {
      q: '"Fractura femoris" tarjimasi nima?',
      a: [
        "Son suyak uzilishi",
        "Yaxshi sifatli o'sma",
        "Bo'g'im yallig'lanishi",
        "Tish chirishi",
        "Mo'rt suyak",
      ],
      correct: 0,
    },
    {
      q: '"Fracturae femorum" so\'zining tarjimasi nima?',
      a: [
        "Son suyak uzilishi",
        "Son suyaklari uzilishi",
        "Qarilik osteoporozu",
        "O'tkir pnevmoniya",
        "Yaxshi sifatli o'smalar",
      ],
      correct: 1,
    },
    {
      q: '"Pneumonia acuta" tarjimasi nima?',
      a: [
        "O'tkir sinovit",
        "Surunkali yurak kasalligi",
        "O'tkir pnevmoniya",
        "O'smalar",
        "Yaxshi sifatli o'sma",
      ],
      correct: 2,
    },
    {
      q: '"Pneumoniae acutae" so\'zi qanday tarjima qilinadi?',
      a: [
        "O'tkir pnevmoniyalar",
        "Qarilik osteoporozlari",
        "O'smalar",
        "Yomon sifatli saratonlar",
        "Miya chandiqli tanalari",
      ],
      correct: 0,
    },
    {
      q: '"Diabetes mellitus" tarjimasi nima?',
      a: [
        "Oshqozon yara",
        "Qandli diabet",
        "O'smalar",
        "O'tkir pnevmoniya",
        "Yaxshi sifatli o'smalar",
      ],
      correct: 1,
    },
    {
      q: '"Osteoporosis senilis" so\'zi qanday tarjima qilinadi?',
      a: [
        "Qandli diabet",
        "Surunkali yurak kasalligi",
        "Qarilik osteoporozu",
        "O'smalar",
        "Yomon sifatli saraton",
      ],
      correct: 2,
    },
    {
      q: '"Osteoporoses seniles" tarjimasi nima?',
      a: [
        "Qarilik osteoporozlari",
        "Yaxshi sifatli o'smalar",
        "Bo'g'im yallig'lanishlari",
        "Yomon sifatli saratonlar",
        "O'tkir pnevmoniyalar",
      ],
      correct: 0,
    },
    {
      q: '"Ulcus pepticum" tarjimasi nima?',
      a: [
        "Oshqozon yara",
        "O'tkir pnevmoniya",
        "Yomon sifatli saraton",
        "O'smalar",
        "Yaxshi sifatli o'sma",
      ],
      correct: 0,
    },
    {
      q: '"Ulcera peptica" so\'zi qanday tarjima qilinadi?',
      a: [
        "Oshqozon yara",
        "Oshqozon yaralari",
        "Surunkali yurak kasalligi",
        "Tish chirishi",
        "Yaxshi sifatli o'smalar",
      ],
      correct: 1,
    },
    {
      q: '"Hepatitis viralis" so\'zi qanday tarjima qilinadi?',
      a: [
        "Virusli gepatit",
        "O'smalar",
        "O'tkir pnevmoniya",
        "Mo'rt suyak",
        "Bo'g'im yallig'lanishi",
      ],
      correct: 0,
    },
    {
      q: '"Hepatitides virales" tarjimasi nima?',
      a: [
        "Virusli gepatitlar",
        "O'tkir pnevmoniyalar",
        "Yomon sifatli saratonlar",
        "O'smalar",
        "Yaxshi sifatli o'smalar",
      ],
      correct: 0,
    },
    {
      q: '"Lumen intestini" tarjimasi nima?',
      a: [
        "Tish chirishi",
        "Ichak bo'shligi",
        "Yomon sifatli saraton",
        "Bo'g'im yallig'lanishi",
        "O'smalar",
      ],
      correct: 1,
    },
    {
      q: '"Lumina intestinorum" so\'zi qanday tarjima qilinadi?',
      a: [
        "Ichak bo'shligi",
        "Bo'g'im yallig'lanishlari",
        "Ichak bo'shliqlari",
        "O'tkir pnevmoniya",
        "Mo'rt suyaklar",
      ],
      correct: 2,
    },
    {
      q: '"Synovitis acuta" so\'zi qanday tarjima qilinadi?',
      a: [
        "O'tkir sinovit",
        "Yaxshi sifatli o'sma",
        "Mo'rt suyak",
        "Oshqozon yara",
        "Tish chirishi",
      ],
      correct: 0,
    },
    {
      q: '"Synovites acutae" so\'zi qanday tarjima qilinadi?',
      a: [
        "O'tkir sinovitlar",
        "Yaxshi sifatli o'smalar",
        "O'smalar",
        "O'tkir pnevmoniyalar",
        "Miya chandiqli tanalari",
      ],
      correct: 0,
    },
    {
      q: '"Morbilli virus" so\'zi qanday tarjima qilinadi?',
      a: [
        "O'smalar",
        "Qizamiq virusi",
        "Yomon sifatli saraton",
        "Mo'rt suyak",
        "O'tkir pnevmoniya",
      ],
      correct: 1,
    },
    {
      q: '"Cranium fragilis" qaysi ma’noni anglatadi?',
      a: [
        "Mo‘rt bosh suyagi",
        "Chuqur joylashgan bosh suyagi",
        "Asosiy bosh suyagi",
        "Uzun bosh suyagi",
        "O‘tkir bosh suyagi",
      ],
      correct: 0,
    },
    {
      q: '"Fibra elastica" qaysi to‘laga tegishli?',
      a: [
        "Baquvvat tola",
        "Elastik tola",
        "Eng serpusht tola",
        "Asosiy tola",
        "Katta tola",
      ],
      correct: 1,
    },
    {
      q: '"Musculus fortissimus" qaysi mushak haqida?',
      a: [
        "Katta mushak",
        "Eng kuchli mushak",
        "Eng uzun mushak",
        "Elastik mushak",
        "Mo‘rt mushak",
      ],
      correct: 1,
    },
    {
      q: '"Arteria major" nimani bildiradi?',
      a: [
        "Asosiy arteriya",
        "Katta arteriya",
        "Chuqur joylashgan arteriya",
        "Uzun arteriya",
        "Elastik arteriya",
      ],
      correct: 1,
    },
    {
      q: '"Summus febris" qaysi xususiyatni bildiradi?',
      a: [
        "Eng baland harorat",
        "Asosiy harorat",
        "Kichik harorat",
        "Uzun davomli harorat",
        "O‘tkir harorat",
      ],
      correct: 0,
    },
    {
      q: '"Brevisimus intervallum" qaysi vaziyatga tegishli?',
      a: [
        "Eng qisqa oraliq",
        "Katta oraliq",
        "Sekin oraliq",
        "Asosiy oraliq",
        "Uzun oraliq",
      ],
      correct: 0,
    },
    {
      q: '"Fortior" sifatining oddiy darajasi qaysi?',
      a: ["Fortissimus", "Fortis", "Longior", "Dignior", "Acutior"],
      correct: 1,
    },
    {
      q: '"Longior" sifatining orttirma darajasi qaysi?',
      a: ["Longissimus", "Longus", "Fortior", "Parvissimus", "Dignior"],
      correct: 0,
    },
    {
      q: '"Acutissimus" sifatining oddiy darajasi qaysi?',
      a: ["Acutior", "Acutus", "Acutissimus", "Fortior", "Amarissimus"],
      correct: 1,
    },
    {
      q: "Pulmo, pulmonis otining asosi (negizi) qaysi qatorda to‘g‘ri ko‘rsatilgan?",
      a: ["pulmo-", "pulmon-", "pulm-", "pulmoni-", "pulmonis-"],
      correct: 1,
    },
    {
      q: "Pulmo dexter birikmasida dexter qanday vazifani bajaradi?",
      a: ["Ot", "Fe’l", "Sifat", "Ravish", "Genitiv aniqlovchi"],
      correct: 2,
    },
    {
      q: "Ren, renis otining ko‘plik Nominativus shaklini toping.",
      a: ["renes", "reni", "renum", "renibus", "renis"],
      correct: 0,
    },
    {
      q: "Larynx, laryngis otining negizi qaysi?",
      a: ["larynx-", "laryng-", "laryn-", "laryngi-", "laryngis-"],
      correct: 1,
    },
    {
      q: "Larynx acutus birikmasida acutus nima sababli -us bilan tugaydi?",
      a: [
        "Larynx so’zi Neutrum bo’lgani uchun",
        "Larynx Femininum rodiga tegishli",
        "Larynx Masculinum rodiga tegishli",
        "Larynx Ko‘plik",
        "Larynx Genitiv",
      ],
      correct: 2,
    },
    {
      q: "Flos, floris otining ko‘plik Nominativus shakli:",
      a: ["flori", "flores", "floras", "floris", "florum"],
      correct: 1,
    },
    {
      q: "Qaysi variant III-turlanish masculinum otining belgisidir?",
      a: ["Genitiv -ae", "Genitiv -i", "Genitiv -is", "Nom. -a", "Nom. -um"],
      correct: 2,
    },
    {
      q: "Mater so‘zi qaysi rodga mansub?",
      a: ["Masculinum", "Neutrum", "Femininum", "O‘zgarmas", "Ko‘plik"],
      correct: 2,
    },
    {
      q: "Pia mater birikmasida grammatik jihatdan to‘g‘ri izoh qaysi?",
      a: [
        "mater – masculinum",
        "mater – femininum",
        "pia – sifat",
        "pia – fe’l",
        "moslashuv yo‘q",
      ],
      correct: 1,
    },
    {
      q: "Os, ossis qaysi rodga mansub?",
      a: ["Masculinum", "Femininum", "Neutrum", "Ikki rodli", "O‘zgarmas"],
      correct: 2,
    },
    {
      q: "Musculus flexor da flexor nima?",
      a: [
        "I-turlanish sifat",
        "III-turlanish ot",
        "Ravish",
        "Fe’l",
        "O‘zgarmas sifat",
      ],
      correct: 1,
    },
    {
      q: "Musculus adductor ning tarjimasi:",
      a: [
        "bukuvchi mushak",
        "yozuvchi mushak",
        "yaqinlashtiruvchi mushak",
        "uzoqlashtiruvchi mushak",
        "aylantiruvchi mushak",
      ],
      correct: 2,
    },
    {
      q: "Calor, caloris otining ma’nosi:",
      a: ["sovuq", "og‘riq", "harorat", "hid", "issiqlik"],
      correct: 2,
    },
    {
      q: "Dolor, doloris ning Genitiv birlik shakli:",
      a: ["dolor", "dolore", "doloris", "dolorem", "doloribus"],
      correct: 2,
    },
    {
      q: "Qaysi variant to‘liq grammatik va terminologik jihatdan to‘g‘ri?",
      a: [
        "musculus flexoris",
        "musculi flexora",
        "musculus flexor",
        "musculus flexorum",
        "musculus flexore",
      ],
      correct: 2,
    },
    {
      q: "Metastasis, contusio, articulatio so‘zlarining ma’nosini belgilang va qaysi turlanishga tegishli ekanini aniqlang.",
      a: [
        "Metastaz, ko‘karish, bo‘g‘im — I turlanish, femininum",
        "Metastaz, lat yeyish, bo‘g‘im — III turlanish, femininum",
        "Metastaz, lat yeyish, bo‘g‘im — III turlanish, masculinum",
        "Metastaz, shish, bo‘g‘im — II turlanish",
        "Metastaz, jarohat, bo‘g‘im — III turlanish, neutrum",
      ],
      correct: 4,
    },
    {
      q: "Cavitas, auris, pars so‘zlarining ma’nosi va grammatik mansubligini aniqlang.",
      a: [
        "Bo‘shliq, quloq, qism — III turlanish, femininum",
        "Bo‘shliq, quloq, qism — II turlanish",
        "Bo‘shliq, quloq, qism — III turlanish, masculinum",
        "Bo‘shliq, eshitish, qism — I turlanish",
        "Bo‘shliq, quloq, bo‘lak — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Cartilago, articulatio, hirudo so‘zlarini tarjima qiling va turlanishini aniqlang.",
      a: [
        "Tog‘ay, bo‘g‘im, zuluk — III turlanish, femininum",
        "Tog‘ay, bog‘lam, zuluk — II turlanish",
        "Tog‘ay, bo‘g‘im, qurt — III turlanish, masculinum",
        "Tog‘ay, bo‘g‘im, zuluk — I turlanish",
        "Tog‘ay, bo‘g‘im, zuluk — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Radix, meninx, pix so‘zlarining ma’nosi va grammatik xususiyatini aniqlang.",
      a: [
        "Ildiz, miya pardasi, smola — III turlanish, femininum",
        "Ildiz, miya, smola — II turlanish",
        "Ildiz, miya pardasi, smola — III turlanish, masculinum",
        "Ildiz, miya pardasi, qatron — I turlanish",
        "Ildiz, miya pardasi, smola — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Crisis, diagnosis, lysis so‘zlarining tarjimasi va turlanishi:",
      a: [
        "Inqiroz, tashxis, parchalanish — III turlanish, femininum",
        "Inqiroz, aniqlash, parchalanish — II turlanish",
        "Inqiroz, tashxis, lizis — III turlanish, masculinum",
        "Inqiroz, tashxis, eritish — I turlanish",
        "Inqiroz, tashxis, parchalanish — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Anamnesis, genesis, synthesis so‘zlarining ma’nosini va turlanishini aniqlang.",
      a: [
        "Anamnez, kelib chiqish, sintez — III turlanish, femininum",
        "Anamnez, paydo bo‘lish, birlashma — II turlanish",
        "Tarix, kelib chiqish, sintez — III turlanish, masculinum",
        "Anamnez, genezis, sintez — I turlanish",
        "Anamnez, kelib chiqish, sintez — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Febris, tussis, paresis so‘zlarining tarjimasi va turlanishi:",
      a: [
        "Isitma, yo‘tal, parez — III turlanish, femininum",
        "Isitma, yo‘tal, falaj — II turlanish",
        "Isitma, yo‘tal, parez — III turlanish, masculinum",
        "Harorat, yo‘tal, parez — I turlanish",
        "Isitma, yo‘tal, parez — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Incisio, perforatio, solutio so‘zlarining ma’nosi va turlanishini aniqlang.",
      a: [
        "Kesik, teshilish, eritma — III turlanish, femininum",
        "Kesish, teshik, eritma — II turlanish",
        "Kesik, teshilish, suyuqlik — III turlanish, masculinum",
        "Kesik, teshilish, eritma — I turlanish",
        "Kesik, teshilish, eritma — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Inflamatio, curatio, auscultatio so‘zlarining tarjimasi va turlanishi:",
      a: [
        "Yallig‘lanish, davolash, eshitish — III turlanish, femininum",
        "Yallig‘lanish, davo, tekshiruv — II turlanish",
        "Yallig‘lanish, davolash, auskultatsiya — III turlanish, masculinum",
        "Yallig‘lanish, davolash, eshitish — I turlanish",
        "Yallig‘lanish, davolash, auskultatsiya — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Amputatio, aspersio, suspensio so‘zlarining ma’nosi va turlanishi:",
      a: [
        "Amputatsiya, sepish, suspenziya — III turlanish, femininum",
        "Kesish, sepish, eritma — II turlanish",
        "Amputatsiya, purkash, suspenziya — III turlanish, masculinum",
        "Amputatsiya, sepish, suspenziya — I turlanish",
        "Amputatsiya, sepish, suspenziya — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Basis, pelvis, nux so‘zlarining tarjimasi va turlanishi:",
      a: [
        "Asos, chanoq, yong‘oq — III turlanish, femininum",
        "Asos, qov, yong‘oq — II turlanish",
        "Asos, chanoq, yong‘oq — III turlanish, masculinum",
        "Asos, chanoq, yong‘oq — I turlanish",
        "Asos, chanoq, yong‘oq — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Digitalis, sinapis, apis so‘zlarining ma’nosi va turlanishi:",
      a: [
        "Barmoqgul, xantal, asalari — III turlanish, femininum",
        "Barmoq, xantal, asal — II turlanish",
        "Barmoqgul, xantal, asalari — III turlanish, masculinum",
        "Barmoqgul, xantal, asalari — I turlanish",
        "Barmoqgul, xantal, asalari — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Borax, filix, radix so‘zlarining tarjimasi va turlanishi:",
      a: [
        "Bura, qirqquloq, ildiz — III turlanish, femininum",
        "Bura, o‘t, ildiz — II turlanish",
        "Bura, qirqquloq, ildiz — III turlanish, masculinum",
        "Bura, qirqquloq, ildiz — I turlanish",
        "Bura, qirqquloq, ildiz — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Hypophysis, pancreas, vas so‘zlarining tarjimasi va grammatik mansubligi:",
      a: [
        "Gipofiz, oshqozon osti bezi, tomir — III turlanish (f, n, n)",
        "Gipofiz, oshqozon, tomir — III turlanish, femininum",
        "Gipofiz, oshqozon osti bezi, tomir — III turlanish, masculinum",
        "Gipofiz, oshqozon, tomir — II turlanish",
        "Gipofiz, oshqozon osti bezi, tomir — I turlanish",
      ],
      correct: 0,
    },
    {
      q: "Diagnosis, prognosis, crisis so‘zlarining ma’nosi va turlanishini aniqlang.",
      a: [
        "Tashxis, bashorat, inqiroz — III turlanish, femininum",
        "Tashxis, prognoz, inqiroz — II turlanish",
        "Tashxis, bashorat, inqiroz — III turlanish, masculinum",
        "Tashxis, bashorat, inqiroz — I turlanish",
        "Tashxis, bashorat, inqiroz — III turlanish, neutrum",
      ],
      correct: 0,
    },
    {
      q: "Dosis, basis, pelvis so‘zlarining ma’nosi va turlanishini aniqlang.",
      a: [
        "Doza, asos, qov sohasi — III turlanish, femininum",
        "Doza, asos, chanoq — II turlanish",
        "Doza, asos, qov sohasi — III turlanish, masculinum",
        "Doza, asos, qov sohasi — I turlanish",
        "Doza, asos, qov sohasi — III turlanish, neutrum",
      ],
      correct: 0,
    },
  ],
};
