// questions.js
window.TEST_QUESTIONS = {
  mock1: [
    {
      q: "Identify the stem of the word crista, ae f.",
      a: ["cris-", "crist-", "crista-", "cristae-", "cri-"],
      correct: 1,
    },
    {
      q: "Determine the declension and gender of the word collum, i n.",
      a: [
        "I declension, feminine",
        "II declension, masculine",
        "II declension, neuter",
        "III declension, neuter",
        "IV declension, neuter",
      ],
      correct: 2,
    },
    {
      q: "Choose the Genitive Singular (Gen. Sg.) form of facies, ei f.",
      a: ["facies", "faciei", "facium", "facii", "facie"],
      correct: 1,
    },
    {
      q: "Choose the Nominative Plural (Nom. Pl.) form of labium, i n.",
      a: ["labii", "labia", "labios", "labiae", "labiora"],
      correct: 1,
    },
    {
      q: "Which pair correctly corresponds in terms of Nominative → Genitive Singular?",
      a: [
        "foramen → foramina",
        "processus → processi",
        "genu → genui",
        "os (bone) → ossis",
        "arcus → arcu",
      ],
      correct: 3,
    },
    {
      q: "Which word is a IV declension neuter noun?",
      a: ["meatus", "ductus", "genu", "textus", "sinus"],
      correct: 2,
    },
    {
      q: "Which Genitive Singular form clearly indicates a III declension noun?",
      a: ["cristae", "colli", "cordis", "arcus", "faciei"],
      correct: 2,
    },
    {
      q: "Which phrase represents an uncoordinated attribute?",
      a: [
        "arcus aortae",
        "vena magna",
        "linea alba",
        "labium lingua",
        "nervus ligamentum",
      ],
      correct: 0,
    },
    {
      q: "Choose the Genitive Singular form of nervus, i m.",
      a: ["nervi", "nervae", "nervis", "nervorum", "nervuum"],
      correct: 0,
    },
    {
      q: "In which pair is the Genitive Singular of a II declension neuter noun correctly given?",
      a: [
        "sternum → sternia",
        "collum → coll",
        "manubrium → manubriium",
        "labium → labii",
        "septum → septa",
      ],
      correct: 3,
    },
    {
      q: "In the phrase articulatio genus, which case is genus in?",
      a: [
        "Nominative plural",
        "Genitive singular",
        "Genitive plural",
        "Nominative singular",
        "Ablative singular",
      ],
      correct: 1,
    },
    {
      q: "Which Genitive form is incorrect for the IV declension?",
      a: [
        "meatus → meatus",
        "ductus → ducti",
        "processus → processus",
        "sinus → sinus",
        "genu → genus",
      ],
      correct: 1,
    },
    {
      q: "Which correspondence is correct?",
      a: [
        "labium, i n → I declension feminine",
        "costa, ae f → II declension feminine",
        "os, ossis n → III declension neuter",
        "arcus, us m → II declension masculine",
        "facies, ei f → IV declension feminine",
      ],
      correct: 2,
    },
    {
      q: "Which stem formation is correct?",
      a: [
        "colli → coll-",
        "cristae → cris-",
        "faciei → facie-",
        "foraminis → foramen-",
        "processus → processu-",
      ],
      correct: 0,
    },
    {
      q: "Choose the Genitive Singular form of os (bone).",
      a: ["osi", "oris", "osse", "ossis", "ossii"],
      correct: 3,
    },
    {
      q: "Which dictionary form is incorrect (gender or declension error)?",
      a: [
        "arcus, us m",
        "vena, ae f",
        "corpus, oris m",
        "labium, i n",
        "facies, ei f",
      ],
      correct: 2,
    },
    {
      q: "To which declension do scapula, vertebra, ala belong, and which option correctly gives their Nominative Plural forms?",
      a: [
        "I declension, scapulae – vertebrae – alae",
        "II declension, scapuli – vertebri – alae",
        "I declension, scapula – vertebra – ala",
        "III declension, scapulas – vertebras – alas",
        "I declension, scapulae – vertebra – alae",
      ],
      correct: 0,
    },
    {
      q: "Which option correctly and fully gives the plural forms of neuter nouns?",
      a: [
        "foramina magni – animalia domestici – retia articulata",
        "foramenes magni – animales domestici – retia articularia",
        "foramina magnum – animalia domesticum – rete articularia",
        "foramina magna – animalia domestica – retia articularia",
        "foramenia magna – animalia domestica – retia articulata",
      ],
      correct: 3,
    },
    {
      q: "Which option violates the rule for III declension neuter nouns?",
      a: [
        "pulvinar → pulvinaria",
        "animal → animalia",
        "rete → retia",
        "foramen → foramenes",
        "cartilago → cartilagines",
      ],
      correct: 3,
    },
    {
      q: "For the words cartilago, dens, corpus, which answer correctly gives the declension and plural forms?",
      a: [
        "III declension: cartilagines – dentes – corpora",
        "I declension: cartilagoe – dentae – corpora",
        "III declension: cartilagini – denti – corpora",
        "II declension: cartilagi – dentes – corpuses",
        "III declension: cartilagines – dentia – corpora",
      ],
      correct: 0,
    },
    {
      q: "What is the correct Nominative Plural form of vena cava inferior?",
      a: [
        "venae cavae inferiores",
        "vena cavae inferiora",
        "venae cavi inferiori",
        "venae cava inferioris",
        "vena cava inferiores",
      ],
      correct: 0,
    },
    {
      q: "In which line does the adjective fully agree with the noun in gender and number?",
      a: [
        "arteriiae elasticae",
        "arteria elastici",
        "arteriae elasticum",
        "arterias elastica",
        "arteria elasticae",
      ],
      correct: 0,
    },
    {
      q: "Which option with the adjectives minor / minus is grammatically correct?",
      a: [
        "ducti minor – foramina minor",
        "ductus minora – foramina minores",
        "ductus minores – foramina minora",
        "ductus minores – foramina minores",
        "ductus minoris – foramina minora",
      ],
      correct: 2,
    },
    {
      q: "Which option correctly gives the neuter plural form of the adjective frontalis, e?",
      a: ["frontalia", "frontales", "frontalis", "frontalium", "frontalis"],
      correct: 0,
    },
    {
      q: "What is the correct plural form of glandula sublingualis minor?",
      a: [
        "glandulae sublinguales minores",
        "glandula sublingualia minora",
        "glandulae sublingualis minora",
        "glandulae sublingualis minores",
        "glandula sublinguales minor",
      ],
      correct: 0,
    },
    {
      q: "Which option correctly matches the abbreviation with its full form?",
      a: [
        "Forr. → foramina",
        "Gll. → glanduli",
        "Aa. → arterii",
        "Nn. → nervae",
        "Vv. → venarum",
      ],
      correct: 0,
    },
    {
      q: "In the phrase foramen ovale magnum: what declension does foramen belong to, what is its plural form, and how do the adjectives agree?",
      a: [
        "IV declension, foramina ovalia magni",
        "II declension, foramenes ovales magni",
        "III declension, foramina ovales magna",
        "III declension, foramina ovalia magna",
        "III declension, foramenia ovalia magna",
      ],
      correct: 3,
    },
    {
      q: "What is the correct Nominative Plural form of rete venosum profundum?",
      a: [
        "retia venosa profundes",
        "rete venosa profunda",
        "retia venosum profunda",
        "retia venosa profunda",
        "rete venosum profundum",
      ],
      correct: 3,
    },
    {
      q: "Which of the following is a III declension neuter noun that takes -ia in the plural?",
      a: ["dens", "corpus", "animal", "vena", "sutura"],
      correct: 2,
    },
    {
      q: "What is the correct plural form of animal domesticum parvum?",
      a: [
        "animales domestici parvi",
        "animals domesticos parvos",
        "animalia domesticum parvum",
        "animalia domestica parva",
        "animalia domestici parva",
      ],
      correct: 3,
    },
    {
      q: "Which line correctly gives the plural form of III declension masculine/feminine nouns?",
      a: [
        "tumor → tumores",
        "virus → vira",
        "corpus → corpora",
        "foramen → foramina",
        "rete → retia",
      ],
      correct: 0,
    },
    {
      q: "Determine the plural form of ductus sublingualis minor.",
      a: [
        "ductus sublinguales minores",
        "ducti sublingualia minora",
        "ductus sublingualis minora",
        "ducti sublinguales minor",
        "ductus sublingualia minores",
      ],
      correct: 0,
    },
    {
      q: "In which option do the noun and adjective NOT agree in gender and number?",
      a: [
        "arteriae elasticae",
        "pulmones resilientes",
        "corpora vulnerabilia",
        "morbi incurabiles",
        "vena cava inferiores",
      ],
      correct: 4,
    },
    {
      q: "For the adjectives frontalis, e and brevis, e, which option correctly gives the neuter plural?",
      a: [
        "frontalia – breves",
        "frontales – breves",
        "frontalis – brevis",
        "frontalia – brevia",
        "frontales – brevia",
      ],
      correct: 3,
    },
    {
      q: "What is the full form and plural of the abbreviation for. magnum?",
      a: [
        "foramina magna",
        "foramenes magni",
        "foramina magnum",
        "foramenia magna",
        "foramina magni",
      ],
      correct: 0,
    },
    {
      q: "In which answer are all words in the phrase grammatically agreed correctly?",
      a: [
        "vena nasales externa",
        "venae nasales externae",
        "vena nasalia externae",
        "venae nasalis externi",
        "vena nasalium externa",
      ],
      correct: 1,
    },
    {
      q: "Determine the plural form of cartilago articularis tenuis.",
      a: [
        "cartilagines articulares tenues",
        "cartilago articularia tenuia",
        "cartilagini articulares tenues",
        "cartilagines articularis tenuis",
        "cartilagines articulata tenues",
      ],
      correct: 0,
    },
    {
      q: "In which option is the neuter rule violated?",
      a: [
        "corpora ossea",
        "foramina incisiva",
        "animalia domestica",
        "canales transversi",
        "retia articulata",
      ],
      correct: 3,
    },
    {
      q: "What is the correct plural form of processus mastoideus brevis?",
      a: [
        "processi mastoidei brevis",
        "processi mastoidei brevia",
        "processus mastoideus brevia",
        "processus mastoidei breves",
        "processus mastoidea brevia",
      ],
      correct: 3,
    },
    {
      q: "In the phrase vena jugularis interna, which option is completely correct?",
      a: [
        "venae jugularis interni",
        "vena jugularia interna",
        "venae jugulares internae",
        "vena jugulares internae",
        "venae jugularia internum",
      ],
      correct: 2,
    },
    {
      q: "Which line contains only III declension neuter nouns?",
      a: [
        "dens – tumor – cartilago",
        "vena – sutura – glandula",
        "corpus – animal – rete",
        "ductus – sinus – processus",
        "ala – scapula – vertebra",
      ],
      correct: 2,
    },
    {
      q: "In the phrase cornu posterius longum: what declension does cornu belong to, what is its plural form, and how do the adjectives agree?",
      a: [
        "IV declension, cornua posterioris longa",
        "II declension, cornua posteriora longa",
        "IV declension, cornus posteriores longi",
        "III declension, cornua posteriores longa",
        "IV declension, cornua posteriora longa",
      ],
      correct: 4,
    },
    {
      q: "What is the correct Nominative Plural form of facies articularis superior?",
      a: [
        "faciei articularia superiora",
        "facies articulares superiores",
        "facies articularis superiores",
        "facies articulatae superiores",
        "facies articularia superior",
      ],
      correct: 1,
    },
    {
      q: "Which option correctly forms the plural of a V declension noun?",
      a: [
        "dies → dio",
        "dies → diae",
        "dies → dies",
        "dies → dia",
        "dies → dii",
      ],
      correct: 2,
    },
    {
      q: "What is the correct plural form of os temporale parvum?",
      a: [
        "ossa temporalia parva",
        "os temporales parvi",
        "ossa temporales parva",
        "ossa temporalia parvi",
        "os temporalia parva",
      ],
      correct: 0,
    },
    {
      q: "In which option is the IV declension neuter rule fully preserved?",
      a: [
        "genu → genia",
        "genu → genui",
        "genu → genera",
        "genu → genua",
        "genu → genues",
      ],
      correct: 3,
    },
    {
      q: "Determine the plural form of ligamentum transversum longius.",
      a: [
        "ligamenta transversa longiora",
        "ligamenta transversia longiora",
        "ligamentes transversos longiores",
        "ligamenta transversum longiora",
        "ligamenta transversa longiores",
      ],
      correct: 0,
    },
    {
      q: "What is the plural form of crus osseum breve?",
      a: [
        "crura ossea brevia",
        "crura ossei breves",
        "crus ossea brevia",
        "crura osseum breve",
        "crura osseae brevia",
      ],
      correct: 0,
    },
    {
      q: "In which option is a comparative adjective incorrectly used in the neuter?",
      a: [
        "spatia minora",
        "cornua minora",
        "foramina minora",
        "ossa minores",
        "retia minora",
      ],
      correct: 3,
    },
    {
      q: "What is the correct plural form of valvula venosa profunda?",
      a: [
        "valvulae venosae profundae",
        "valvula venosa profunda",
        "valvulae venosum profunda",
        "valvulae venosa profundes",
        "valvula venosa profundae",
      ],
      correct: 0,
    },
    {
      q: "Which option shows II declension masculine nouns incorrectly pluralized?",
      a: [
        "nervus → nervi",
        "bronchus → bronchi",
        "virus → viri",
        "musculus → musculi",
        "sulcus → sulci",
      ],
      correct: 2,
    },
    {
      q: "Determine the plural form of tuberculum articulare anterius.",
      a: [
        "tubercula articulata anteriora",
        "tuberculi articulares anteriores",
        "tubercula articularis anteriora",
        "tubercula articularia anteriora",
        "tubercula articularia anteriorem",
      ],
      correct: 3,
    },
    {
      q: "In which option do a noun and adjective belong to different declensions but agree correctly?",
      a: [
        "processus transversi",
        "processus transversa",
        "processi transversus",
        "processus transversum",
        "processi transversa",
      ],
      correct: 0,
    },
    {
      q: "What is the correct plural form of sinus venosus profundus?",
      a: [
        "sinūs venosi profundes",
        "sinūs venosa profunda",
        "sinus venosum profundum",
        "sinus venosi profundi",
        "sinus venosa profundes",
      ],
      correct: 3,
    },
    {
      q: "Which line correctly pluralizes III declension feminine nouns?",
      a: [
        "cavitas → cavitates",
        "sutura → suturae",
        "ala → alae",
        "vena → venae",
        "fibula → fibulae",
      ],
      correct: 0,
    },
    {
      q: "Determine the plural form of labium inferius latum.",
      a: [
        "labium inferiora lata",
        "labia inferiores lata",
        "labia inferiora lata",
        "labia inferius latum",
        "labia inferiora latus",
      ],
      correct: 2,
    },
    {
      q: "In which option is a neuter noun + first group adjective incorrectly matched?",
      a: [
        "corpora vulnerabilia",
        "ossa fragilia",
        "foramina larga",
        "retia elasticum",
        "spatia ampla",
      ],
      correct: 3,
    },
    {
      q: "Determine the plural form of incisura jugularis profunda.",
      a: [
        "incisura jugulares profundae",
        "incisura jugularia profunda",
        "incisurae jugularis profundes",
        "incisurae jugularia profundum",
        "incisurae jugulares profundae",
      ],
      correct: 4,
    },
    {
      q: "Which option correctly uses IV declension masculine nouns?",
      a: [
        "ductus → ductes",
        "ductus → ducti",
        "ductus → ductua",
        "ductus → ductūs",
        "ductus → ductae",
      ],
      correct: 3,
    },
    {
      q: "Determine the plural form of arcus palmaris profundus.",
      a: [
        "arcūs palmaris profundes",
        "arcus palmares profundi",
        "arcus palmaria profunda",
        "arcus palmares profundum",
        "arcūs palmari profundi",
      ],
      correct: 1,
    },
    {
      q: "In which option is there a grammatical error where the noun is plural but the adjective is singular?",
      a: [
        "arteriae caroticae",
        "venae pulmonales",
        "ossa parvum",
        "nervi spinales",
        "glandulae salivariae",
      ],
      correct: 2,
    },
    {
      q: "Determine the correct plural form of fossa cranialis media.",
      a: [
        "fossa cranialia media",
        "fossae craniales mediae",
        "fossae cranialis media",
        "fossae cranialia medium",
        "fossa craniales mediae",
      ],
      correct: 1,
    },
    {
      q: "Which option incorrectly gives a III declension masculine noun?",
      a: [
        "canalis → canales",
        "axis → axes",
        "margo → margines",
        "dens → dentia",
        "pes → pedes",
      ],
      correct: 3,
    },
    {
      q: "Choose the correct grammatical description for cavitas, auris, pars.",
      a: [
        "II declension feminine",
        "III declension feminine",
        "III declension masculine",
        "I declension feminine",
        "V declension feminine",
      ],
      correct: 1,
    },
    {
      q: "Which word ends in -is and is feminine?",
      a: ["pulvis", "axis", "auris", "canalis", "dens"],
      correct: 2,
    },
    {
      q: "In the phrase radix dentis, what is the grammatical property of radix?",
      a: [
        "III declension masculine",
        "II declension feminine",
        "III declension feminine",
        "IV declension feminine",
        "I declension feminine",
      ],
      correct: 2,
    },
    {
      q: "Which word ends in -go and belongs to the III declension feminine?",
      a: ["margo", "cartilago", "thorax", "coccyx", "hirudo"],
      correct: 1,
    },
    {
      q: "What is the plural form of cartilago thyroidea?",
      a: [
        "cartilago thyroideae",
        "cartilagini thyroidea",
        "cartilagines thyroideae",
        "cartilagines thyroideus",
        "cartilaginum thyroideae",
      ],
      correct: 2,
    },
    {
      q: "Which word appears feminine but is an exception and belongs to the masculine gender?",
      a: ["auris", "pelvis", "atlas", "basis", "cavitas"],
      correct: 2,
    },
    {
      q: "Choose the correct description for meninx, meningis.",
      a: [
        "III declension neuter",
        "II declension feminine",
        "III declension feminine",
        "I declension feminine",
        "V declension feminine",
      ],
      correct: 2,
    },
    {
      q: "Which line contains only III declension feminine nouns?",
      a: [
        "auris – pelvis – cavitas",
        "pulvis – sanguis – dens",
        "atlas – axis – canalis",
        "pancreas – vas – cornu",
        "margo – tendo – thorax",
      ],
      correct: 0,
    },
    {
      q: "In the phrase auris externa, how is gender agreement applied?",
      a: [
        "incorrect",
        "only the noun is correct",
        "only the adjective is correct",
        "fully agreed",
        "neutral",
      ],
      correct: 3,
    },
    {
      q: "Which word ends in -x and is feminine?",
      a: ["thorax", "larynx", "pharynx", "radix", "coccyx"],
      correct: 3,
    },
    {
      q: "In the phrase pyramis renalis, what type of noun is pyramis?",
      a: [
        "III declension masculine",
        "III declension feminine",
        "II declension feminine",
        "IV declension feminine",
        "V declension feminine",
      ],
      correct: 1,
    },
    {
      q: "Which word belongs to the neuter gender despite having a feminine-looking ending?",
      a: ["auris", "pelvis", "cartilago", "pancreas", "cavitas"],
      correct: 3,
    },
    {
      q: "In the phrase pars libera gingivae, to which gender and declension does pars belong?",
      a: [
        "II declension feminine",
        "III declension masculine",
        "III declension feminine",
        "I declension feminine",
        "IV declension feminine",
      ],
      correct: 2,
    },
    {
      q: "Which line contains disease names (III declension feminine)?",
      a: [
        "curatio – incisio – solutio",
        "cirrhosis – mycosis – febris",
        "auris – pelvis – basis",
        "pulvis – vas – pancreas",
        "atlas – dens – axis",
      ],
      correct: 1,
    },
    {
      q: "What common feature do the words diagnosis, synthesis, metastasis share?",
      a: [
        "II declension",
        "IV declension",
        "V declension",
        "III declension feminine",
        "III declension masculine",
      ],
      correct: 3,
    },
    {
      q: "Which word ends in -s and is feminine?",
      a: ["dens", "axis", "pars", "unguis", "canalis"],
      correct: 2,
    },
    {
      q: "To which declension does the word hypophysis belong?",
      a: [
        "III declension masculine",
        "III declension feminine",
        "II declension feminine",
        "IV declension feminine",
        "V declension feminine",
      ],
      correct: 1,
    },
    {
      q: "Which line lists medicinal plants (III declension feminine)?",
      a: [
        "digitalis – filix – thermopsis",
        "adonis – pulvis – solutio",
        "borax – pix – vas",
        "apis – mays – ribes",
        "sinapis – pancreas – pelvis",
      ],
      correct: 0,
    },
    {
      q: "In the phrase pix liquida, what is the gender of pix?",
      a: ["neuter", "masculine", "feminine", "II declension", "IV declension"],
      correct: 2,
    },
    {
      q: "To which declension do incisio, perforatio, amputatio belong, and what are their Nom. Sg. / Gen. Sg. endings?",
      a: [
        "II declension -is / -idis",
        "III declension -as / -atis",
        "III declension -x / -cis",
        "III declension -io / -onis",
        "I declension -go / -ginis",
      ],
      correct: 3,
    },
    {
      q: "In the phrase vas lymphaticum, what is the gender of vas?",
      a: ["feminine", "masculine", "neuter", "common", "uncertain"],
      correct: 2,
    },
    {
      q: "Which line contains only III declension feminine nouns?",
      a: [
        "auris – cavitas – pelvis",
        "dens – pulvis – axis",
        "pancreas – vas – cornu",
        "atlas – canalis – unguis",
        "margo – tendo – thorax",
      ],
      correct: 0,
    },
    {
      q: "In the phrase basis cranii, what type of noun is basis?",
      a: [
        "III declension masculine",
        "II declension feminine",
        "III declension feminine",
        "I declension feminine",
        "V declension feminine",
      ],
      correct: 2,
    },
    {
      q: "In the phrase cavitas thoracis, indicate the Nom. Sg. and Gen. Sg. endings of cavitas.",
      a: [
        "-is / -idis",
        "-io / -onis",
        "-as / -atis",
        "-x / -cis",
        "-go / -ginis",
      ],
      correct: 2,
    },
    {
      q: "In the phrase meninx cerebri, choose the correct description of meninx.",
      a: [
        "III declension masculine",
        "III declension feminine",
        "III declension neuter",
        "II declension feminine",
        "V declension feminine",
      ],
      correct: 1,
    },
    {
      q: "Which option contains a medicinal plant name (III declension feminine)?",
      a: ["thermopsis", "adonis", "mays", "ribes", "vas"],
      correct: 0,
    },
    {
      q: "In the phrase suspensio pharmaceutica, to which declension does suspensio belong?",
      a: [
        "I declension",
        "II declension",
        "III declension",
        "IV declension",
        "V declension",
      ],
      correct: 2,
    },
    {
      q: "In the phrase mucilago plantaginis, what type of noun is mucilago?",
      a: [
        "II declension feminine",
        "III declension feminine",
        "III declension masculine",
        "IV declension feminine",
        "V declension feminine",
      ],
      correct: 1,
    },
    {
      q: "For the words hepar, abdomen, femur, which option correctly gives their declension, gender, and Nominative Plural?",
      a: [
        "III declension n — hepara, abdomena, femura",
        "III declension n — heparia, abdomina, femora",
        "III declension n — heparia, abdomines, femures",
        "III declension m — hepares, abdomines, femores",
        "II declension n — hepara, abdomina, femora",
      ],
      correct: 1,
    },
    {
      q: "For the words caput, corpus, pectus, which option correctly gives their Genitive Singular forms?",
      a: [
        "capitis – corporum – pectorum",
        "caputis – corpusis – pectusis",
        "capiti – corpori – pectori",
        "capitis – corporis – pectoris",
        "capitum – corporum – pectorum",
      ],
      correct: 3,
    },
    {
      q: "Which line lists III declension neuter nouns ending in -ar / -e / -en?",
      a: [
        "lien – ren – thorax",
        "ulcar – corpus – ulcus",
        "hepar – abdomen – carcinoma",
        "hepar – mellis – abdomen",
        "hepar – secale – semen",
      ],
      correct: 4,
    },
    {
      q: "For the words zygoma, systema, carcinoma, which description is correct?",
      a: [
        "I declension feminine",
        "III declension neuter",
        "III declension masculine",
        "II declension neuter",
        "IV declension neuter",
      ],
      correct: 1,
    },
    {
      q: "Which line contains nouns ending in -ma that belong to the I declension feminine?",
      a: [
        "zygoma – systema – trauma",
        "diaphragma – carcinoma – oedema",
        "squama – struma",
        "stroma – parenchyma – platysma",
        "bregma – chiasma – rhizoma",
      ],
      correct: 2,
    },
    {
      q: "In the phrases foramen occipitale, foramen incisivum, foramen mentale, which conclusion about foramen is correct?",
      a: [
        "II declension neuter",
        "III declension neuter",
        "III declension masculine",
        "I declension feminine",
        "IV declension neuter",
      ],
      correct: 1,
    },
    {
      q: "For the words crus, genu, pectus, which option correctly gives their Nominative Plural forms?",
      a: [
        "crura – genera – pectora",
        "cruses – genuses – pectuses",
        "crura – genora – pectura",
        "crures – genua – pectores",
        "crura – genua – pectora",
      ],
      correct: 4,
    },
    {
      q: "Which words appear neuter in form but actually belong to the masculine gender?",
      a: [
        "corpus, femur",
        "lien, ren",
        "zygoma, systema",
        "caput, crus",
        "ulcus, pectus",
      ],
      correct: 1,
    },
    {
      q: "For the words rete, semen, ulcus, which option correctly gives their Genitive Singular forms?",
      a: [
        "retis – seminis – ulceris",
        "rete – semen – ulcus",
        "retum – seminum – ulcerum",
        "retis – semenis – ulcitis",
        "reti – semini – ulceri",
      ],
      correct: 0,
    },
    {
      q: "What common feature do the words abdomen, foramen, semen share?",
      a: [
        "II declension",
        "III declension neuter",
        "III declension feminine",
        "IV declension",
        "V declension",
      ],
      correct: 1,
    },
    {
      q: "In the phrases caput longum, caput breve, caput laterale, which conclusion about caput is correct?",
      a: [
        "II declension masculine",
        "III declension neuter",
        "I declension feminine",
        "IV declension neuter",
        "III declension masculine",
      ],
      correct: 1,
    },
    {
      q: "Which line lists oncological terms (III declension neuter)?",
      a: [
        "carcinoma – sarcoma – neoplasma",
        "cirrhosis – mycosis – febris",
        "squama – struma",
        "glaucoma – oedema – sarcoma",
        "adenoma – oedema – symptoma",
      ],
      correct: 0,
    },
    {
      q: "In the phrases ulcus ventriculi, vulnus apertum, which description of ulcus and vulnus is correct?",
      a: [
        "I declension feminine",
        "II declension neuter",
        "III declension neuter",
        "III declension masculine",
        "IV declension neuter",
      ],
      correct: 2,
    },
    {
      q: "Which option fully follows the plural rule for III declension neuter nouns?",
      a: [
        "corpores, femures, capites",
        "corpi, femuri, capiti",
        "corporae, femorae, capitae",
        "corpora, femora, capita",
        "corpus, femur, caput",
      ],
      correct: 3,
    },
    {
      q: "What common feature do pectus, corpus, tempus share?",
      a: [
        "III declension masculine, gen. -oris/-oris",
        "III declension feminine",
        "III declension neuter, gen. -oris/-oris",
        "III declension feminine, gen. -oris/-oris",
        "II declension neuter",
      ],
      correct: 2,
    },
    {
      q: "Which line lists III declension neuter nouns ending in -us?",
      a: [
        "pectus – ulcus – ductus",
        "sinus – ductus",
        "corpus – tempus – pectus",
        "ulcus – nervus – corpus",
        "nervus – angulus – musculus",
      ],
      correct: 2,
    },
    {
      q: "Choose the correct description for diaphragma, systema, oedema.",
      a: [
        "I declension feminine",
        "III declension neuter",
        "III declension masculine",
        "II declension neuter",
        "IV declension neuter",
      ],
      correct: 1,
    },
    {
      q: "Which line correctly gives the plural forms of foramen magnum, foramen mastoideum?",
      a: [
        "foramina magnus, mastoideus",
        "foramenes magni, mastoidei",
        "foramina magni, mastoidei",
        "foramina magna, mastoidea",
        "foramina magnum, mastoideum",
      ],
      correct: 3,
    },
    {
      q: "Which option is correct for the words mel, lac?",
      a: [
        "II declension masculine",
        "III declension neuter",
        "I declension feminine",
        "IV declension neuter",
        "V declension neuter",
      ],
      correct: 1,
    },
    {
      q: "Which line lists internal organs (III declension neuter)?",
      a: [
        "hepar – pectus – corpus",
        "auris – oculus – dens",
        "lien – ren – abdomen",
        "squama – struma",
        "basis – pelvis",
      ],
      correct: 2,
    },
    {
      q: "For the words mel, lac, caput, which option correctly gives their Genitive Singular forms?",
      a: [
        "melis – lacis – capitis",
        "mellis – lactis – capitis",
        "melis – lactis – caputis",
        "mellum – lactum – caputum",
        "mellis – lactis – caputis",
      ],
      correct: 1,
    },
    {
      q: "Which line lists III declension neuter nouns ending in -en?",
      a: [
        "semen – foramen – abdomen",
        "genus – tempus – pectus",
        "foramen – abdomen – lien",
        "zygoma – systema – oedema",
        "lien – ren",
      ],
      correct: 0,
    },
    {
      q: "Which line lists nouns that appear neuter but are actually masculine?",
      a: [
        "lien – ren",
        "corpus – tempus",
        "ulcus – vulnus",
        "zygoma – systema",
        "caput – crus",
      ],
      correct: 0,
    },
    {
      q: "What common feature do abdomen, semen, foramen share?",
      a: [
        "I declension",
        "III declension feminine",
        "III declension neuter, gen. -inis",
        "III declension neuter, gen. -onis",
        "IV declension",
      ],
      correct: 2,
    },
    {
      q: "Which line lists III declension neuter nouns ending in -us?",
      a: [
        "sinus – ductus",
        "pectus – corpus – tempus",
        "lien – ren – thorax",
        "angulus – musculus",
        "nervus – purus – albus",
      ],
      correct: 1,
    },
    {
      q: "Which line gives III declension neuter nouns + pathological conditions?",
      a: [
        "oedema – ulcus – vulnus",
        "cirrhosis – mycosis – febris",
        "auris – pelvis – basis",
        "lien – ren – margo",
        "squama – struma",
      ],
      correct: 0,
    },
    {
      q: "In which option are all words III declension neuter?",
      a: [
        "hepar – femur – corpus",
        "lien – ren – thorax",
        "squama – struma",
        "auris – pelvis – basis",
        "atlas – dens – canalis",
      ],
      correct: 0,
    },
    {
      q: "Which statement about alveolus is correct?",
      a: [
        "I declension f., -ae",
        "II declension m., -i",
        "III declension n., -is",
        "IV declension m., -us",
        "V declension f., -ei",
      ],
      correct: 1,
    },
    {
      q: "Which description of corpus is correct?",
      a: [
        "II declension m., corpora",
        "III declension n., corporis",
        "III declension m., corpora",
        "IV declension n., corpus",
        "V declension n., corporei",
      ],
      correct: 1,
    },
    {
      q: "Which description of the form anguli is correct?",
      a: [
        "Nom. Sg. – “angle”",
        "Gen. Sg. – “of the angle”",
        "Nom. Pl. – “angles”",
        "Dat. Pl. – “to the angles”",
        "Abl. Pl. – “from the angles”",
      ],
      correct: 2,
    },
    {
      q: "For the word processus, which ending marks the Nominative Singular and which declension does it belong to?",
      a: ["–is / III", "–us / IV", "–um / II", "–a / I", "–ei / V"],
      correct: 1,
    },
    {
      q: "Which word does NOT belong to the neuter gender but is misleading in form?",
      a: ["corpus", "os (bone)", "facies", "lien", "foramen"],
      correct: 2,
    },
    {
      q: "When distinguishing os (bone) and os (mouth), which feature is MOST important?",
      a: [
        "Nominative form",
        "Adjective form",
        "Genitive Singular form",
        "Plural form",
        "Declension name",
      ],
      correct: 2,
    },
    {
      q: "Which option contains a II declension neuter noun?",
      a: ["anguli", "skeleton", "apex", "arcus", "corpus"],
      correct: 1,
    },
    {
      q: "Which description of the word species is correct?",
      a: [
        "I declension, feminine",
        "II declension, feminine",
        "III declension, feminine",
        "IV declension, feminine",
        "V declension, feminine",
      ],
      correct: 4,
    },
    {
      q: "Which statement about cornu is correct?",
      a: [
        "II declension, masculine, “peak”",
        "III declension, neuter, “arch”",
        "IV declension, neuter, “horn”",
        "V declension, feminine, “tissue”",
        "I declension, neuter, “opening”",
      ],
      correct: 2,
    },
    {
      q: "Choose the correct description for tuberculum.",
      a: [
        "I declension, feminine, nerve",
        "II declension, neuter, tubercle",
        "III declension, masculine, lip",
        "IV declension, neuter, arch",
        "V declension, feminine, nerve",
      ],
      correct: 1,
    },
    {
      q: "In III declension nouns, which ending forms the Genitive Singular (Gen. Sg.)?",
      a: ["–ae", "–is", "–us", "–ei", "–i"],
      correct: 1,
    },
    {
      q: "How is the word hiatus translated and to which declension does it belong?",
      a: [
        "passage / II",
        "pocket / III",
        "fissure / IV",
        "knot / I",
        "tissue / V",
      ],
      correct: 2,
    },
    {
      q: "Which grammatical description of arcus is correct?",
      a: [
        "II declension, masculine",
        "III declension, neuter",
        "IV declension, masculine",
        "V declension, feminine",
        "I declension, masculine",
      ],
      correct: 2,
    },
    {
      q: "Which description of cortex is correct?",
      a: [
        "I declension, feminine",
        "II declension, masculine",
        "III declension, masculine",
        "IV declension, neuter",
        "V declension, feminine",
      ],
      correct: 2,
    },
    {
      q: "When referring to pain or sensations, which term means “sharper”?",
      a: ["Acutior", "Melior", "Tardior", "Fortior"],
      correct: 0,
    },
    {
      q: "Which adjective refers to “larger” blood vessels?",
      a: ["Major", "Minor", "Gravior", "Longior"],
      correct: 0,
    },
    {
      q: "Which term indicates “better” conditions or treatment?",
      a: ["Deterior", "Melior", "Saturatior", "Efficientior"],
      correct: 1,
    },
    {
      q: "If injuries are “smaller,” which adjective is used?",
      a: ["Brevisior", "Inferior", "Minor", "Simplicior"],
      correct: 2,
    },
    {
      q: "When discussing physiological processes, what does “slower” mean?",
      a: ["Gravior", "Longior", "Tardior", "Salubrior"],
      correct: 2,
    },
    {
      q: "Which term is used for “more severe” diseases?",
      a: ["Brevisior", "Gravior", "Simplicior", "Acutior"],
      correct: 1,
    },
    {
      q: "Which adjective describes medical procedures as “shorter”?",
      a: ["Salubrior", "Brevisior", "Major", "Fortior"],
      correct: 1,
    },
    {
      q: "If medications or treatments are “stronger,” which term is used?",
      a: ["Saturatior", "Minor", "Fortior", "Tardior"],
      correct: 2,
    },
    {
      q: "When health worsens, which term means “worse”?",
      a: ["Deterior", "Acutior", "Efficientior", "Gravior"],
      correct: 0,
    },
    {
      q: "In the context of treatment plans, which term means “simpler”?",
      a: ["Inferior", "Simplicior", "Major", "Nasalis"],
      correct: 1,
    },
    {
      q: "In the context of blood oxygen levels, which term means “more saturated”?",
      a: ["Efficientior", "Saturatior", "Nasalis", "Ethmoidalis"],
      correct: 1,
    },
    {
      q: "Which term means “more effective” in medical interventions?",
      a: ["Efficientior", "Tardior", "Gravior", "Nasalis"],
      correct: 0,
    },
    {
      q: "Which term means “lower” when referring to anatomical structures?",
      a: ["Inferior", "Minor", "Major", "Salubrior"],
      correct: 0,
    },
    {
      q: "In lifestyle or habit discussions, which term means “healthier”?",
      a: ["Salubrior", "Fortior", "Simplicior", "Acutior"],
      correct: 0,
    },
    {
      q: "In the phrase vena cava superior, which description of superior is correct?",
      a: [
        "Positive degree, II declension",
        "Comparative degree, III declension",
        "Superlative degree, I declension",
        "Comparative degree, II declension",
        "Positive degree, III declension",
      ],
      correct: 1,
    },
    {
      q: "In the phrase musculus pectoralis major et minor, what is true about major and minor?",
      a: [
        "Positive degree adjectives",
        "Comparative degree, III declension",
        "Superlative degree, I declension",
        "Positive degree, II declension",
        "Numeral adjectives",
      ],
      correct: 1,
    },
    {
      q: "What does the dictionary form major, jus indicate?",
      a: [
        "Comparative degree, masculine only",
        "Comparative degree, feminine only",
        "Comparative degree, masculine/feminine and neuter forms",
        "Comparative degree, neuter only",
        "Superlative degree",
      ],
      correct: 2,
    },
    {
      q: "In the phrase cornu posterius medullae spinalis, to which gender does posterius agree?",
      a: [
        "Masculine",
        "Feminine",
        "Neuter",
        "Common gender",
        "Cannot be determined",
      ],
      correct: 2,
    },
    {
      q: "In the phrases fossa cranii anterior and fossa cranii posterior, what does the position of adjectives indicate?",
      a: [
        "Random order",
        "In Latin adjectives always precede nouns",
        "In anatomical terminology, modifiers often follow the noun",
        "Comparative degree is not used",
        "Clinical style only",
      ],
      correct: 2,
    },
    {
      q: "In the phrase laesio gravior cerebri, what does gravior indicate?",
      a: [
        "Positive degree (simple quality)",
        "Superlative degree",
        "Comparative degree (“more severe”)",
        "Quantity",
        "Size",
      ],
      correct: 2,
    },
    {
      q: "Which option is grammatically correct?",
      a: [
        "foramen superior",
        "foramen superius",
        "foramina superior",
        "foramina superiora",
        "foramen superiora",
      ],
      correct: 1,
    },
    {
      q: "What common feature do the adjectives major, jus and minor, us share?",
      a: [
        "Positive degree",
        "Comparative degree",
        "Superlative degree",
        "Indicative form",
        "Indeclinable form",
      ],
      correct: 1,
    },
    {
      q: "In the phrase respiratio difficilior, what does difficilior mean?",
      a: ["difficult", "most difficult", "more difficult", "easier", "simple"],
      correct: 2,
    },
    {
      q: "Which adjective is NOT in the comparative degree?",
      a: ["anterior", "posterior", "major", "maximus", "inferior"],
      correct: 3,
    },
    {
      q: "Which option is NOT a comparative adjective?",
      a: ["longior", "brevius", "purior", "facilior", "simplicissimus"],
      correct: 4,
    },
    {
      q: "Which adjective indicates a more severe clinical condition?",
      a: ["gravis", "gravior", "gravissimus", "graviter", "gravitas"],
      correct: 1,
    },
    {
      q: "Which line correctly gives neuter forms?",
      a: [
        "inferior – superior – anterior",
        "inferius – superius – anterius",
        "inferiores – superiores – anteriores",
        "inferiora – superiora – anteriora",
        "inferioris – superioris – anterioris",
      ],
      correct: 1,
    },
    {
      q: "In which option is the comparative adjective placed incorrectly?",
      a: [
        "nervus lateralis inferior",
        "vena cava superior",
        "musculus major pectoralis",
        "laesio cerebri gravior",
        "status clinicus gravior",
      ],
      correct: 2,
    },
    {
      q: "Which option correctly gives the superlative degree of longus and its masculine form?",
      a: [
        "longior",
        "longissimus",
        "longissimum",
        "longissimus, -a, -um",
        "longior, -ius",
      ],
      correct: 1,
    },
    {
      q: "In the phrase musculus longissimus, what does longissimus indicate?",
      a: [
        "simple length",
        "relative length",
        "the greatest degree of length",
        "non-comparative quality",
        "temporary state",
      ],
      correct: 2,
    },
    {
      q: "Which adjective forms the superlative degree using the “-issimus, -a, -um” model?",
      a: ["facilis", "magnus", "acer", "niger", "parvus"],
      correct: 0,
    },
    {
      q: "Which option correctly forms the superlative degree of niger?",
      a: ["nigissimus", "nigerrimus", "nigerissimus", "nigrior", "nigerrior"],
      correct: 1,
    },
    {
      q: "In the phrase operatio facillima, which aspects are correct?",
      a: [
        "comparative degree + incorrect gender",
        "superlative degree + feminine agreement",
        "positive degree + masculine",
        "comparative degree + neuter",
        "superlative degree + incorrect number",
      ],
      correct: 1,
    },
    {
      q: "What type of change is magnus → maximus?",
      a: [
        "simple suffix addition",
        "comparative degree formation",
        "irregular superlative formation",
        "incorrect derivation",
        "no phonetic change",
      ],
      correct: 2,
    },
    {
      q: "In the phrase nigerrimus prognosis, what does nigerrimus mean?",
      a: [
        "good prognosis",
        "average prognosis",
        "the worst prognosis",
        "better prognosis",
        "short-term",
      ],
      correct: 2,
    },
    {
      q: "In the phrase optimus medicus, what does optimus mean?",
      a: [
        "good doctor",
        "the best doctor",
        "bad doctor",
        "strong doctor",
        "inexperienced doctor",
      ],
      correct: 1,
    },
    {
      q: "In the phrase ovum fertilissimum, what does fertilissimum mean?",
      a: [
        "fertile",
        "more fertile",
        "most fertile",
        "poorly fertile",
        "temporary",
      ],
      correct: 2,
    },
    {
      q: "Which line correctly presents the chain positive–comparative–superlative?",
      a: [
        "fortis – fortior – fortissimus",
        "magnus – magnior – magnissimus",
        "longus – longior – longimus",
        "parvus – parvior – parvimus",
        "dignus – dignior – dignimus",
      ],
      correct: 0,
    },
    {
      q: "In the phrase tardissimus pulsus, what does tardissimus indicate?",
      a: [
        "rapid pulse",
        "slowest pulse",
        "average pulse",
        "faster pulse",
        "irregular pulse",
      ],
      correct: 1,
    },
    {
      q: "What is incorrect in the phrase respiratio velocissimus?",
      a: [
        "adjective in the wrong degree",
        "noun–adjective gender mismatch",
        "comparative degree used",
        "correct word order",
        "no error",
      ],
      correct: 1,
    },
    {
      q: "Determine the meaning of purus and find its neuter Nom. Pl. form.",
      a: [
        "pure – purium",
        "pure – purorum",
        "pure – purae",
        "pure – purius",
        "pure – pura",
      ],
      correct: 4,
    },
    {
      q: "Give the Uzbek meaning of ruber, bra, brum and its feminine Nom. Pl. form.",
      a: [
        "black – nigrae",
        "red – rubrae",
        "white – albae",
        "bitter – amarae",
        "warm – calidae",
      ],
      correct: 1,
    },
    {
      q: "In which option do the adjective and noun agree correctly in gender and number?",
      a: [
        "musculi alba",
        "vena rubrum",
        "ossa pura",
        "arteriae purum",
        "nervus rubrae",
      ],
      correct: 2,
    },
    {
      q: "Correctly combine the adjective purus with the noun vena (f.) in the plural.",
      a: [
        "venae puri",
        "venae pura",
        "venae purum",
        "venae purae",
        "venae purorum",
      ],
      correct: 3,
    },
    {
      q: "Which line does NOT contain neuter plural phrases?",
      a: [
        "ossa alba",
        "ligamenta pura",
        "viscera rubra",
        "nerva alba",
        "foramina pura",
      ],
      correct: 3,
    },
    {
      q: "Correctly write the plural of ligamentum (n.) with the adjective purus.",
      a: [
        "ligamenta puri",
        "ligamenta purum",
        "ligamenta pura",
        "ligamenta purae",
        "ligamenta purorum",
      ],
      correct: 2,
    },
    {
      q: "In the phrase osteum fragile, to which grammatical features does the adjective agree?",
      a: [
        "gender only",
        "number only",
        "gender and number",
        "gender, number, and case",
        "case only",
      ],
      correct: 3,
    },
    {
      q: "Convert tumor benignus to the correct Nominative Plural form.",
      a: [
        "tumores benigna",
        "tumores benigni",
        "tumoribus benignis",
        "tumor benignorum",
        "tumorum benignorum",
      ],
      correct: 1,
    },
    {
      q: "In the phrase cancer malignus, why does malignus end in -us?",
      a: [
        "because it is plural",
        "because of feminine gender",
        "because of masculine gender",
        "because of neuter gender",
        "because of case",
      ],
      correct: 2,
    },
    {
      q: "In which option is gender agreement violated?",
      a: [
        "corpus callosum",
        "ulcus pepticum",
        "pneumonia acutus",
        "synovitis acuta",
        "cardiopathia chronica",
      ],
      correct: 2,
    },
    {
      q: "In the phrase pneumonia acuta, what grammatical form is acuta?",
      a: [
        "masculine nominative singular",
        "feminine nominative singular",
        "neuter nominative singular",
        "feminine accusative plural",
        "masculine genitive singular",
      ],
      correct: 1,
    },
    {
      q: "What does pneumoniae acutae mean?",
      a: [
        "acute pneumonia",
        "acute pneumonias",
        "chronic pneumonia",
        "viral pneumonia",
        "acute bronchitis",
      ],
      correct: 1,
    },
    {
      q: "Which rule is applied in the phrase diabetes mellitus?",
      a: [
        "III declension rule",
        "noun–adjective agreement",
        "possessive case",
        "verb phrase",
        "adverbial modifier",
      ],
      correct: 1,
    },
    {
      q: "In osteoporosis senilis, what type of adjective is senilis?",
      a: [
        "first-group adjective",
        "second-group adjective",
        "indeclinable adjective",
        "numeral adjective",
        "III declension noun",
      ],
      correct: 1,
    },
    {
      q: "In osteoporoses seniles, why does the adjective end in -es?",
      a: [
        "masculine gender",
        "feminine plural",
        "neuter plural",
        "genitive plural",
        "accusative case",
      ],
      correct: 1,
    },
    {
      q: "In asthma bronchiale, why does bronchiale end in -e?",
      a: [
        "because asthma is feminine",
        "because asthma is neuter",
        "because asthma is masculine",
        "because it is plural",
        "because it is genitive",
      ],
      correct: 1,
    },
    {
      q: "How is the term corpus callosum translated?",
      a: [
        "corpus callosum of the brain",
        "acute synovitis",
        "jugular vein",
        "chronic heart disease",
        "tumors",
      ],
      correct: 0,
    },
    {
      q: "What is the translation of corpora callosa?",
      a: [
        "corpora callosa of the brain",
        "benign tumors",
        "senile osteoporoses",
        "tumors",
        "chronic heart diseases",
      ],
      correct: 0,
    },
    {
      q: "What is the translation of tumor benignus?",
      a: [
        "tumors",
        "acute pneumonia",
        "benign tumor",
        "malignant cancer",
        "acute synovitis",
      ],
      correct: 2,
    },
    {
      q: "What does tumores benigni mean?",
      a: [
        "tumors",
        "benign tumors",
        "malignant cancers",
        "senile osteoporoses",
        "corpora callosa",
      ],
      correct: 1,
    },
    {
      q: "How is cancer malignus translated?",
      a: [
        "brittle bone",
        "tumors",
        "malignant cancer",
        "chronic heart disease",
        "gastric ulcer",
      ],
      correct: 2,
    },
    {
      q: "What is the translation of cancres maligni?",
      a: [
        "tumors",
        "malignant cancers",
        "long muscles",
        "acute pneumonia",
        "benign tumors",
      ],
      correct: 1,
    },
    {
      q: "What does fractura femoris mean?",
      a: [
        "fracture of the femur",
        "benign tumor",
        "joint inflammation",
        "tooth decay",
        "brittle bone",
      ],
      correct: 0,
    },
    {
      q: "What is the translation of fracturae femorum?",
      a: [
        "fracture of the femur",
        "fractures of the femurs",
        "senile osteoporosis",
        "acute pneumonia",
        "benign tumors",
      ],
      correct: 1,
    },
    {
      q: "What does pneumonia acuta mean?",
      a: [
        "acute synovitis",
        "chronic heart disease",
        "acute pneumonia",
        "tumors",
        "benign tumor",
      ],
      correct: 2,
    },
    {
      q: "How is pneumoniae acutae translated?",
      a: [
        "acute pneumonias",
        "senile osteoporoses",
        "tumors",
        "malignant cancers",
        "corpora callosa",
      ],
      correct: 0,
    },
    {
      q: "What does diabetes mellitus mean?",
      a: [
        "gastric ulcer",
        "diabetes mellitus",
        "tumors",
        "acute pneumonia",
        "benign tumors",
      ],
      correct: 1,
    },
    {
      q: "What is the translation of osteoporosis senilis?",
      a: [
        "diabetes mellitus",
        "chronic heart disease",
        "senile osteoporosis",
        "tumors",
        "malignant cancer",
      ],
      correct: 2,
    },
    {
      q: "What is the translation of osteoporoses seniles?",
      a: [
        "senile osteoporoses",
        "benign tumors",
        "joint inflammations",
        "malignant cancers",
        "acute pneumonias",
      ],
      correct: 0,
    },
    {
      q: "What is the translation of ulcus pepticum?",
      a: [
        "gastric ulcer",
        "acute pneumonia",
        "malignant cancer",
        "tumors",
        "benign tumor",
      ],
      correct: 0,
    },
    {
      q: "How is ulcera peptica translated?",
      a: [
        "gastric ulcer",
        "gastric ulcers",
        "chronic heart disease",
        "tooth decay",
        "benign tumors",
      ],
      correct: 1,
    },
    {
      q: "What does hepatitis viralis mean?",
      a: [
        "viral hepatitis",
        "tumors",
        "acute pneumonia",
        "brittle bone",
        "joint inflammation",
      ],
      correct: 0,
    },
    {
      q: "What is the translation of hepatitides virales?",
      a: [
        "viral hepatitides",
        "acute pneumonias",
        "malignant cancers",
        "tumors",
        "benign tumors",
      ],
      correct: 0,
    },
    {
      q: "What does lumen intestini mean?",
      a: [
        "tooth decay",
        "intestinal lumen",
        "malignant cancer",
        "joint inflammation",
        "tumors",
      ],
      correct: 1,
    },
    {
      q: "How is lumina intestinorum translated?",
      a: [
        "intestinal lumen",
        "joint inflammations",
        "intestinal lumina",
        "acute pneumonia",
        "brittle bones",
      ],
      correct: 2,
    },
    {
      q: "What does synovitis acuta mean?",
      a: [
        "acute synovitis",
        "benign tumor",
        "brittle bone",
        "gastric ulcer",
        "tooth decay",
      ],
      correct: 0,
    },
    {
      q: "What is the translation of synovites acutae?",
      a: [
        "acute synovitides",
        "benign tumors",
        "tumors",
        "acute pneumonias",
        "corpora callosa",
      ],
      correct: 0,
    },
    {
      q: "What does morbilli virus mean?",
      a: [
        "tumors",
        "measles virus",
        "malignant cancer",
        "brittle bone",
        "acute pneumonia",
      ],
      correct: 1,
    },
    {
      q: "What does cranium fragilis mean?",
      a: [
        "fragile skull",
        "deeply located skull",
        "basic skull",
        "long skull",
        "acute skull",
      ],
      correct: 0,
    },
    {
      q: "Which type of fiber is referred to by fibra elastica?",
      a: [
        "strong fiber",
        "elastic fiber",
        "most fertile fiber",
        "main fiber",
        "large fiber",
      ],
      correct: 1,
    },
    {
      q: "What does musculus fortissimus describe?",
      a: [
        "large muscle",
        "strongest muscle",
        "longest muscle",
        "elastic muscle",
        "fragile muscle",
      ],
      correct: 1,
    },
    {
      q: "What does arteria major indicate?",
      a: [
        "main artery",
        "large artery",
        "deeply located artery",
        "long artery",
        "elastic artery",
      ],
      correct: 1,
    },
    {
      q: "What characteristic does summus febris describe?",
      a: [
        "highest fever",
        "basic fever",
        "mild fever",
        "prolonged fever",
        "acute fever",
      ],
      correct: 0,
    },
    {
      q: "What does brevissimum intervallum indicate?",
      a: [
        "shortest interval",
        "large interval",
        "slow interval",
        "main interval",
        "long interval",
      ],
      correct: 0,
    },
    {
      q: "What is the positive degree of the adjective fortior?",
      a: ["fortissimus", "fortis", "longior", "dignior", "acutior"],
      correct: 1,
    },
    {
      q: "What is the superlative degree of longior?",
      a: ["longissimus", "longus", "fortior", "parvissimus", "dignior"],
      correct: 0,
    },
    {
      q: "What is the positive degree of acutissimus?",
      a: ["acutior", "acutus", "acutissimus", "fortior", "amarissimus"],
      correct: 1,
    },
    {
      q: "For the noun pulmo, pulmonis, which stem is correct?",
      a: ["pulmo-", "pulmon-", "pulm-", "pulmoni-", "pulmonis-"],
      correct: 1,
    },
    {
      q: "In the phrase pulmo dexter, what is the function of dexter?",
      a: ["noun", "verb", "adjective", "adverb", "genitive attribute"],
      correct: 2,
    },
    {
      q: "Choose the Nominative Plural form of ren, renis.",
      a: ["renes", "reni", "renum", "renibus", "renis"],
      correct: 0,
    },
    {
      q: "What is the stem of larynx, laryngis?",
      a: ["larynx-", "laryng-", "laryn-", "laryngi-", "laryngis-"],
      correct: 1,
    },
    {
      q: "In the phrase larynx acutus, why does acutus end in -us?",
      a: [
        "because larynx is neuter",
        "because larynx is feminine",
        "because larynx is masculine",
        "because larynx is plural",
        "because larynx is genitive",
      ],
      correct: 2,
    },
    {
      q: "What is the Nominative Plural form of flos, floris?",
      a: ["flori", "flores", "floras", "floris", "florum"],
      correct: 1,
    },
    {
      q: "Which option indicates a III declension masculine noun?",
      a: [
        "Genitive -ae",
        "Genitive -i",
        "Genitive -is",
        "Nominative -a",
        "Nominative -um",
      ],
      correct: 2,
    },
    {
      q: "To which gender does the noun mater belong?",
      a: ["Masculine", "Neuter", "Feminine", "Indeclinable", "Plural only"],
      correct: 2,
    },
    {
      q: "In the phrase pia mater, which explanation is grammatically correct?",
      a: [
        "mater – masculine",
        "mater – feminine",
        "pia – noun",
        "pia – verb",
        "no agreement",
      ],
      correct: 1,
    },
    {
      q: "To which gender does os, ossis belong?",
      a: ["Masculine", "Feminine", "Neuter", "Dual gender", "Indeclinable"],
      correct: 2,
    },
    {
      q: "In musculus flexor, what is flexor?",
      a: [
        "I declension adjective",
        "III declension noun",
        "Adverb",
        "Verb",
        "Indeclinable adjective",
      ],
      correct: 1,
    },
    {
      q: "What is the translation of musculus adductor?",
      a: [
        "flexor muscle",
        "extensor muscle",
        "adductor muscle",
        "abductor muscle",
        "rotator muscle",
      ],
      correct: 2,
    },
    {
      q: "What is the meaning of calor, caloris?",
      a: ["cold", "pain", "temperature", "smell", "heat"],
      correct: 4,
    },
    {
      q: "Choose the Genitive Singular form of dolor, doloris.",
      a: ["dolor", "dolore", "doloris", "dolorem", "doloribus"],
      correct: 2,
    },
    {
      q: "Which option is fully correct grammatically and terminologically?",
      a: [
        "musculus flexoris",
        "musculi flexora",
        "musculus flexor",
        "musculus flexorum",
        "musculus flexore",
      ],
      correct: 2,
    },
    {
      q: "Determine the meanings and declension of metastasis, contusio, articulatio.",
      a: [
        "metastasis, bruise, joint — I declension feminine",
        "metastasis, contusion, joint — III declension feminine",
        "metastasis, contusion, joint — III declension masculine",
        "metastasis, swelling, joint — II declension",
        "metastasis, injury, joint — III declension neuter",
      ],
      correct: 1,
    },
    {
      q: "Determine the meanings and grammatical classification of cavitas, auris, pars.",
      a: [
        "cavity, ear, part — III declension feminine",
        "cavity, ear, part — II declension",
        "cavity, ear, part — III declension masculine",
        "cavity, hearing, part — I declension",
        "cavity, ear, fragment — III declension neuter",
      ],
      correct: 0,
    },
    {
      q: "Translate and classify cartilago, articulatio, hirudo.",
      a: [
        "cartilage, joint, leech — III declension feminine",
        "cartilage, ligament, leech — II declension",
        "cartilage, joint, worm — III declension masculine",
        "cartilage, joint, leech — I declension",
        "cartilage, joint, leech — III declension neuter",
      ],
      correct: 0,
    },
    {
      q: "Determine the meanings and grammatical properties of radix, meninx, pix.",
      a: [
        "root, meninges, resin — III declension feminine",
        "root, brain, resin — II declension",
        "root, meninges, resin — III declension masculine",
        "root, meninges, pitch — I declension",
        "root, meninges, resin — III declension neuter",
      ],
      correct: 0,
    },
    {
      q: "Translate and classify crisis, diagnosis, lysis.",
      a: [
        "crisis, diagnosis, lysis — III declension feminine",
        "crisis, determination, lysis — II declension",
        "crisis, diagnosis, lysis — III declension masculine",
        "crisis, diagnosis, dissolution — I declension",
        "crisis, diagnosis, lysis — III declension neuter",
      ],
      correct: 0,
    },
    {
      q: "Translate and classify anamnesis, genesis, synthesis.",
      a: [
        "anamnesis, origin, synthesis — III declension feminine",
        "anamnesis, formation, synthesis — II declension",
        "history, origin, synthesis — III declension masculine",
        "anamnesis, genesis, synthesis — I declension",
        "anamnesis, origin, synthesis — III declension neuter",
      ],
      correct: 0,
    },
  ],
};
