// questions.js
window.TEST_QUESTIONS = {
  topic1: [
    {
      q: "A student is studying the cell as the fundamental basis that determines the structure and function of the organism. This definition belongs to which scientific field?",
      a: [
        "Cell biology",
        "Molecular genetics",
        "Histology",
        "Embryology",
        "Biochemistry",
      ],
      correct: 0,
    },
    {
      q: "From a scientific perspective, what does dividing cell biology into two main branches provide?",
      a: [
        "Separation of structure and heredity",
        "Differentiation of tissues and organs",
        "Analysis of metabolism",
        "Determination of energy balance",
        "Assessment of population growth",
      ],
      correct: 0,
    },
    {
      q: "Which of the following processes does NOT belong to the cell division branch?",
      a: [
        "Cell metabolism",
        "Cell cycle",
        "Gene expression",
        "Cell organelles",
        "Cell-to-cell communication",
      ],
      correct: 2,
    },
    {
      q: "Identify the incorrectly listed primary subject studied in the genetics branch.",
      a: [
        "Genetic inheritance",
        "Hereditary traits",
        "Chromosome structure",
        "Cell metabolism",
        "DNA expression",
      ],
      correct: 3,
    },
    {
      q: "In the levels of biological organization, which level comes immediately after organelles?",
      a: ["Cell", "Tissue", "Organ", "Molecule", "Organism"],
      correct: 0,
    },
    {
      q: "Which option is incorrectly listed as an inorganic component of the cell?",
      a: ["Water", "Macroelements", "Microelements", "Protein", "Ions"],
      correct: 3,
    },
    {
      q: "Which of the following carbohydrates is NOT a polysaccharide?",
      a: ["Starch", "Cellulose", "Glycogen", "Chitin", "Lactose"],
      correct: 4,
    },
    {
      q: "Which structural level of a protein involves only peptide bonds?",
      a: ["Primary", "Secondary", "Tertiary", "Quaternary", "Denatured"],
      correct: 0,
    },
    {
      q: "Disulfide (S–S) bonds are characteristic of which protein structure?",
      a: ["Primary", "Secondary", "Tertiary", "Quaternary", "Fragmented"],
      correct: 2,
    },
    {
      q: "What process results in loss of protein function due to decreased pH and increased temperature?",
      a: [
        "Denaturation",
        "Renaturation",
        "Glycosylation",
        "Polymerization",
        "Oxidation",
      ],
      correct: 0,
    },
    {
      q: "What is the process called in which a protein is restored with the help of chaperone proteins?",
      a: [
        "Renaturation",
        "Denaturation",
        "Translation",
        "Replication",
        "Isomerization",
      ],
      correct: 0,
    },
    {
      q: "What is the main difference between glycoproteins and peptidoglycans?",
      a: [
        "Carbohydrate content",
        "Protein composition",
        "Type of bonding",
        "Charge characteristics",
        "Localization area",
      ],
      correct: 0,
    },
    {
      q: "O-linked glycosylation occurs on which amino acids?",
      a: [
        "Serine and threonine",
        "Asparagine and glycine",
        "Alanine and valine",
        "Lysine and arginine",
        "Phenylalanine and tyrosine",
      ],
      correct: 0,
    },
    {
      q: "What is the primary function of sialic acids on the cell surface?",
      a: [
        "Providing negative charge",
        "Producing energy",
        "Accelerating protein synthesis",
        "Protecting DNA",
        "Increasing ion exchange",
      ],
      correct: 0,
    },
    {
      q: "Which of the following substances is classified as a glycosaminoglycan?",
      a: ["Hyaluronic acid", "Glycogen", "Sucrose", "Lactose", "Chitin"],
      correct: 0,
    },
    {
      q: "What is the main reason lipids are insoluble in water?",
      a: [
        "Hydrophobic properties",
        "Degree of ionization",
        "Molecular size",
        "Chain length",
        "Number of bonds",
      ],
      correct: 0,
    },
    {
      q: "What is the protein component of a lipoprotein called?",
      a: ["Apoprotein", "Glycoprotein", "Proteoglycan", "Enzyme", "Chaperone"],
      correct: 0,
    },
    {
      q: "Which lipoprotein is considered the most dangerous in atherosclerosis?",
      a: ["LDL", "HDL", "VLDL", "IDL", "Chylomicron"],
      correct: 0,
    },
    {
      q: "What is the main chemical difference between DNA and RNA?",
      a: [
        "Sugar and nitrogenous base",
        "Phosphate group",
        "Chain length",
        "Type of bonding",
        "Charge amount",
      ],
      correct: 0,
    },
    {
      q: "DNA in chromosomes is associated with which proteins?",
      a: [
        "Histone proteins",
        "Enzymatic proteins",
        "Structural proteins",
        "Transport proteins",
        "Membrane proteins",
      ],
      correct: 0,
    },
  ],
  topic2: [
    {
      q: "Which main biological function is represented by the cell membrane separating internal cellular structures from the external environment?",
      a: [
        "Performing a selective barrier function",
        "Providing energy production",
        "Storing genetic information",
        "Controlling protein synthesis",
        "Accelerating metabolic processes",
      ],
      correct: 0,
    },
    {
      q: "Which membrane function is responsible for extracellular signals triggering a biological response inside the cell?",
      a: [
        "Signal transduction function",
        "Mechanical protection function",
        "Structural support function",
        "Energy exchange function",
        "Transport accumulation function",
      ],
      correct: 0,
    },
    {
      q: "What does the asymmetric structure of the cell membrane indicate?",
      a: [
        "Different compositions of inner and outer layers",
        "All lipids are equally distributed",
        "Proteins are only on the outer surface",
        "Membrane thickness is variable",
        "Carbohydrates are absent",
      ],
      correct: 0,
    },
    {
      q: "What is the accepted average thickness of the cell membrane?",
      a: ["7.5 nm", "15 nm", "3.5 nm", "25 nm", "1.5 nm"],
      correct: 0,
    },
    {
      q: "Which of the following components is NOT found in the cell membrane?",
      a: [
        "Nucleic acids",
        "Phospholipids",
        "Glycoproteins",
        "Carbohydrates",
        "Membrane proteins",
      ],
      correct: 0,
    },
    {
      q: "Which property of the lipid bilayer prevents free passage of ions?",
      a: [
        "Its nonpolar hydrophobic core",
        "Its asymmetric arrangement",
        "High protein content",
        "Carbohydrate layer",
        "Degree of thickness",
      ],
      correct: 0,
    },
    {
      q: "Which feature best defines an amphipathic molecule?",
      a: [
        "Having both hydrophilic and hydrophobic regions",
        "Being soluble only in water",
        "Being soluble only in lipids",
        "Having a charged structure",
        "Being composed only of proteins",
      ],
      correct: 0,
    },
    {
      q: "Which lipid type is most abundant in the cell membrane?",
      a: ["Phospholipids", "Glycolipids", "Steroids", "Triglycerides", "Waxes"],
      correct: 0,
    },
    {
      q: "In which membrane layer is phosphatidylcholine mainly located?",
      a: [
        "Outer leaflet",
        "Inner leaflet",
        "Equally in both leaflets",
        "Only in mitochondria",
        "Only in nuclear membrane",
      ],
      correct: 0,
    },
    {
      q: "Phosphatidylserine and phosphatidylinositol are characteristic of which layer?",
      a: [
        "Inner leaflet",
        "Outer leaflet",
        "Only cell wall",
        "Only endoplasmic reticulum",
        "Only Golgi apparatus",
      ],
      correct: 0,
    },
    {
      q: "What does the fluid mosaic model of the membrane explain?",
      a: [
        "Mobility of proteins within the lipid bilayer",
        "Strict static nature of the membrane",
        "Composition of only lipids",
        "Free passage of ions",
        "Absence of carbohydrates",
      ],
      correct: 0,
    },
    {
      q: "What is the main characteristic of peripheral membrane proteins?",
      a: [
        "They do not span the lipid bilayer",
        "They possess transmembrane domains",
        "They are located only on the outer surface",
        "They function only as enzymes",
        "They occupy the hydrophobic core",
      ],
      correct: 0,
    },
    {
      q: "Which function best distinguishes integral membrane proteins?",
      a: [
        "Acting as receptors and signal transducers",
        "Providing only structural support",
        "Producing cellular energy",
        "Replicating DNA",
        "Regulating protein synthesis",
      ],
      correct: 0,
    },
    {
      q: "Proteins attached to the membrane via GPI anchors belong to which group?",
      a: [
        "Peripheral membrane proteins",
        "Integral strictly transmembrane proteins",
        "Nuclear proteins",
        "Cytoskeletal proteins",
        "Secretory proteins",
      ],
      correct: 0,
    },
    {
      q: "Which proteins mainly participate in cell adhesion?",
      a: [
        "Integral membrane proteins",
        "Peripheral cytoplasmic proteins",
        "Enzymatic proteins",
        "Histone proteins",
        "Chaperone proteins",
      ],
      correct: 0,
    },
    {
      q: "What does the transition of membrane proteins from peripheral to integral indicate?",
      a: [
        "Functional adaptability",
        "Membrane destruction",
        "Lipid bilayer degradation",
        "Ion balance disturbance",
        "Energy deficiency",
      ],
      correct: 0,
    },
    {
      q: "What is the main reason charged ions cannot pass through the lipid bilayer?",
      a: [
        "Presence of a hydrophobic environment",
        "High protein concentration",
        "Carbohydrate layer",
        "Membrane thickness",
        "Asymmetric structure",
      ],
      correct: 0,
    },
    {
      q: "What is the clinical significance of phosphatidylcholine in the colonic mucosa?",
      a: [
        "Creating a barrier against pathogens",
        "Producing energy",
        "Actively transporting ions",
        "Facilitating hormone synthesis",
        "Protecting DNA",
      ],
      correct: 0,
    },
    {
      q: "What are the transmembrane domains of integral membrane proteins mainly composed of?",
      a: [
        "Hydrophobic amino acids",
        "Charged amino acids",
        "Only glycosylated regions",
        "Only carbohydrates",
        "Only ions",
      ],
      correct: 0,
    },
    {
      q: "Through which membrane components is a cell recognized by the immune system?",
      a: [
        "Integral membrane proteins",
        "Hydrophobic core of lipid bilayer",
        "Steroids",
        "Phospholipid tails",
        "Pure carbohydrates",
      ],
      correct: 0,
    },
  ],
  topic3: [
    {
      q: "The strict regulation of substances through the cell membrane ensures which fundamental property of the cell?",
      a: [
        "Maintaining internal environment stability",
        "Increasing energy production",
        "Transmitting genetic information",
        "Accelerating cell division",
        "Activating protein synthesis",
      ],
      correct: 0,
    },
    {
      q: "The selective permeability of the membrane most accurately represents which situation?",
      a: [
        "Allowing some substances to pass while blocking others",
        "Allowing all ions to pass freely",
        "Allowing only water molecules to pass",
        "Allowing only large molecules to pass",
        "Working only with energy consumption",
      ],
      correct: 0,
    },
    {
      q: "Transport that occurs without energy consumption and along a concentration gradient belongs to which type?",
      a: [
        "Passive transport",
        "Primary active transport",
        "Secondary active transport",
        "Vesicular transport",
        "Transcytosis",
      ],
      correct: 0,
    },
    {
      q: "In simple diffusion, the movement of substances depends on what?",
      a: [
        "Concentration and electrochemical gradient",
        "ATP hydrolysis",
        "Activity of transport proteins",
        "Vesicle formation",
        "Membrane thickness",
      ],
      correct: 0,
    },
    {
      q: "Which group of substances primarily passes through simple diffusion?",
      a: [
        "O2, CO2, H2O",
        "Na+, K+, Ca2+",
        "Glucose and amino acids",
        "Proteins and peptides",
        "DNA and RNA",
      ],
      correct: 0,
    },
    {
      q: "What is the key distinguishing feature of facilitated diffusion?",
      a: [
        "It uses protein channels or carrier proteins",
        "It consumes ATP",
        "It moves against the gradient",
        "It passes only water molecules",
        "It involves vesicle formation",
      ],
      correct: 0,
    },
    {
      q: "In cystinuria, the main defect is associated with which mechanism?",
      a: [
        "Abnormality of carrier proteins",
        "Blockage of simple diffusion",
        "Increased osmosis",
        "Defective exocytosis",
        "Impaired phagocytosis",
      ],
      correct: 0,
    },
    {
      q: "Transport that moves substances against a concentration gradient and requires energy is called?",
      a: [
        "Active transport",
        "Simple diffusion",
        "Facilitated diffusion",
        "Pinocytosis",
        "Osmosis",
      ],
      correct: 0,
    },
    {
      q: "In primary active transport, what is the energy source used?",
      a: ["ATP", "Ion gradient", "Membrane potential", "Glycogen", "NADH"],
      correct: 0,
    },
    {
      q: "From where does secondary active transport obtain energy?",
      a: [
        "Pre-existing electrochemical gradient",
        "Direct ATP hydrolysis",
        "Protein denaturation",
        "Vesicle breakdown",
        "Osmotic pressure",
      ],
      correct: 0,
    },
    {
      q: "The SGLT2 transporter operates based on which mechanism?",
      a: [
        "Secondary active transport",
        "Primary active transport",
        "Simple diffusion",
        "Facilitated diffusion",
        "Transcytosis",
      ],
      correct: 0,
    },
    {
      q: "What is the main result of blocking SGLT2 in type 2 diabetes?",
      a: [
        "Increased glucose excretion in urine",
        "Increased glucose uptake into cells",
        "Enhanced ATP production",
        "Osmosis stops",
        "Reduced sodium secretion",
      ],
      correct: 0,
    },
    {
      q: "The transport of large molecules via vesicles belongs to which transport type?",
      a: [
        "Vesicular transport",
        "Passive transport",
        "Simple diffusion",
        "Osmosis",
        "Facilitated diffusion",
      ],
      correct: 0,
    },
    {
      q: "The process of releasing large molecules from the cell is called?",
      a: [
        "Exocytosis",
        "Endocytosis",
        "Phagocytosis",
        "Pinocytosis",
        "Transcytosis",
      ],
      correct: 0,
    },
    {
      q: "The uptake of bacteria and solid particles is carried out by which process?",
      a: [
        "Phagocytosis",
        "Pinocytosis",
        "Exocytosis",
        "Simple diffusion",
        "Osmosis",
      ],
      correct: 0,
    },
    {
      q: "The uptake of liquid into the cell via vesicles is called?",
      a: [
        "Pinocytosis",
        "Phagocytosis",
        "Exocytosis",
        "Transcytosis",
        "Active transport",
      ],
      correct: 0,
    },
    {
      q: "The process in which endocytosis and exocytosis occur together is called?",
      a: [
        "Transcytosis",
        "Pinocytosis",
        "Phagocytosis",
        "Simple diffusion",
        "Osmosis",
      ],
      correct: 0,
    },
    {
      q: "The movement of water through a semi-permeable membrane is called?",
      a: [
        "Osmosis",
        "Diffusion",
        "Active transport",
        "Exocytosis",
        "Filtration",
      ],
      correct: 0,
    },
    {
      q: "A solution that has the same osmotic pressure as the cell's interior is called?",
      a: [
        "Isotonic solution",
        "Hypertonic solution",
        "Hypotonic solution",
        "Hyperactive solution",
        "Passive solution",
      ],
      correct: 0,
    },
    {
      q: "What happens when a cell is placed in a hypotonic solution?",
      a: [
        "Water enters the cell, causing it to swell",
        "Water leaves the cell, causing it to shrink",
        "Transport stops",
        "ATP synthesis increases",
        "The membrane ruptures",
      ],
      correct: 0,
    },
  ],
  genetics: [
    {
      q: "What does the term genome refer to?",
      a: [
        "All DNA within the cell nucleus",
        "A single chromosome",
        "One functional gene",
        "Only coding regions of DNA",
      ],
      correct: 0,
    },
    {
      q: "Genes are best defined as:",
      a: [
        "DNA segments that code for proteins",
        "Entire chromosomes",
        "Noncoding DNA regions",
        "RNA molecules",
      ],
      correct: 0,
    },
    {
      q: "How many chromosomes are present in a normal human somatic cell?",
      a: ["23", "46", "44", "92"],
      correct: 1,
    },
    {
      q: "Homologous chromosomes are characterized by:",
      a: [
        "Containing identical copies of each gene",
        "Being present only in gametes",
        "Having different gene content",
        "Originating from the same parent",
      ],
      correct: 0,
    },
    {
      q: "Somatic cells are classified as diploid because they contain:",
      a: [
        "Two sets of chromosomes",
        "Only one chromosome set",
        "Only autosomes",
        "Only sex chromosomes",
      ],
      correct: 0,
    },
    {
      q: "The primary function of meiosis is to:",
      a: [
        "Produce haploid gametes",
        "Create identical daughter cells",
        "Repair damaged DNA",
        "Increase chromosome number",
      ],
      correct: 0,
    },
    {
      q: "During mitosis, DNA replication occurs in which phase?",
      a: ["G1 phase", "S phase", "G2 phase", "M phase"],
      correct: 1,
    },
    {
      q: "An allele is best described as:",
      a: [
        "A variant form of a gene",
        "A complete chromosome",
        "A noncoding DNA region",
        "A protein product",
      ],
      correct: 0,
    },
    {
      q: "The physical location of a gene on a chromosome is called the:",
      a: ["Allele", "Genome", "Locus", "Phenotype"],
      correct: 2,
    },
    {
      q: "Genotype refers to:",
      a: [
        "The genetic makeup of an individual",
        "Observable physical traits",
        "Environmental influence",
        "Protein expression level",
      ],
      correct: 0,
    },
    {
      q: "Phenotype is defined as:",
      a: [
        "Observable traits produced by genotype",
        "DNA sequence composition",
        "Chromosome number",
        "Gene mutation rate",
      ],
      correct: 0,
    },
    {
      q: "A wild-type allele is considered:",
      a: [
        "The most common normal allele",
        "Always pathogenic",
        "Always recessive",
        "Absent in populations",
      ],
      correct: 0,
    },
    {
      q: "An individual with genotype Aa is described as:",
      a: ["Homozygous", "Heterozygous", "Hemizygous", "Nullizygous"],
      correct: 1,
    },
    {
      q: "Germline mutations are clinically important because they:",
      a: [
        "Can be inherited by offspring",
        "Occur only in adulthood",
        "Affect single tissues only",
        "Are never pathogenic",
      ],
      correct: 0,
    },
    {
      q: "A recessive disorder requires which genotype to be expressed?",
      a: ["AA", "Aa", "aa", "A–"],
      correct: 2,
    },
    {
      q: "Codominance is best illustrated by which example?",
      a: [
        "AB blood group expressing both antigens",
        "Autosomal recessive inheritance",
        "Incomplete penetrance",
        "X-linked disorders",
      ],
      correct: 0,
    },
    {
      q: "Which genotype is associated with severe α1-antitrypsin deficiency?",
      a: ["MM", "MS", "MZ", "ZZ"],
      correct: 3,
    },
    {
      q: "Penetrance refers to:",
      a: [
        "Proportion of mutation carriers who show disease",
        "Severity of disease expression",
        "Number of alleles involved",
        "Age of disease onset",
      ],
      correct: 0,
    },
    {
      q: "BRCA1 and BRCA2 mutations are characterized by:",
      a: [
        "Autosomal dominant inheritance with incomplete penetrance",
        "Autosomal recessive inheritance",
        "X-linked inheritance",
        "Mitochondrial inheritance",
      ],
      correct: 0,
    },
    {
      q: "Variable severity of the same genetic disorder is known as:",
      a: ["Penetrance", "Expressivity", "Pleiotropy", "Mosaicism"],
      correct: 1,
    },
    {
      q: "Pleiotropy occurs when:",
      a: [
        "One gene affects multiple organ systems",
        "Multiple genes affect one trait",
        "A mutation has no effect",
        "Only somatic cells are involved",
      ],
      correct: 0,
    },
    {
      q: "The two-hit hypothesis applies primarily to:",
      a: [
        "Tumor suppressor genes",
        "Oncogenes",
        "Mitochondrial genes",
        "Imprinted genes",
      ],
      correct: 0,
    },
    {
      q: "Hereditary retinoblastoma develops because:",
      a: [
        "One germline and one somatic mutation occur",
        "Two somatic mutations occur late",
        "Only one mutation is sufficient",
        "It is X-linked",
      ],
      correct: 0,
    },
    {
      q: "Familial adenomatous polyposis is caused by mutation in which gene?",
      a: ["TP53", "APC", "BRCA1", "RB"],
      correct: 1,
    },
    {
      q: "Li-Fraumeni syndrome is associated with mutation of:",
      a: ["RB", "APC", "TP53", "MSH2"],
      correct: 2,
    },
    {
      q: "Mosaicism refers to:",
      a: [
        "Genetic differences among cells of the same individual",
        "Different alleles on homologous chromosomes",
        "Inheritance of two mutant alleles",
        "Environmental gene modification",
      ],
      correct: 0,
    },
    {
      q: "McCune-Albright syndrome is caused by:",
      a: [
        "Post-zygotic somatic mutation",
        "Inherited germline mutation",
        "X-linked recessive mutation",
        "Mitochondrial mutation",
      ],
      correct: 0,
    },
    {
      q: "Allelic heterogeneity means:",
      a: [
        "Different mutations within the same gene cause one disease",
        "One mutation causes multiple diseases",
        "Different genes cause different diseases",
        "Identical mutations cause different traits",
      ],
      correct: 0,
    },
    {
      q: "Locus heterogeneity is best described as:",
      a: [
        "Mutations in different genes causing the same disease",
        "Different alleles of one gene",
        "Somatic and germline mutations together",
        "Incomplete penetrance",
      ],
      correct: 0,
    },
  ],
};
