// questions.js
window.TEST_QUESTIONS = {
  topic1: [
    {
      q: "Talaba hujayraning fundamental negiz sifatida organizm tuzilishi va funksiyasini belgilashini o‘rganmoqda. Bu ta’rif qaysi fan doirasiga to‘g‘ri keladi?",
      a: [
        "Hujayra biologiyasi",
        "Molekulyar genetika",
        "Gistologiya",
        "Embriologiya",
        "Biokimyo",
      ],
      correct: 0,
    },
    {
      q: "Hujayra biologiyasi fanining ikki asosiy bo‘limga ajratilishi ilmiy jihatdan nimani ta’minlaydi?",
      a: [
        "Tuzilish va irsiyat ajratilishi",
        "To‘qima va organ farqlanishi",
        "Modda almashinuvi tahlili",
        "Energiya balansini aniqlash",
        "Populyatsiya o‘sishini baholash",
      ],
      correct: 0,
    },
    {
      q: "Quyidagi jarayonlardan qaysi biri hujayra bo‘limiga kirmaydi?",
      a: [
        "Hujayra metabolizmi",
        "Hujayra sikli",
        "Gen ifodalanishi",
        "Hujayra organellalari",
        "Hujayralararo aloqa",
      ],
      correct: 2,
    },
    {
      q: "Genetika bo‘limining asosiy o‘rganish obyekti noto‘g‘ri ko‘rsatilgan javobni aniqlang.",
      a: [
        "Genetik nasldorlik",
        "Irsiy belgilar",
        "Xromosoma tuzilishi",
        "Hujayra metabolizmi",
        "DNK ifodalanishi",
      ],
      correct: 3,
    },
    {
      q: "Hayotning tuzilish darajalarida organoidlardan keyingi daraja qaysi hisoblanadi?",
      a: ["Hujayra", "To‘qima", "Organ", "Molekula", "Organizm"],
      correct: 0,
    },
    {
      q: "Hujayraning kimyoviy tarkibiga kiruvchi anorganik modda noto‘g‘ri ko‘rsatilgan javobni toping.",
      a: ["Suv", "Makroelement", "Mikroelement", "Oqsil", "Ionlar"],
      correct: 3,
    },
    {
      q: "Quyidagi uglevodlardan qaysi biri polisaxarid hisoblanmaydi?",
      a: ["Kraxmal", "Selluloza", "Glikogen", "Xitin", "Laktoza"],
      correct: 4,
    },
    {
      q: "Oqsil molekulasida faqat peptid bog‘lar qatnashadigan strukturaviy daraja qaysi?",
      a: [
        "Birlamchi",
        "Ikkilamchi",
        "Uchlamchi",
        "To‘rtlamchi",
        "Denaturatsiyalangan",
      ],
      correct: 0,
    },
    {
      q: "Disulfid (S–S) bog‘lari qaysi oqsil strukturasi uchun xos?",
      a: [
        "Birlamchi",
        "Ikkilamchi",
        "Uchlamchi",
        "To‘rtlamchi",
        "Fragmentlangan",
      ],
      correct: 2,
    },
    {
      q: "pH pasayishi va harorat oshishi oqibatida oqsil funksiyasining yo‘qolishi qanday jarayon?",
      a: [
        "Denaturatsiya",
        "Renaturatsiya",
        "Glikozillanish",
        "Polimerizatsiya",
        "Oksidlanish",
      ],
      correct: 0,
    },
    {
      q: "Shaperon oqsillari ishtirokida oqsilning qayta tiklanishi nima deb ataladi?",
      a: [
        "Renaturatsiya",
        "Denaturatsiya",
        "Translyatsiya",
        "Replikatsiya",
        "Izomerizatsiya",
      ],
      correct: 0,
    },
    {
      q: "Glikoprotein va peptidoglikan orasidagi asosiy farq nimada?",
      a: [
        "Uglevod miqdorida",
        "Oqsil tarkibida",
        "Bog‘lanish turida",
        "Zaryad xususiyatida",
        "Joylashish hududida",
      ],
      correct: 0,
    },
    {
      q: "O-bog‘langan glikozillanish qaysi aminokislotalarda uchraydi?",
      a: [
        "Serin va treonin",
        "Asparagin va glitsin",
        "Alanin va valin",
        "Lizin va arginin",
        "Fenilalanin va tirozin",
      ],
      correct: 0,
    },
    {
      q: "Sial kislotalarning hujayra yuzasidagi asosiy vazifasi nimadan iborat?",
      a: [
        "Manfiy zaryad berish",
        "Energiya ishlab chiqarish",
        "Oqsil sintezini tezlatish",
        "DNKni himoyalash",
        "Ion almashinuvini oshirish",
      ],
      correct: 0,
    },
    {
      q: "Quyidagi moddalar ichidan glikozaminoglikanlarga mansubini aniqlang.",
      a: ["Gialuron kislota", "Glikogen", "Saxaroza", "Laktoza", "Xitin"],
      correct: 0,
    },
    {
      q: "Lipidlarning suvda erimasligining asosiy sababi nima?",
      a: [
        "Gidrofob xususiyati",
        "Ionlanish darajasi",
        "Molekula kattaligi",
        "Zanjir uzunligi",
        "Bog‘lanish soni",
      ],
      correct: 0,
    },
    {
      q: "Lipoprotein tarkibidagi oqsil qismi qanday nomlanadi?",
      a: ["Apoprotein", "Glikoprotein", "Proteoglikan", "Ferment", "Shaperon"],
      correct: 0,
    },
    {
      q: "Aterosklerozda eng xavfli hisoblangan lipoprotein qaysi?",
      a: ["LDL", "HDL", "VLDL", "IDL", "Xilomikron"],
      correct: 0,
    },
    {
      q: "DNK va RNK o‘rtasidagi asosiy kimyoviy farq nimada?",
      a: [
        "Uglevod va azot asosida",
        "Fosfat qoldig‘ida",
        "Zanjir uzunligida",
        "Bog‘lanish turida",
        "Zaryad miqdorida",
      ],
      correct: 0,
    },
    {
      q: "Xromosoma tarkibidagi DNK qaysi oqsillar bilan bog‘langan?",
      a: [
        "Giston oqsillari",
        "Ferment oqsillari",
        "Struktur oqsillar",
        "Transport oqsillari",
        "Membrana oqsillari",
      ],
      correct: 0,
    },
  ],
  topic2: [
    {
      q: "Hujayra ichini tashqi muhitdan ajratib turuvchi asosiy tuzilma qaysi?",
      a: [
        "Hujayra membranasi",
        "Yadro qobig‘i",
        "Mitoxondriya",
        "Sitoplazma",
        "Endoplazmatik to‘r",
      ],
      correct: 0,
    },
    {
      q: "Plazmolemma orqali hujayra uchun zarur moddalarning kirib-chiqishi qaysi funksiyaga kiradi?",
      a: [
        "Transport funksiyasi",
        "Energetik funksiyasi",
        "Genetik boshqaruv",
        "Oqsil sintezi",
        "Signal almashinuvi",
      ],
      correct: 0,
    },

    {
      q: "Plazmolemmaning o‘rtacha qalinligi qancha?",
      a: ["7.5 nm", "15 nm", "3 nm", "25 nm", "5.5 nm"],
      correct: 0,
    },
    {
      q: "Hujayra membranasida uchramaydigan modda qaysi?",
      a: [
        "Nuklein kislotalar",
        "Fosfolipidlar",
        "Glikoproteinlar",
        "Karbogidratlar",
        "Xolesterol",
      ],
      correct: 0,
    },
    {
      q: "Lipid qo‘shqavat qaysi moddalarga oson o‘tkazuvchan?",
      a: [
        "Qutbsiz va yog‘da eruvchan",
        "Zaryadlangan ionlar",
        "Periferik va integral",
        "Oqsil va uglevodlar",
        "Aminokislotalar",
      ],
      correct: 0,
    },
    {
      q: "Ionlarning membranadan o‘ta olmasligining sababi nima?",
      a: [
        "Gidrofob yadro",
        "Proteinlar kamligi",
        "Membrana yupqaligi",
        "Karbogidrat qatlami",
        "Asimmetriklik funksiya",
      ],
      correct: 0,
    },
    {
      q: "Fosfolipidlarning amfipatikligi nimani anglatadi?",
      a: [
        "Gidrofil va gidrofob",
        "Faqat suvda eriydi",
        "Faqat yog‘da eriydi",
        "Zaryadli va zaryadsiz",
        "Qutbli va qutbsiz",
      ],
      correct: 0,
    },
    {
      q: "Hujayra membranasida eng ko‘p uchraydigan lipid turi qaysi?",
      a: [
        "Fosfolipidlar",
        "Glikolipidlar",
        "Steroidlar",
        "Triglitseridlar",
        "Mumlar",
      ],
      correct: 0,
    },
    {
      q: "Fosfatidilxolin asosan qaysi qavatda joylashadi?",
      a: [
        "Tashqi qavatda",
        "Ichki qavatda",
        "Har ikkala qavatda",
        "Yadro membranasida",
        "Mitoxondriyada",
      ],
      correct: 0,
    },
    {
      q: "Ichki qavat uchun xos fosfolipidlar qaysilar?",
      a: [
        "Fosfatidilserin va fosfatidilinozitol",
        "Fosfatidilxolin va sfingomiyelin",
        "Xolesterol",
        "Glikolipidlar",
        "Triglitseridlar",
      ],
      correct: 0,
    },
    {
      q: "Membrananing mozaik modeli nimani tushuntiradi?",
      a: [
        "Oqsillarning lipidlar orasida harakatlanishini",
        "Membrananing qattiqligini",
        "Uglevodlar iceberg kabi suzib yurishini",
        "Ionlarning erkin o‘tishini",
        "Statik tuzilmani",
      ],
      correct: 0,
    },
    {
      q: "Periferik membrana oqsillarining xususiyati qaysi?",
      a: [
        "Lipid qo‘shqavatni kesib o‘tmaydi",
        "Transmembranal domeni bor",
        "Faqat tashqi tomonda bo‘ladi",
        "Lipid qo'shqavatni kesib o'tadi",
        "Gidrofob yadroni egallaydi",
      ],
      correct: 0,
    },
    {
      q: "Integral membrana oqsillarining asosiy vazifasi qaysi?",
      a: [
        "Retseptor va adgeziya",
        "DNK replikatsiyasi",
        "ATP sintezi",
        "Oqsil parchalanishi",
        "Signal transduksiyasi, uglevod parchalanishi",
      ],
      correct: 0,
    },
    {
      q: "GPI orqali birikkan oqsillar qaysi turga kiradi?",
      a: ["Periferik", "Integral", "Yadro", "Sitoskelet", "Sekretor"],
      correct: 0,
    },
    {
      q: "Hujayraning immun tizim tomonidan tanilishi nimaga bog‘liq?",
      a: [
        "Integral membrana oqsillariga",
        "Lipid dumlariga",
        "Xolesterolga",
        "Fosfolipid boshlariga",
        "Periferik membrana oqsillariga",
      ],
      correct: 0,
    },
    {
      q: "Fosfatidilxolinning yo‘g‘on ichakdagi vazifasi nima?",
      a: [
        "Patogenlarga qarshi gidrofob to‘siq",
        "Energiya ishlab chiqarish",
        "Ion nasosi vazifasi",
        "Gormon sintezi",
        "Fosfatifilxolinni normal ishlashini ta'minlash",
      ],
      correct: 0,
    },
  ],

  topic3: [
    {
      q: "Membrana orqali moddalarning qat’iy nazoratda o‘tishi hujayrada nimani ta’minlaydi?",
      a: [
        "Ichki muhit barqarorligi",
        "Energiya ishlab chiqarish",
        "Genetik axborot uzatish",
        "Bo‘linish tezlashuvi",
        "Oqsil sintezi faolligi",
      ],
      correct: 0,
    },
    {
      q: "Selektiv o‘tkazuvchanlik mohiyati nimada ifodalanadi?",
      a: [
        "Tanlab o‘tkazish xususiyati",
        "Ionlarning erkin o‘tishi",
        "Faqat suv o‘tishi",
        "Yirik molekula o‘tishi",
        "Energiya talab qilinishi",
      ],
      correct: 0,
    },
    {
      q: "Energiya sarfisiz, gradient bo‘yicha kechuvchi transport turi qaysi?",
      a: [
        "Passiv transport turi",
        "Birlamchi aktiv turi",
        "Ikkilamchi aktiv turi",
        "Vezikular transport turi",
        "Transsitoz mexanizmi",
      ],
      correct: 0,
    },
    {
      q: "Oddiy diffuziyada modda harakati nimaga bog‘liq?",
      a: [
        "Konsentratsiya gradientiga",
        "ATF parchalanishiga",
        "Oqsil faolligiga",
        "Vezikula hosiliga",
        "Membrana qalinligiga",
      ],
      correct: 0,
    },
    {
      q: "Qaysi moddalarning o‘tishi oddiy diffuziya bilan kechadi?",
      a: [
        "Kichik qutbsiz molekulalar",
        "Zaryadlangan ionlar guruhi",
        "Yirik organik molekulalar",
        "Oqsil strukturalari",
        "Nuklein kislotalar",
      ],
      correct: 0,
    },
    {
      q: "Yengillashgan diffuziyaning asosiy belgisi qaysi?",
      a: [
        "Oqsil ishtiroki bilan",
        "ATF sarfi bilan",
        "Gradientga qarshi",
        "Vezikula orqali",
        "Suv bilan bog‘liq",
      ],
      correct: 0,
    },
    {
      q: "Sistinuriya kasalligi qaysi buzilish bilan bog‘liq?",
      a: [
        "Tashuvchi oqsil nuqsoni",
        "Oddiy diffuziya yetishmovchiligi",
        "Osmos kuchayishi holati",
        "Ekzotsitoz buzilishi",
        "Fagotsitoz pasayishi",
      ],
      correct: 0,
    },
    {
      q: "Gradientga qarshi va energiya bilan kechuvchi transport qaysi?",
      a: [
        "Aktiv transport turi",
        "Oddiy diffuziya turi",
        "Yengillashgan diffuziya",
        "Pinotsitoz jarayoni",
        "Osmos mexanizmi",
      ],
      correct: 0,
    },
    {
      q: "Birlamchi aktiv transport energiyani qayerdan oladi?",
      a: [
        "ATF parchalanishidan",
        "Ion gradientidan",
        "Membrana potensialidan",
        "Glikogen parchalanishidan",
        "NADH oksidlanishidan",
      ],
      correct: 0,
    },
    {
      q: "Ikkilamchi aktiv transport energiya manbai nima?",
      a: [
        "Elektrokimyoviy gradient",
        "Bevosita ATF",
        "Oqsil denaturatsiyasi",
        "Vezikula parchalanishi",
        "Osmotik bosim",
      ],
      correct: 0,
    },
    {
      q: "SGLT2 tashuvchisi qaysi mexanizm asosida ishlaydi?",
      a: [
        "Ikkilamchi aktiv transport",
        "Birlamchi aktiv transport",
        "Oddiy diffuziya",
        "Yengillashgan diffuziya",
        "Transsitoz mexanizmi",
      ],
      correct: 0,
    },
    {
      q: "SGLT2 bloklanganda asosiy klinik natija nima?",
      a: [
        "Glyukozuriya kuchayishi",
        "Hujayraga glyukoza kirishi",
        "ATF ishlab chiqarilishi",
        "Osmos to‘xtashi",
        "Natriy yo‘qolishi",
      ],
      correct: 0,
    },
    {
      q: "Yirik molekulalarning vezikula orqali o‘tishi qanday ataladi?",
      a: [
        "Vezikular transport",
        "Passiv transport",
        "Oddiy diffuziya",
        "Osmos jarayoni",
        "Yengillashgan diffuziya",
      ],
      correct: 0,
    },
    {
      q: "Hujayradan tashqariga modda chiqarilishi nima deyiladi?",
      a: [
        "Ekzotsitoz jarayoni",
        "Endotsitoz jarayoni",
        "Fagotsitoz jarayoni",
        "Pinotsitoz jarayoni",
        "Transsitoz jarayoni",
      ],
      correct: 0,
    },
    {
      q: "Qattiq zarrachalar yutilishi qaysi mexanizm bilan kechadi?",
      a: [
        "Fagotsitoz jarayoni",
        "Pinotsitoz jarayoni",
        "Ekzotsitoz jarayoni",
        "Oddiy diffuziya",
        "Osmos jarayoni",
      ],
      correct: 0,
    },
    {
      q: "Suyuqlikning vezikula orqali yutilishi nima deyiladi?",
      a: [
        "Pinotsitoz jarayoni",
        "Fagotsitoz jarayoni",
        "Ekzotsitoz jarayoni",
        "Transsitoz jarayoni",
        "Aktiv transport",
      ],
      correct: 0,
    },
    {
      q: "Endotsitoz va ekzotsitoz birga kechsa nima deyiladi?",
      a: [
        "Transsitoz jarayoni",
        "Pinotsitoz jarayoni",
        "Fagotsitoz jarayoni",
        "Oddiy diffuziya",
        "Osmos jarayoni",
      ],
      correct: 0,
    },
    {
      q: "Suvning yarimo‘tkazuvchan membrana orqali o‘tishi nima?",
      a: [
        "Osmos jarayoni",
        "Diffuziya jarayoni",
        "Aktiv transport",
        "Ekzotsitoz jarayoni",
        "Filtratsiya jarayoni",
      ],
      correct: 0,
    },
    {
      q: "Hujayra ichki suyuqligiga teng eritma qanday ataladi?",
      a: [
        "Izotonik eritma",
        "Gipertonik eritma",
        "Gipotonik eritma",
        "Giperaktiv eritma",
        "Passiv eritma",
      ],
      correct: 0,
    },
    {
      q: "Hujayra gipotonik muhitda qanday o‘zgaradi?",
      a: [
        "Suv kirib shishadi",
        "Suv chiqib kichrayadi",
        "Transport to‘xtaydi",
        "ATF ortib ketadi",
        "Membrana buziladi",
      ],
      correct: 0,
    },
  ],

  topic4: [
    {
      q: "Organella nima?",
      a: [
        "Hujayra faoliyati uchun zarur, maxsus vazifani bajaruvchi tuzilma",
        "Hujayra tashqi qobig‘i",
        "DNK ni faqat saqlovchi tuzilma",
        "Faqat energiya ishlab chiqaruvchi tuzilma",
        "Hujayra bo‘linishini boshqaruvchi tuzilma",
      ],
      correct: 0,
    },
    {
      q: "Quyidagi organellalardan qaysi biri membranasiz hisoblanadi?",
      a: [
        "Ribosoma",
        "Mitoxondriya",
        "Yadro",
        "Lizosoma",
        "Endoplazmatik to‘r",
      ],
      correct: 0,
    },
    {
      q: "Ikki qavatli membrana bilan o‘ralgan organellaga misol keltiring:",
      a: [
        "Mitoxondriya",
        "Ribosoma",
        "Lizosoma",
        "Golji apparati",
        "Sitoskelet",
      ],
      correct: 0,
    },
    {
      q: "Genetik materialni saqlovchi organellalarga misol keltiring:",
      a: [
        "Yadro va mitoxondriya",
        "Ribosoma va lizosoma",
        "Golji apparati va vakuola",
        "SET va DET",
        "Peroksisoma va proteasoma",
      ],
      correct: 0,
    },
    {
      q: "Endoplazmatik to‘rning ikki tarkibiy qismi qanday ataladi?",
      a: [
        "Donador ET va Silliq ET",
        "SET va Golji ET",
        "DET va lizosoma",
        "Ribosoma va mikronaycha",
        "Vakuola va peroksisoma",
      ],
      correct: 0,
    },
    {
      q: "Silliq endoplazmatik to‘rning asosiy vazifasi nima?",
      a: [
        "Lipid va steroid sintezi, detoksifikatsiya, kalsiy zaxira",
        "Protein sintezi",
        "DNK replikatsiyasi",
        "Vezikula tashilishi",
        "Mitoxondrial funksiyalarni boshqarish",
      ],
      correct: 0,
    },
    {
      q: "Donador endoplazmatik to‘r qaysi jarayonga mas’ul?",
      a: [
        "Protein translyatsiyasi va modifikatsiyasi",
        "Lipid sintezi",
        "Kalsiy zaxira",
        "Oqsillarni parchalash",
        "Hujayra skeletini shakllantirish",
      ],
      correct: 0,
    },
    {
      q: "Golji apparatining qabul qiluvchi va chiqaruvchi tomonlari qanday ataladi?",
      a: [
        "Cis va trans tomonlar",
        "Sis va ret tomonlar",
        "SET va DET",
        "Ribosomal va mikronaycha",
        "Vakuola va lizosoma",
      ],
      correct: 0,
    },
    {
      q: "Golji apparati ichida oqsillar qanday jarayonda saralanadi va modifikatsiya qilinadi?",
      a: [
        "Glikozilatsiya va funksional guruh qo‘shish",
        "ATP parchalanishi",
        "DNK transkripsiyasi",
        "Kalsiy saqlash",
        "Protein degradatsiyasi",
      ],
      correct: 0,
    },
    {
      q: "Mitoxondriya DNK ga ega bo‘lishining klinik ahamiyati nima?",
      a: [
        "Onadan bolaga o‘tadigan mitoxondrial kasalliklar",
        "ATP ishlab chiqarishni kuchaytirish",
        "Ribosoma faoliyatini nazorat qilish",
        "Golji apparati vazifasini oshirish",
        "Sitoskeletni mustahkamlash",
      ],
      correct: 0,
    },
    {
      q: "MELAS sindromi qaysi organella bilan bog‘liq?",
      a: ["Mitoxondriya", "Peroksisoma", "Lizosoma", "SET", "Golji apparati"],
      correct: 0,
    },
    {
      q: "Lizosomaning asosiy vazifasi nima?",
      a: [
        "Biopolimerlarni parchalash va hujayra hazmi",
        "Protein sintezi",
        "Lipid sintezi",
        "DNK saqlash",
        "Mikronaychalar hosil qilish",
      ],
      correct: 0,
    },
    {
      q: "Lizosomalardagi fermentlar qachon faol bo‘ladi?",
      a: [
        "pH pasayganda, ikkilamchi lizosomalarda",
        "SET da har doim",
        "Ribosomada oqsil sintezida",
        "Golji apparatiga yetganda",
        "Mitoxondriya matritsasida",
      ],
      correct: 0,
    },
    {
      q: "Peroksisomada vodorod peroksidni suvga aylantiruvchi ferment nima?",
      a: [
        "Katalaza",
        "ATPaza",
        "Glikozidaza",
        "Kollagenaza",
        "Transglutaminaza",
      ],
      correct: 0,
    },
    {
      q: "Proteasomaning asosiy vazifasi nima?",
      a: [
        "Shikastlangan va noto‘g‘ri sintezlangan oqsillarni parchalash",
        "Protein sintezini boshlash",
        "Lipidlarni ishlab chiqarish",
        "DNK replikatsiyasi",
        "Mikronaycha hosil qilish",
      ],
      correct: 0,
    },
    {
      q: "Sitoskeletning asosiy vazifasi nima?",
      a: [
        "Hujayraga shakl berish, organellalarni joylashtirish va transport yo‘lini ta’minlash",
        "Protein sintezini nazorat qilish",
        "Golji apparatini qo‘llab-quvvatlash",
        "Mitoxondriya funksiyasini oshirish",
        "Lizosomalarning harakatini to‘xtatish",
      ],
      correct: 0,
    },
    {
      q: "Mikrofilamentlar qaysi oqsildan tashkil topadi?",
      a: ["Aktin", "Keratins", "Tubulin", "Myosin", "Collagen"],
      correct: 0,
    },
    {
      q: "Oraliq filamentlar qaysi vazifani bajaradi?",
      a: [
        "Mekanik tayanch va hujayra ichidagi mustahkamlash",
        "Protein sintezini boshqarish",
        "Oqsillarni parchalash",
        "Kalsiy zaxira qilish",
        "Mitoxondrial energiya ishlab chiqarish",
      ],
      correct: 0,
    },
    {
      q: "Mikronaychalarning asosiy subbirliklari nima?",
      a: [
        "α-tubulin va β-tubulin dimerlari",
        "Aktin monomerlari",
        "Keratins",
        "Ribosomal RNK",
        "Katalaza",
      ],
      correct: 0,
    },
    {
      q: "Mikronaychalarning asosiy vazifasi nima?",
      a: [
        "Xromosomalarni mitozda tortish, transport yo‘llarini yaratish, hujayra shaklini saqlash",
        "Protein sintezini boshqarish",
        "Lipid sintezi",
        "Oqsil degradatsiyasi",
        "Kalsiy zaxira qilish",
      ],
      correct: 0,
    },
    {
      q: "Ribosoma asosiy vazifasi nima?",
      a: [
        "Protein sintezi",
        "Lipid sintezi",
        "DNK saqlash",
        "Oqsil degradatsiyasi",
        "Golji apparatida modifikatsiya",
      ],
      correct: 0,
    },
    {
      q: "Ribosoma tRNKlar uchun nechta saytga ega?",
      a: [
        "A, P va E saytlar",
        "C va D saytlar",
        "α va β saytlar",
        "Sis va trans saytlar",
        "DET va SET saytlar",
      ],
      correct: 0,
    },
    {
      q: "Translyatsiya jarayonida ribosoma tRNKlarni qanday ishlatadi?",
      a: [
        "A, P va E saytlar bo‘ylab harakatlantiradi",
        "Ribosoma ichida saqlaydi",
        "Golji apparatga yuboradi",
        "Mitoxondriya matritsasida eritadi",
        "Sitoskeletda mustahkamlaydi",
      ],
      correct: 0,
    },
    {
      q: "Hujayrada SET eng ko‘p uchraydigan hujayra qaysi?",
      a: ["Gepatotsit", "Eritrotsit", "Neyron", "Limfotsit", "Fibroblast"],
      correct: 0,
    },
    {
      q: "Proteasoma faoliyati patologik inhibitsiya qilinsa, nima yuz beradi?",
      a: [
        "Apoptoz hosil bo‘ladi",
        "Protein sintezi tezlashadi",
        "Lipidlar ko‘payadi",
        "Kalsiy zaxira oshadi",
        "Golji apparati kengayadi",
      ],
      correct: 0,
    },
    {
      q: "Peroksisoma vazifalariga quyidagilardan qaysi kiradi?",
      a: [
        "Cholesterol sintezi va juda uzun zanjirli yog‘ kislotalar oksidlanishi",
        "DNK replikatsiyasi",
        "Protein sintezi",
        "Mikronaychalarni hosil qilish",
        "Golji apparatidagi protein modifikatsiyasi",
      ],
      correct: 0,
    },
    {
      q: "SET da glyukoza 6-fosfataza yetishmovchiligi qaysi kasallikka olib keladi?",
      a: [
        "Glycogen Storage Disease",
        "MELAS",
        "Chidiyak Higashi",
        "Zellweger sindromi",
        "Hyperkalemiya",
      ],
      correct: 0,
    },
    {
      q: "DET asosiy klinik ahamiyati qaysi hujayralarda ko‘rinadi?",
      a: [
        "Jigar, oshqozon-ichak, endokrin va ekzokrin bez hujayralari",
        "Eritrotsitlar",
        "Limfotsitlar",
        "Muskul hujayralari",
        "Peroksisomalar",
      ],
      correct: 0,
    },
    {
      q: "Ribosoma va Golji apparat birgalikda qaysi jarayonda ishtirok etadi?",
      a: [
        "Protein sintezi va modifikatsiyasi",
        "Lipid detoksifikatsiyasi",
        "Mikronaycha hosil qilish",
        "Kalsiy zaxira",
        "Mitoxondrial energiya ishlab chiqarish",
      ],
      correct: 0,
    },
  ],
  topic5_6: [
    {
      q: "Hujayra yadrosining asosiy vazifasi nima?",
      a: [
        "Genetik materialni saqlash va hujayra faoliyatini boshqarish",
        "Protein sintezini boshlash",
        "Lipid sintezini ta’minlash",
        "Kalsiy zaxira qilish",
        "Sitoskeletni mustahkamlash",
      ],
      correct: 0,
    },
    {
      q: "Yadro qobig‘i qanday membranalardan tashkil topgan?",
      a: [
        "Tashqi va ichki ikki qavatli fosfolipid membranalari",
        "Faqat bitta lipid qavati",
        "Ribosoma bilan qoplangan membrana",
        "SET va DET membranalari",
        "Golji apparati membranasi",
      ],
      correct: 0,
    },
    {
      q: "Yadro teshikchalari (nuclear pores) vazifasi nima?",
      a: [
        "Moddalarning yadroga kirib-chiqishini tartibga solish",
        "Protein sintezini boshlash",
        "Lipid sintezini oshirish",
        "Xromosomalarni himoya qilish",
        "Mikronaycha hosil qilish",
      ],
      correct: 0,
    },
    {
      q: "Xromatin va xromosoma farqi nima?",
      a: [
        "Xromatin - bo‘linish paytida spirallashmagan, xromosoma - bo‘linishdan oldin spirallashgan DNK",
        "Xromatin faqat proteinlardan iborat, xromosoma faqat DNK",
        "Xromatin faqat hayvon hujayralarida, xromosoma - o‘simliklarda",
        "Xromatin DNKni parchalaydi, xromosoma sintezlaydi",
        "Xromatin ribosomada joylashadi, xromosoma mitoxondriyada",
      ],
      correct: 0,
    },
    {
      q: "Giston oqsillari qanday rol o‘ynaydi?",
      a: [
        "DNKni ixchamlashtirish va gen faolligini belgilash",
        "Protein modifikatsiyasini bajarish",
        "Lipidlarga signal uzatish",
        "Mikronaycha hosil qilish",
        "Hujayra bo‘linishini to‘xtatish",
      ],
      correct: 0,
    },
    {
      q: "Odam somatik hujayralaridagi xromosoma soni nechta?",
      a: ["46 ta (diploid 2n)", "23 ta (haploid)", "44 ta", "48 ta", "92 ta"],
      correct: 0,
    },
    {
      q: "Gomologik xromosomalar nima?",
      a: [
        "Bir xil shakl va genetik axborotni tashuvchi juft xromosomalar",
        "Mutatsiyaga uchragan xromosomalar",
        "Xromatinning faol shakli",
        "DNKni parchalaydigan organellalar",
        "Xromosoma ichidagi ribosomalar",
      ],
      correct: 0,
    },
    {
      q: "Aneuploidiya qaysi kasalliklarga olib keladi?",
      a: [
        "Daun sindromi, Klaynfelter sindromi, Turner sindromi",
        "Glikogen saqlash kasalligi",
        "MELAS",
        "Zellveger sindromi",
        "Chidiyak Higashi kasalligi",
      ],
      correct: 0,
    },
    {
      q: "Hujayralar signal uzatishda qaysi molekulalarni ishlatadi?",
      a: [
        "Ligandlar (gormon, mediator, oqsil yoki toksin)",
        "Faqat DNK molekulalari",
        "Faqat lipidlar",
        "Faqat mikronaychalar",
        "Faqat ribosomalar",
      ],
      correct: 0,
    },
    {
      q: "Autokrin signal uzatilishining xususiyati nima?",
      a: [
        "Hujayra o‘zi ishlab chiqargan ligand orqali o‘z retseptoriga ta’sir qiladi",
        "Hujayralar qon orqali uzoq masofaga signal yuboradi",
        "Faqat qo‘shni hujayralarga ta’sir qiladi",
        "Signal DNK ga kiradi",
        "Protein sintezini to‘xtatadi",
      ],
      correct: 0,
    },
    {
      q: "Parakrin signal uzatilishi qanday jarayonda sodir bo‘ladi?",
      a: [
        "Hujayralar qisqa masofada qo‘shni hujayralar bilan faoliyatini muvofiqlashtiradi",
        "Uzoq masofaga qon orqali signal uzatiladi",
        "O‘zi signalni o‘ziga yuboradi",
        "DNK o‘qiladi",
        "Ribosoma sintezini boshlaydi",
      ],
      correct: 0,
    },
    {
      q: "Endokrin signal uzatilishida qanday transport tizimi ishlatiladi?",
      a: [
        "Qon aylanish tizimi orqali uzoq masofaga ligand yetkaziladi",
        "Mikronaycha transporti",
        "Golji apparati orqali",
        "SET orqali",
        "Sitoskelet orqali",
      ],
      correct: 0,
    },
    {
      q: "Endokrin ligandlar odatda qaysi hujayralar tomonidan ishlab chiqariladi?",
      a: [
        "Ixtisoslashgan hujayralar: qalqonsimon, gipotalamus, gipofiz, jinsiy bezlar, oshqozon osti bezlari",
        "Ribosomalar",
        "Mikronaychalar",
        "Peroksisomalar",
        "Sitoskelet filamentlari",
      ],
      correct: 0,
    },
    {
      q: "Xromatin qanday fazada mavjud?",
      a: [
        "Hujayra o‘sish fazasida, bo‘linish amalga oshmayotgan paytda",
        "Mitoz paytida",
        "Meioz paytida",
        "Signal transduksiya vaqtida",
        "Protein modifikatsiyasida",
      ],
      correct: 0,
    },
    {
      q: "Xromosoma eukariot hujayralarda qanday shaklda bo‘ladi?",
      a: [
        "Chiziqli struktura, hujayra bo‘linishidan oldin kuchli spirallashgan",
        "Halqa shaklida",
        "Disk shaklida",
        "Tubalik shaklida",
        "Ixtiyoriy shaklda",
      ],
      correct: 0,
    },
    {
      q: "Ligand va retseptorning mosligi nima uchun muhim?",
      a: [
        "Signal uzatish faqat maxsus mos ligand-retseptor orqali sodir bo‘ladi",
        "DNK replikatsiyasi uchun",
        "Protein modifikatsiyasi uchun",
        "Lipidlarga transport uchun",
        "Mikronaycha hosil qilish uchun",
      ],
      correct: 0,
    },
    {
      q: "Yadro ichidagi suyuqlik qanday nomlanadi?",
      a: [
        "Nukleoplazma",
        "Sitoplazma",
        "Mitoxondrial matritsa",
        "Lizosomal matriks",
        "Golji bo‘shlig‘i",
      ],
      correct: 0,
    },
    {
      q: "DNKni erkin spirallashmagan holatda kim bilan bog‘langan?",
      a: [
        "Giston oqsillari bilan",
        "Mitoxondrial oqsillar bilan",
        "Ribosomal RNK bilan",
        "Peroksisomal ferment bilan",
        "Lipid molekulalar bilan",
      ],
      correct: 0,
    },
    {
      q: "Hujayralararo signal uzatilishning klinik ahamiyati nimada?",
      a: [
        "Organizmning biokimyoviy va fiziologik jarayonlarini muvofiqlashtirishda",
        "Protein sintezini to‘xtatishda",
        "Xromosoma sonini kamaytirishda",
        "Lipidlarga transportni oshirishda",
        "Mikronaychalarni hosil qilishda",
      ],
      correct: 0,
    },
    {
      q: "Ligand turi yo‘q bo‘lsa, nima sodir bo‘ladi?",
      a: [
        "Hujayralararo signal uzatilishi amalga oshmaydi",
        "Protein sintezi tezlashadi",
        "DNK degradatsiya qilinadi",
        "Mikronaychalar hosil bo‘ladi",
        "Golji apparati kengayadi",
      ],
      correct: 0,
    },
  ],
};
