window.TEST_QUESTIONS = {
  mock1: [
    {
      q: "Qorin pardasi qaysi hujayralardan tashkil topgan?",
      a: ["Epitelial", "Mezotelial", "Suyak", "Muskular", "Nerv hujayralar"],
      correct: 1,
    },
    {
      q: "Viseeral peritoneum",
      a: [
        "Somatik nervlar bilan innervatsiya qilinadi",
        "Og'riqni sezadi",
        "Og'riq sezmaydi",
        "Qorin devorini qoplaydi",
        "Fibrin hosil qiladi",
      ],
      correct: 2,
    },
    {
      q: "Katta charvi (omentum major) qanday vazifa bajaradi?",
      a: [
        "Jigarga qon yetkazadi",
        "Ichakni osib turadi",
        "Peritonitning yoyilishini oldini oladi",
        "Limfa tugunlarini yo'naltiradi",
        "Qorin bo'shlig'ini qisqa qiladi",
      ],
      correct: 2,
    },
    {
      q: "Katta charvi bo'ylab qaysi tomirlar o'tadi?",
      a: [
        "Chap va o'ng gastrik tomirlar",
        "Chap va o'ng gastroepiploik tomirlar",
        "Gepatogastrik va gepatoduodenal tomirlar",
        "Superior mesenteric arteriya",
        "Inferior mesenteric vena",
      ],
      correct: 1,
    },
    {
      q: "Gastrolienal boylam qaysi organlarni bog'laydi?",
      a: [
        "Oshqozon va taloq",
        "Oshqozon va jigar",
        "Jigar va duodenum",
        "Sigmoid ichak va bachadon",
        "Talaq va buyrak",
      ],
      correct: 0,
    },
    {
      q: "Lienorenal boylam qaysi organlarga boradi?",
      a: [
        "Oshqozon va taloq",
        "Taloq va chap buyrak",
        "Jigar va oshqozon",
        "Sigmoid va rektum",
        "Duodenum va jejunum",
      ],
      correct: 1,
    },
    {
      q: "Mesentery proper qaysi ichakni bog'laydi?",
      a: [
        "Oshqozon",
        "Jejunum va ileum",
        "Duodenum va jejunum",
        "Sigmoid ichak",
        "Appendix",
      ],
      correct: 1,
    },
    {
      q: "Transverse mesocolon qaysi organni qorinning orqa devoriga bog'laydi?",
      a: [
        "Ko’ndalang chambar ichak",
        "Sigmoid ichak",
        "Duodenum va Jejunum",
        "Jejunum, duodenum va ileum",
        "Oshqozon",
      ],
      correct: 0,
    },
    {
      q: "Mesoappendix qaysi tuzilmani bog'laydi?",
      a: [
        "Appendix vermiformis va jejunum",
        "Appendix vermiformis va ileum",
        "Appendix vermiformis va cecum",
        "Sigmoid ichak va rectum",
        "Oshqozon va duodenum",
      ],
      correct: 2,
    },
    {
      q: "Phrenicocolic ligament chap chambar ichak egriligidan qay tomon tortilgan?",
      a: [
        "Oshqozon",
        "O'ng chambar ichak egriligi",
        "Jigar",
        "Diafragma",
        "Sigmoid ichak",
      ],
      correct: 3,
    },
    {
      q: "Ligamentum falciforme nima qiladi?",
      a: [
        "Jigarni diafragmaga bog'laydi",
        "Talaqni oshqozonga bog'laydi",
        "Sigmoid ichakni chanoq devoriga bog'laydi",
        "Duodenumni orqa devorga bog'laydi",
        "Appendixni ileumga bog'laydi",
      ],
      correct: 0,
    },
    {
      q: "Ligamentum teres hepatis embrional davrda qaysi tuzilmaning qoldig'idir?",
      a: [
        "Ductus arteriosus",
        "Chap umbilical vena",
        "Ductus venosus",
        "Portal vena",
        "Superior mesenteric arteriya",
      ],
      correct: 1,
    },
    {
      q: "Tojsimon ligament qaysi organ bilan bog'liq?",
      a: [
        "Jigar va diafragma",
        "Oshqozon va taloq",
        "Jejunum va ileum",
        "Sigmoid va rectum",
        "Appendix",
      ],
      correct: 0,
    },
    {
      q: "Ligamentum venosum nima qoldig'i?",
      a: [
        "Ductus venosus",
        "Ductus arteriosus",
        "Chap umbilical vena",
        "Portal vena",
        "Superior mesenteric arteriya",
      ],
      correct: 0,
    },
    {
      q: "Kindik burmasi qaysi tuzilmalarni o'z ichiga oladi?",
      a: [
        "O'rta, medial va lateral kindik burmalari",
        "Oshqozon burmalari",
        "Jejunum burmalari",
        "Sigmoid burmalari",
        "Appendix burmalari",
      ],
      correct: 0,
    },
    {
      q: "Rectouterine burma qaysi bo'shliqni hosil qiladi?",
      a: [
        "Pouch of Douglas",
        "Omental bursa",
        "Subphrenic recess",
        "Morrison recess",
        "Paracolic gutter",
      ],
      correct: 0,
    },
    {
      q: "Ileocecal burma qaysi organlarni bog'laydi?",
      a: [
        "Terminal ileum va cecum",
        "Oshqozon va duodenum",
        "Jejunum va ileum",
        "Sigmoid ichak va rectum",
        "Appendix va cecum",
      ],
      correct: 0,
    },
    {
      q: "Qorin parda parietal va visceral qatlamlar orasidagi bo'shliq qanday nomlanadi?",
      a: [
        "Peritoneal bo'shliq",
        "Mesenterial bo'shliq",
        "Omental recess",
        "Paracolic gutter",
        "Subphrenic space",
      ],
      correct: 0,
    },
    {
      q: "Kichik qopcha (bursa omentalis) qaysi organlar atrofida joylashgan?",
      a: [
        "Jigar, kichik charvi, oshqozon va katta charvi",
        "Jejunum va ileum",
        "Sigmoid ichak va rectum",
        "Duodenum va pankreas",
        "Talaq va oshqozon",
      ],
      correct: 0,
    },
    {
      q: "Kichik qopcha qaysi teshik orqali katta qopcha bilan bog'lanadi?",
      a: [
        "Epiploic foramen",
        "Umbilical foramen",
        "Mesenteric hiatus",
        "Omental recess",
        "Paracolic gutter",
      ],
      correct: 0,
    },
    {
      q: "Katta qopcha qorin bo'shlig'ini qamrab oladi va qaysidan qaysigacha yoyiladi?",
      a: [
        "Diafragmadan chanoq bo'shlig'igacha",
        "Jigar bo'shlig'idan taloqgacha",
        "Oshqozondan sigmoid ichakka",
        "Duodenumdan jejunumgacha",
        "Appendixdan cecumgacha",
      ],
      correct: 0,
    },
    {
      q: "Subfrenik (suprahepatic) cho‘ntak qaysi tuzilmalarning o'rtasida joylashgan?",
      a: [
        "Diafragma va jigar",
        "Oshqozon va taloq",
        "Jejunum va ileum",
        "Sigmoid ichak va rectum",
        "Appendix va cecum",
      ],
      correct: 0,
    },
    {
      q: "Morrison recess (subhepatic recess) qaysi organlar orasida joylashgan?",
      a: [
        "Jigar va buyrak",
        "Oshqozon va taloq",
        "Jejunum va ileum",
        "Sigmoid ichak va rectum",
        "Appendix va cecum",
      ],
      correct: 0,
    },
    {
      q: "Paracolic gutterlar qaysi ichaklar bilan yonma-yon joylashgan?",
      a: [
        "Ko’tariluvchi va tushuvchi chambar ichak",
        "Jejunum va ileum",
        "Oshqozon va duodenum",
        "Sigmoid ichak va rectum",
        "Appendix va cecum",
      ],
      correct: 0,
    },
    {
      q: "Epiploic foramen yuqoridan qaysi organ bilan chegaralangan?",
      a: [
        "Jigar dumsimon qismi",
        "Oshqozon pastki qismi",
        "Jejunum",
        "Sigmoid ichak",
        "Appendix",
      ],
      correct: 0,
    },
    {
      q: "Epiploic foramen pastdan qaysi tuzilma bilan chegaralangan?",
      a: [
        "Duodenum 1-qismi",
        "Oshqozon",
        "Jejunum",
        "Sigmoid ichak",
        "Appendix",
      ],
      correct: 0,
    },
    {
      q: "Epiploic foramen orqa tomondan qaysi tuzilma bilan chegaralangan?",
      a: [
        "Pastki kovak vena",
        "Portal vena",
        "Superior mesenteric arteriya",
        "Inferior mesenteric vena",
        "Chap umbilical vena",
      ],
      correct: 0,
    },
    {
      q: "Parasentez amaliyotida igna qorin bo'shlig'iga qayerdan kiritiladi?",
      a: [
        "Mak-Burney nuqtasidan lateral yoki kindikdan 2 cm pastroq",
        "Oshqozon pastki qismidan",
        "Jejunum orqa qismidan",
        "Sigmoid ichakdan",
        "Talaqdan",
      ],
      correct: 0,
    },
    {
      q: "Katta charvi qaysi boylamni o'z ichiga olmaydi?",
      a: [
        "Gastrolienal",
        "Lienorenal",
        "Gastrofrenik",
        "Gastrokolik",
        "Ligamentum falciforme",
      ],
      correct: 4,
    },
    {
      q: "Kichik charvi o'ng erkin burchagida qaysi tuzilmalarga ega?",
      a: [
        "Jigarning proper hepatic arteriyasi, o’t yo’li va portal vena",
        "Jejunum va ileum",
        "Sigmoid ichak va rectum",
        "Oshqozon va duodenum",
        "Talaq va oshqozon",
      ],
      correct: 0,
    },
    {
      q: "Qorin parda yallig‘lanishi qanday nomlanadi?",
      a: ["Peritonit", "Gastrit", "Hepatit", "Colitis", "Appendisit"],
      correct: 0,
    },
    {
      q: "Peritonitning asosiy belgisi nima?",
      a: [
        "Fibrin va leykotsitlar bilan boy peritoneal suyuqlik to‘planishi",
        "Ichak peristaltikasi oshishi",
        "Jigar shishi",
        "Talaq yallig‘lanishi",
        "Appendix kattalashishi",
      ],
      correct: 0,
    },
    {
      q: "Viseeral peritoneum og‘riqni sezadimi?",
      a: [
        "Ha, doim sezadi",
        "Yo‘q, sezmaydi",
        "Faqat kichik qopchada sezadi",
        "Faqat katta qopchada sezadi",
        "Faqat epiploik foramen atrofida sezadi",
      ],
      correct: 1,
    },
    {
      q: "Parietal peritoneum qaysi nervlar orqali innervatsiya qilinadi?",
      a: [
        "Somatik nervlar: diafragmal, subkostal, iliogipogastrik, ilioinguinal",
        "Viseeral nervlar",
        "Only vagus nervi",
        "Sympathetic plexus",
        "Only mesenteric nerves",
      ],
      correct: 0,
    },
  ],
};
