// qs.js
window.TEST_QUESTIONS = {
  cases: [
    {
      q: "A 22-year-old man presented to his family physician with a laceration of the fibrous sheets or bands that cover his body under the skin and invest the muscles. Which of the following structures would most likely be injured?",
      a: [
        "Tendon",
        "Fascia",
        "Synovial tendon sheath",
        "Aponeurosis",
        "Ligament",
      ],
      correct: 1,
    },
    {
      q: "On the basis of the examination at her doctor’s office, a patient is told that her parasympathetic nerves are damaged. Which of the following muscles would most likely be affected?",
      a: [
        "Muscles in the hair follicles",
        "Muscles in blood vessels",
        "Muscles that act at the elbow joint",
        "Muscles in the gastrointestinal (GI) tract",
        "Muscles enclosed by epimysium",
      ],
      correct: 3,
    },
    {
      q: "A 46-year-old male patient with high blood pressure was examined in the emergency department, and his physician found a leakage of blood from the blood vessel that normally carries richly oxygenated blood. Which of the following vessels would most likely be damaged?",
      a: [
        "Superior vena cava",
        "Pulmonary arteries",
        "Pulmonary veins",
        "Portal vein",
        "Coronary sinus",
      ],
      correct: 2,
    },
    {
      q: "A 16-year-old patient received a stab wound, and axons of the general somatic efferent (GSE) neurons to the shoulder muscles were severed. The damaged axons:",
      a: [
        "Would carry impulses toward the cell bodies",
        "Would carry impulses away from the cell bodies",
        "Would carry pain impulses",
        "Are several in numbers for multipolar neurons",
        "Are found primarily in the gray matter",
      ],
      correct: 1,
    },
    {
      q: "A 16-year-old patient received a laceration of the posterior intercostal nerves by a penetrated knife blade. A pathologist obtained needle biopsy tissues and observed numerous degenerated cell bodies of the unipolar or pseudounipolar neurons. Which of the following structures would most likely provide the abnormal cell morphology?",
      a: [
        "Ventral horn of the spinal cord",
        "Lateral horn of the spinal cord",
        "Dorsal horn of the spinal cord",
        "Dorsal root ganglion",
        "Sympathetic chain ganglion",
      ],
      correct: 3,
    },
    {
      q: "A 19-year-old college student came to his doctor’s office for a neurologic examination. His physician told him that normally synapses are absent in or on which of the following structures?",
      a: [
        "Anterior horn of the spinal cord",
        "Dorsal root ganglia",
        "Sympathetic chain ganglia",
        "Dendrites",
        "Cell bodies",
      ],
      correct: 1,
    },
    {
      q: "A 27-year-old woman involved in a car accident is brought into the emergency department. Her magnetic resonance imaging reveals that she has a laceration of the spinal cord at the L4 spinal cord level. Which of the following structures would you expect to be intact?",
      a: [
        "Dorsal horn",
        "Lateral horn",
        "Ventral horn",
        "Gray matter",
        "White matter",
      ],
      correct: 1,
    },
    {
      q: "A 33-year-old male patient complains of feeling severe pain when he tries to turn his neck. The physician realizes that the problem is in his pivot (trochoid) joint. Which of the following joints would most likely be examined?",
      a: [
        "Atlantooccipital joint",
        "Atlantoaxial joint",
        "Carpometacarpal joint",
        "Proximal tibiofibular joint",
        "Intervertebral disks",
      ],
      correct: 1,
    },
    {
      q: "A patient presents with a loss of sensation to the skin over the shoulder. Injury to which of the following nerve cells would most likely affect the conduction of sensory information to the central nervous system?",
      a: [
        "Multipolar neurons",
        "Bipolar neurons",
        "Unipolar or pseudounipolar neurons",
        "Neurons in the ventral horn",
        "Neurons in sympathetic chain ganglia",
      ],
      correct: 2,
    },
    {
      q: "A 7-year-old girl comes to the emergency department with severe diarrhea. Tests show that the diarrhea is due to decreased capacity of normal absorption in one of her organs. Which of the following organs is involved?",
      a: ["Stomach", "Gallbladder", "Large intestine", "Liver", "Pancreas"],
      correct: 2,
    },
    {
      q: "A 16-year-old girl with urinary diseases comes to a local hospital. Her urologist’s examination and laboratory test results reveal that she has difficulty in removing wastes from the blood and in producing urine. Which of the following organs may have abnormal functions?",
      a: ["Ureter", "Spleen", "Urethra", "Bladder", "Kidney"],
      correct: 4,
    },
    {
      q: "A 53-year-old man with a known history of emphysema is examined in the emergency department. Laboratory findings along with examination indicate that the patient is unable to exchange oxygen in the air and carbon dioxide in the blood. This exchange occurs in which portion of the respiratory system?",
      a: ["Bronchi", "Alveolar (air) sac", "Nasal cavity", "Larynx", "Trachea"],
      correct: 1,
    },
    {
      q: "A 26-year-old woman has an amenorrhea, followed by uterine bleeding, pelvic pain, and pelvic mass. Her obstetrician performed a thorough examination, and the patient was diagnosed as having an ectopic pregnancy. Which of the following organs is most likely to provide a normal site of fertilization?",
      a: [
        "Fundus of the uterus",
        "Ampulla of the uterine tube",
        "Fimbriae",
        "Infundibulum of the uterine tube",
        "Body of the uterus",
      ],
      correct: 1,
    },
    {
      q: "A 29-year-old woman with abdominal pain was admitted to a local hospital, and examination shows that a retroperitoneal infection is affecting a purely endocrine gland. Which of the following structures is infected?",
      a: ["Ovary", "Suprarenal gland", "Pancreas", "Liver", "Stomach"],
      correct: 1,
    },
    {
      q: "A 36-year-old woman received a first-degree burn on her neck, arm, and forearm from a house fire. Which of the following skin structures or functions is most likely damaged or impaired?",
      a: [
        "GSE nerves",
        "Parasympathetic general visceral efferent nerves",
        "Trophic hormone production",
        "Exocrine gland secretion",
        "Vitamin A production",
      ],
      correct: 3,
    },
    {
      q: "A 9-year-old boy is diagnosed with multiple sclerosis (MS). Which of the following nervous structures would most likely be affected by this disease?",
      a: [
        "Trigeminal ganglion",
        "Superior cervical ganglion",
        "Optic nerve",
        "Facial nerve",
        "Spinal accessory nerve",
      ],
      correct: 2,
    },
  ],
  chapter2: [
    {
      q: "During an outbreak of meningitis at a local college, a 20-year-old student presents to a hospital emergency department complaining of headache, fever, chills, and stiff neck. On examination, it appears that he may have meningitis and needs a lumbar puncture or a spinal tap. Cerebrospinal fluid (CSF) is normally withdrawn from which of the following spaces?",
      a: [
        "Epidural space",
        "Subdural space",
        "Space between the spinal cord and the pia mater",
        "Subarachnoid space",
        "Space between the arachnoid and dura maters",
      ],
      correct: 3,
    },
    {
      q: "A 23-year-old jockey falls from her horse and complains of headache, backache, and weakness. Radiologic examination would reveal blood in which of the following spaces if the internal vertebral venous plexus was ruptured?",
      a: [
        "Space deep to the pia mater",
        "Space between the arachnoid and dura maters",
        "Subdural space",
        "Epidural space",
        "Subarachnoid space",
      ],
      correct: 3,
    },
    {
      q: "A 42-year-old woman with metastatic breast cancer is known to have tumors in the intervertebral foramina between the fourth and fifth cervical vertebrae and between the fourth and fifth thoracic vertebrae. Which of the following spinal nerves may be damaged?",
      a: [
        "Fourth cervical and fourth thoracic nerves",
        "Fifth cervical and fifth thoracic nerves",
        "Fourth cervical and fifth thoracic nerves",
        "Fifth cervical and fourth thoracic nerves",
        "Third cervical and fourth thoracic nerves",
      ],
      correct: 3,
    },
    {
      q: "A 39-year-old woman with headaches presents to her primary care physician with a possible herniated disk. Her magnetic resonance imaging (MRI) scan reveals that the posterolateral protrusion of the intervertebral disk between L4 and L5 vertebrae would most likely affect nerve roots of which of the following spinal nerves?",
      a: [
        "Third lumbar nerve",
        "Fourth lumbar nerve",
        "Fifth lumbar nerve",
        "First sacral nerve",
        "Second sacral nerve",
      ],
      correct: 2,
    },
    {
      q: "A 57-year-old woman comes into her physician’s office complaining of fever, nausea, vomiting, and the worst headache of her life. Tests and physical examination suggest hydrocephalus resulting from a decrease in the absorption of cerebrospinal fluid (CSF). A decrease of flow in the CSF through which of the following structures would be responsible for these findings?",
      a: [
        "Choroid plexus",
        "Vertebral venous plexus",
        "Arachnoid villi",
        "Internal jugular vein",
        "Subarachnoid trabeculae",
      ],
      correct: 2,
    },
    {
      q: "After a 26-year-old man’s car was broadsided by a large truck, he is brought to the emergency department with multiple fractures of the transverse processes of the cervical and upper thoracic vertebrae. Which of the following muscles might be affected?",
      a: [
        "Trapezius",
        "Levator scapulae",
        "Rhomboid major",
        "Serratus posterior superior",
        "Rectus capitis posterior major",
      ],
      correct: 1,
    },
    {
      q: "A 27-year-old mountain climber falls from a steep rock wall and is brought to the emergency department. His physical examination and computed tomography (CT) scan reveal dislocation fracture of the upper thoracic vertebrae. The fractured body of the T4 vertebra articulates with which of the following parts of the ribs?",
      a: [
        "Head of the third rib",
        "Neck of the fourth rib",
        "Tubercle of the fourth rib",
        "Head of the fifth rib",
        "Tubercle of the fifth rib",
      ],
      correct: 3,
    },
    {
      q: "A young toddler presents to her pediatrician with rather new onset of bowel and bladder dysfunction and loss of the lower limb function. Her mother had not taken enough folic acid during her pregnancy. On examination, the child has protrusion of the spinal cord and meninges and is diagnosed with which of the following conditions?",
      a: [
        "Spina bifida occulta",
        "Meningocele",
        "Meningomyelocele",
        "Myeloschisis",
        "Syringomyelocele",
      ],
      correct: 2,
    },
    {
      q: "A 34-year-old woman crashes into a tree during a skiing lesson and is brought to a hospital with multiple injuries that impinge the dorsal primary rami of several spinal nerves. Such lesions could affect which of the following muscles?",
      a: [
        "Rhomboid major",
        "Levator scapulae",
        "Serratus posterior superior",
        "Iliocostalis",
        "Latissimus dorsi",
      ],
      correct: 3,
    },
    {
      q: "During a domestic dispute, a 16-year-old boy receives a deep stab wound around the superior angle of the scapula near the medial border, which injures both the dorsal scapular and spinal accessory nerves. Such an injury could result in paralysis or weakness of which of the following muscles?",
      a: [
        "Trapezius and serratus posterior superior",
        "Rhomboid major and trapezius",
        "Rhomboid minor and latissimus dorsi",
        "Splenius cervicis and sternocleidomastoid",
        "Levator scapulae and erector spinae",
      ],
      correct: 1,
    },
    {
      q: "An elderly man at a nursing home is known to have degenerative brain disease. When cerebrospinal fluid (CSF) is withdrawn by lumbar puncture for further examination, which of the following structures is most likely penetrated by the needle?",
      a: [
        "Pia mater",
        "Filum terminale externum",
        "Posterior longitudinal ligament",
        "Ligamentum flavum",
        "Annulus fibrosus",
      ],
      correct: 3,
    },
    {
      q: "A 27-year-old stuntman is thrown out of his vehicle prematurely when the car used for a particular scene speeds out of control. His spinal cord is crushed at the level of the fourth lumbar spinal segment. Which of the following structures would most likely be spared from destruction?",
      a: [
        "Dorsal horn",
        "Ventral horn",
        "Lateral horn",
        "Gray matter",
        "Pia mater",
      ],
      correct: 2,
    },
    {
      q: "A 24-year-old woman comes to a hospital to deliver her baby. Her obstetrician uses a caudal anesthesia during labor and childbirth to block the spinal nerves in the epidural space. Local anesthetic agents are most likely injected via which of the following openings?",
      a: [
        "Intervertebral foramen",
        "Sacral hiatus",
        "Vertebral canal",
        "Dorsal sacral foramen",
        "Ventral sacral foramen",
      ],
      correct: 1,
    },
    {
      q: "In a freak hunting accident, a 17-year-old boy was shot with an arrow that penetrated into his suboccipital triangle, injuring the suboccipital nerve between the vertebral artery and the posterior arch of the atlas. Which of the following muscles would be unaffected by such a lesion?",
      a: [
        "Rectus capitis posterior major",
        "Semispinalis capitis",
        "Splenius capitis",
        "Obliquus capitis superior",
        "Obliquus capitis inferior",
      ],
      correct: 2,
    },
    {
      q: "A 26-year-old heavyweight boxer was punched on his mandible, resulting in a slight subluxation (dislocation) of the atlantoaxial joint. The consequence of the injury was decreased range of motion at that joint. What movement would be most affected?",
      a: ["Extension", "Flexion", "Abduction", "Adduction", "Rotation"],
      correct: 4,
    },
    {
      q: "A crush injury of the vertebral column can cause the spinal cord to swell. Which structure would be trapped between the dura and the vertebral body by the swelling spinal cord?",
      a: [
        "Anterior longitudinal ligament",
        "Alar ligament",
        "Posterior longitudinal ligament",
        "Cruciform ligament",
        "Ligamentum nuchae",
      ],
      correct: 2,
    },
    {
      q: "A 44-year-old woman comes to her physician and complains of headache and backache. On examination, she is found to have fluid accumulated in the spinal epidural space because of damage to blood vessels or meninges. Which of the following structures is most likely ruptured?",
      a: [
        "Vertebral artery",
        "Vertebral vein",
        "External vertebral venous plexus",
        "Internal vertebral venous plexus",
        "Lumbar cistern",
      ],
      correct: 3,
    },
    {
      q: "A 69-year-old man has an abnormally increased curvature of the thoracic vertebral column. Which of the following conditions is the most likely diagnosis?",
      a: [
        "Lordosis",
        "Spina bifida occulta",
        "Meningocele",
        "Meningomyelocele",
        "Kyphosis",
      ],
      correct: 4,
    },
    {
      q: "During a snowstorm, a 52-year-old man is brought to the emergency department after a multiple car accident. Which of the following conditions is produced by a force that drives the trunk forward while the head lags behind in a rear-end automobile collision?",
      a: [
        "Scoliosis",
        "Hangman fracture",
        "Meningomyelocele",
        "Whiplash injury",
        "Herniated disk",
      ],
      correct: 3,
    },
    {
      q: "A 37-year-old man is brought to the emergency department with a crushed second cervical vertebra (axis) that he suffered after a stack of pallets fell on him at work. Which of the following structures would be intact after the accident?",
      a: [
        "Alar ligament",
        "Apical ligament",
        "Semispinalis cervicis muscle",
        "Rectus capitis posterior minor",
        "Obliquus capitis inferior",
      ],
      correct: 3,
    },
    {
      q: "A middle-aged coal miner injures his back after an accidental explosion. His magnetic resonance imaging (MRI) scan reveals that his spinal cord has shifted to the right because the lateral extensions of the pia mater were torn. Function of which of the following structures is most likely impaired?",
      a: [
        "Filum terminale internum",
        "Coccygeal ligament",
        "Denticulate ligament",
        "Choroid plexus",
        "Tectorial membrane",
      ],
      correct: 2,
    },
    {
      q: "A 25-year-old man with congenital abnormalities at birth has a lesion of the dorsal scapular nerve, making him unable to adduct his scapula. Which of the following muscles is most likely paralyzed?",
      a: [
        "Semispinalis capitis",
        "Rhomboid major",
        "Multifidus",
        "Rotator longus",
        "Iliocostalis",
      ],
      correct: 1,
    },
    {
      q: "After an automobile accident, a back muscle that forms the boundaries of the triangle of auscultation and the lumbar triangle receives no blood. Which of the following muscles might be ischemic?",
      a: [
        "Levator scapulae",
        "Rhomboid minor",
        "Latissimus dorsi",
        "Trapezius",
        "Splenius capitis",
      ],
      correct: 2,
    },
    {
      q: "A 38-year-old woman with a long history of shoulder pain is admitted to a hospital for surgery. Which of the following muscles becomes ischemic soon after ligation of the superficial or ascending branch of the transverse cervical artery?",
      a: [
        "Latissimus dorsi",
        "Multifidus",
        "Trapezius",
        "Rhomboid major",
        "Longissimus capitis",
      ],
      correct: 2,
    },
    {
      q: "A 25-year-old soldier suffers a gunshot wound on the lower part of his back and is unable to move his legs. A neurologic examination and magnetic resonance imaging (MRI) scan reveal injury of the cauda equina. Which of the following is most likely damaged?",
      a: [
        "Dorsal primary rami",
        "Ventral primary rami",
        "Dorsal roots of the thoracic spinal nerves",
        "Ventral roots of the sacral spinal nerves",
        "Lumbar spinal nerves",
      ],
      correct: 3,
    },
  ],
  chapter3: [
    {
      q: "A 32-year-old patient who weighs 275 lb comes to the doctor’s office. On the surface of the chest, the physician is able to locate the apex of the heart:",
      a: [
        "At the level of the sternal angle",
        "In the left fourth intercostal space",
        "In the left fifth intercostal space",
        "In the right fifth intercostal space",
        "At the level of the xiphoid process of the sternum",
      ],
      correct: 2,
    },
    {
      q: "A 43-year-old female patient has been lying down on the hospital bed for more than 4 months. Her normal, quiet expiration is achieved by contraction of which of the following structures?",
      a: [
        "Elastic tissue in the lungs and thoracic wall",
        "Serratus posterior superior muscles",
        "Pectoralis minor muscles",
        "Serratus anterior muscles",
        "Diaphragm",
      ],
      correct: 0,
    },
    {
      q: "A 23-year-old man received a gunshot wound, and his greater splanchnic nerve was destroyed. Which of the following nerve fibers would be injured?",
      a: [
        "General somatic afferent (GSA) and preganglionic sympathetic fibers",
        "General visceral afferent (GVA) and postganglionic sympathetic fibers",
        "GVA and preganglionic sympathetic fibers",
        "General somatic efferent (GSE) and postganglionic sympathetic fibers",
        "GVA and GSE fibers",
      ],
      correct: 2,
    },
    {
      q: "A 17-year-old boy was involved in a gang fight, and a stab wound severed the white rami communicantes at the level of his sixth thoracic vertebra. This injury would result in degeneration of nerve cell bodies in which of the following structures?",
      a: [
        "Dorsal root ganglion and anterior horn of the spinal cord",
        "Sympathetic chain ganglion and dorsal root ganglion",
        "Sympathetic chain ganglion and posterior horn of the spinal cord",
        "Dorsal root ganglion and lateral horn of the spinal cord",
        "Anterior and lateral horns of the spinal cord",
      ],
      correct: 3,
    },
    {
      q: "A 27-year-old cardiac patient with an irregular heartbeat visits her doctor’s office for examination. Where should the physician place the stethoscope to listen to the sound of the mitral valve?",
      a: [
        "Over the medial end of the second left intercostal space",
        "Over the medial end of the second right intercostal space",
        "In the left fourth intercostal space at the midclavicular line",
        "In the left fifth intercostal space at the midclavicular line",
        "Over the right half of the lower end of the body of the sternum",
      ],
      correct: 3,
    },
    {
      q: "A 19-year-old man came to the emergency department, and his angiogram exhibited that he was bleeding from the vein that is accompanied by the posterior interventricular artery. Which of the following veins is most likely to be ruptured?",
      a: [
        "Great cardiac vein",
        "Middle cardiac vein",
        "Anterior cardiac vein",
        "Small cardiac vein",
        "Oblique veins of the left atrium",
      ],
      correct: 1,
    },
    {
      q: "A 37-year-old patient with palpitation was examined by her physician, and one of the diagnostic records included a posterior–anterior chest radiograph. Which of the following comprises the largest portion of the sternocostal surface of the heart seen on the radiograph?",
      a: [
        "Left atrium",
        "Right atrium",
        "Left ventricle",
        "Right ventricle",
        "Base of the heart",
      ],
      correct: 3,
    },
    {
      q: "A 5-year-old girl is brought to the emergency department because of difficulty breathing (dyspnea), palpitations, and shortness of breath. Doppler study of the heart reveals an atrial septal defect (ASD). This malformation usually results from incomplete closure of which of the following embryonic structures?",
      a: [
        "Ductus arteriosus",
        "Ductus venosus",
        "Sinus venarum",
        "Foramen ovale",
        "Truncus arteriosus",
      ],
      correct: 3,
    },
    {
      q: "A 54-year-old patient is implanted with an artificial cardiac pacemaker. Which of the following conductive tissues of the heart had a defective function that required the pacemaker?",
      a: [
        "Atrioventricular (AV) bundle",
        "AV node",
        "Sinoatrial (SA) node",
        "Purkinje fiber",
        "Moderator band",
      ],
      correct: 2,
    },
    {
      q: "A thoracic surgeon removed the right middle lobar (secondary) bronchus along with lung tissue from a 57-year-old heavy smoker with lung cancer. Which of the following bronchopulmonary segments must contain cancerous tissues?",
      a: [
        "Medial and lateral",
        "Anterior and posterior",
        "Anterior basal and medial basal",
        "Anterior basal and posterior basal",
        "Lateral basal and posterior basal",
      ],
      correct: 0,
    },
    {
      q: "The bronchogram of a 45-year-old female smoker shows the presence of a tumor in the eparterial bronchus. Which airway is most likely blocked?",
      a: [
        "Left superior bronchus",
        "Left inferior bronchus",
        "Right superior bronchus",
        "Right middle bronchus",
        "Right inferior bronchus",
      ],
      correct: 2,
    },
    {
      q: "An 83-year-old man with a typical coronary circulation has been suffering from an embolism of the circumflex branch of the left coronary artery. This condition would result in ischemia of which of the following areas of the heart?",
      a: [
        "Anterior part of the left ventricle",
        "Anterior interventricular region",
        "Posterior interventricular region",
        "Posterior part of the left ventricle",
        "Anterior part of the right ventricle",
      ],
      correct: 3,
    },
    {
      q: "A 44-year-old man with a stab wound was brought to the emergency department, and a physician found that the patient was suffering from a laceration of his right phrenic nerve. Which of the following conditions has likely occurred?",
      a: [
        "Injury to only GSE fibers",
        "Difficulty in expiration",
        "Loss of sensation in the fibrous pericardium and mediastinal pleura",
        "Normal function of the diaphragm",
        "Loss of sensation in the costal part of the diaphragm",
      ],
      correct: 2,
    },
    {
      q: "An 8-year-old boy with ASD presents to a pediatrician. This congenital heart defect shunts blood from the left atrium to the right atrium and causes hypertrophy of the right atrium, right ventricle, and pulmonary trunk. Which of the following veins opens into the hypertrophied atrium?",
      a: [
        "Middle cardiac vein",
        "Small cardiac vein",
        "Oblique cardiac vein",
        "Anterior cardiac vein",
        "Right pulmonary vein",
      ],
      correct: 3,
    },
    {
      q: "A 37-year-old patient with severe chest pain, shortness of breath, and congestive heart failure was admitted to a local hospital. His coronary angiograms reveal a thrombosis in the circumflex branch of the left coronary artery. Which of the following conditions could result from the blockage of blood flow in the circumflex branch?",
      a: [
        "Tricuspid valve insufficiency",
        "Mitral valve insufficiency",
        "Ischemia of AV node",
        "Paralysis of pectinate muscle",
        "Necrosis of septomarginal trabecula",
      ],
      correct: 1,
    },
    {
      q: "A 75-year-old patient has been suffering from lung cancer located near the cardiac notch, a deep indentation on the lung. Which of the following lobes is most likely to be excised?",
      a: [
        "Superior lobe of the right lung",
        "Middle lobe of the right lung",
        "Inferior lobe of the right lung",
        "Superior lobe of the left lung",
        "Inferior lobe of the left lung",
      ],
      correct: 3,
    },
    {
      q: "A thoracentesis is performed to aspirate an abnormal accumulation of fluid in a 37-year-old patient with pleural effusion. A needle should be inserted at the midaxillary line between which of the following two ribs so as to avoid puncturing the lung?",
      a: [
        "Ribs 1 and 3",
        "Ribs 3 and 5",
        "Ribs 5 and 7",
        "Ribs 7 and 9",
        "Ribs 9 and 11",
      ],
      correct: 3,
    },
    {
      q: "A newborn baby is readmitted to the hospital with hypoxia and upon testing is found to have pulmonary stenosis, dextraposition of the aorta, interventricular septal defect, and hypertrophy of the right ventricle. Which of the following is best described by these symptoms?",
      a: [
        "ASD",
        "Patent ductus arteriosus",
        "Tetralogy of Fallot",
        "Aortic stenosis",
        "Coarctation of the aorta",
      ],
      correct: 2,
    },
    {
      q: "A 33-year-old patient is suffering from a sudden occlusion at the origin of the descending (thoracic) aorta. This condition would most likely decrease blood flow in which of the following intercostal arteries?",
      a: [
        "Upper six anterior",
        "All of the posterior",
        "Upper two posterior",
        "Lower anterior",
        "Lower six posterior",
      ],
      correct: 4,
    },
    {
      q: "A 56-year-old patient recently suffered a myocardial infarction in the area of the apex of the heart. The occlusion by atherosclerosis is in which of the following arteries?",
      a: [
        "Marginal artery",
        "Right coronary artery at its origin",
        "Anterior interventricular artery",
        "Posterior interventricular artery",
        "Circumflex branch of the left coronary artery",
      ],
      correct: 2,
    },
    {
      q: "A 75-year-old woman was admitted to a local hospital, and bronchograms and radiographs revealed a lung carcinoma in her left lung. Which of the following structures or characteristics does the cancerous lung contain?",
      a: [
        "Horizontal fissure",
        "Groove for superior vena cava (SVC)",
        "Middle lobe",
        "Lingula",
        "Larger capacity than the right",
      ],
      correct: 3,
    },
    {
      q: "An 18-year-old girl is thrust into the steering wheel while driving and experiences difficulty in expiration. Which of the following muscles is most likely damaged?",
      a: [
        "Levator costarum",
        "Innermost intercostal muscle",
        "External intercostal muscle",
        "Diaphragm",
        "Muscles of the abdominal wall",
      ],
      correct: 4,
    },
    {
      q: "A 78-year-old patient presents with an advanced cancer in the posterior mediastinum. The surgeons are in a dilemma as to how to manage the condition. Which of the following structures is most likely damaged?",
      a: [
        "Brachiocephalic veins",
        "Trachea",
        "Arch of the azygos vein",
        "Arch of the aorta",
        "Hemiazygos vein",
      ],
      correct: 4,
    },
    {
      q: "A 46-year-old patient comes to his doctor’s office and complains of chest pain and headache. His computed tomography (CT) scan reveals a tumor located just superior to the root of the right lung. Blood flow in which of the following veins is most likely blocked by this tumor?",
      a: [
        "Hemiazygos vein",
        "Arch of the azygos vein",
        "Right subclavian vein",
        "Right brachiocephalic vein",
        "Accessory hemiazygos vein",
      ],
      correct: 3,
    },
    {
      q: "A 21-year-old patient with a stab wound reveals a laceration of the right vagus nerve proximal to the origin of the recurrent laryngeal nerve. Which of the following conditions would most likely result from this lesion?",
      a: [
        "Contraction of bronchial muscle",
        "Stimulation of bronchial gland secretion",
        "Dilation of the bronchial lumen",
        "Decrease in cardiac rate",
        "Constriction of coronary artery",
      ],
      correct: 2,
    },
    {
      q: "A neonate appears severely cyanotic and breathing rapidly. Cardiac echocardiogram reveals that the aorta lies to the right of the pulmonary trunk. Which of the following is most likely occurred during development?",
      a: [
        "AP septum failed to develop in a spiral fashion",
        "Excessive resorption of septum primum",
        "Pulmonary valve atresia",
        "Persistent truncus arteriosus",
        "Coarctation of the aorta",
      ],
      correct: 0,
    },
    {
      q: "A 12-year-old boy was admitted to a local hospital with a known history of heart problems. His left ventricular hypertrophy could result from which of the following conditions?",
      a: [
        "A constricted pulmonary trunk",
        "An abnormally small left AV opening",
        "Improper closing of the pulmonary valves",
        "An abnormally large right AV opening",
        "Stenosis of the aorta",
      ],
      correct: 4,
    },
    {
      q: "A 31-year-old man was involved in a severe automobile accident and suffered laceration of the left primary bronchus. The damaged primary bronchus:",
      a: [
        "Has a larger diameter than the right primary bronchus",
        "Often receives more foreign bodies than the right primary bronchus",
        "Gives rise to the eparterial bronchus",
        "Is longer than the right primary bronchus",
        "Runs under the arch of the azygos vein",
      ],
      correct: 3,
    },
    {
      q: "A 62-year-old woman who is a heavy smoker has an advanced lung cancer that spread into her right third posterior intercostal space posterior to the midaxillary line. If cancer cells are carried in the venous drainage, they would travel first to which of the following veins?",
      a: [
        "SVC",
        "Right superior intercostal vein",
        "Right brachiocephalic vein",
        "Azygos vein",
        "Hemiazygos vein",
      ],
      correct: 1,
    },
    {
      q: "A radiologist examines posterior–anterior chest radiographs of a 27-year-old victim of a car accident. Which of the following structures forms the right border of the cardiovascular silhouette?",
      a: [
        "Arch of the aorta",
        "Pulmonary trunk",
        "SVC",
        "Ascending aorta",
        "Left ventricle",
      ],
      correct: 2,
    },
    {
      q: "A 37-year-old man is brought to the emergency department complaining of severe chest pain. His angiogram reveals thromboses of both brachiocephalic veins just before entering the superior vena cava. This condition would most likely cause a dilation of which of the following veins?",
      a: [
        "Azygos",
        "Hemiazygos",
        "Right superior intercostal",
        "Left superior intercostal",
        "Internal thoracic",
      ],
      correct: 3,
    },
    {
      q: "A cardiologist is on clinical rounds with her medical students. She asks them, “During the cardiac cycle, which of the following events occurs?”",
      a: [
        "AV valves close during diastole",
        "Aortic valve closes during systole",
        "Pulmonary valve opens during diastole",
        "Blood flow in coronary arteries is maximal during diastole",
        "Aortic valve closes at the same time as AV valve",
      ],
      correct: 3,
    },
    {
      q: "Coronary angiographs of a 44-year-old male patient reveal an occlusion of the circumflex branch of the left coronary artery. This patient has been suffering from myocardial infarction in which of the following areas?",
      a: [
        "Right and left ventricles",
        "Right and left atria",
        "Interventricular septum",
        "Apex of the heart",
        "Left atrium and ventricle",
      ],
      correct: 4,
    },
    {
      q: "A patient has a small but solid tumor in the mediastinum, which is confined at the level of the sternal angle. Which of the following structures would most likely be found at this level?",
      a: [
        "Bifurcation of the trachea",
        "Beginning of the ascending aorta",
        "Middle of the aortic arch",
        "Articulation of the third rib with the sternum",
        "Superior border of the superior mediastinum",
      ],
      correct: 0,
    },
    {
      q: "A 37-year-old house painter fell from a ladder and fractured his left third rib and the structures with which it articulated. Which of the following structures would most likely be damaged?",
      a: [
        "Manubrium of the sternum",
        "Body of the second thoracic vertebra",
        "Spinous process of the third thoracic vertebra",
        "Body of the fourth thoracic vertebra",
        "Transverse process of the second thoracic vertebra",
      ],
      correct: 1,
    },
    {
      q: "A 45-year-old woman presents with a tumor confined to the posterior mediastinum. This could result in compression of which of the following structures?",
      a: [
        "Trachea",
        "Descending aorta",
        "Arch of the aorta",
        "Arch of the azygos vein",
        "Phrenic nerve",
      ],
      correct: 1,
    },
    {
      q: "A 62-year-old patient with pericardial effusion comes to a local hospital for aspiration of pericardial fluid by pericardiocentesis. The needle is inserted into the pericardial cavity through which of the following intercostal spaces adjacent to the sternum?",
      a: [
        "Right fourth intercostal space",
        "Left fourth intercostal space",
        "Right fifth intercostal space",
        "Left fifth intercostal space",
        "Right sixth intercostal space",
      ],
      correct: 3,
    },
    {
      q: "The attending faculty in the coronary intensive care unit demonstrates to his students a normal heart examination. The first heart sound is produced by near-simultaneous closure of which of the following valves?",
      a: [
        "Aortic and tricuspid",
        "Aortic and pulmonary",
        "Tricuspid and mitral",
        "Mitral and pulmonary",
        "Tricuspid and pulmonary",
      ],
      correct: 2,
    },
    {
      q: "A 27-year-old patient with Marfan syndrome has an aneurysm of the aortic arch. This may compress which of the following structures?",
      a: [
        "Right vagus nerve",
        "Left phrenic nerve",
        "Right sympathetic trunk",
        "Left recurrent laryngeal nerve",
        "Left greater splanchnic nerve",
      ],
      correct: 3,
    },
    {
      q: "A 47-year-old man with a known atrial fibrillation returns to see his cardiologist for follow-up of his cardiac health. The right atrium is important in this case because it:",
      a: [
        "Receives blood from the oblique cardiac vein",
        "Is associated with the apex of the heart",
        "Contains the SA node",
        "Receives the right pulmonary vein",
        "Is hypertrophied by pulmonary stenosis",
      ],
      correct: 2,
    },
    {
      q: "A 57-year-old patient has a heart murmur resulting from the inability to maintain constant tension on the cusps of the AV valve. Which of the following structures is most likely damaged?",
      a: [
        "Crista terminalis",
        "Septomarginal trabecula",
        "Chordae tendineae",
        "Pectinate muscle",
        "Anulus fibrosus",
      ],
      correct: 2,
    },
    {
      q: "A mother with diabetes gives birth to a baby who is diagnosed as having dextroposition of the aorta and the pulmonary trunk with cyanosis and shortness of breath. Which of the following structures is required to remain patent until surgical correction of the deformity?",
      a: [
        "Umbilical arteries",
        "Umbilical vein",
        "Ductus arteriosus",
        "Ductus venosus",
        "Sinus venosus",
      ],
      correct: 2,
    },
    {
      q: "During early development of the respiratory system, the laryngotracheal tube maintains communication with the primitive foregut. Which of the following embryonic structures is most likely responsible for partitioning these two embryonic structures?",
      a: [
        "Tracheoesophageal folds",
        "Tracheoesophageal fistula",
        "Tracheoesophageal septum",
        "Laryngotracheal diverticulum",
        "Laryngotracheal septum",
      ],
      correct: 2,
    },
    {
      q: "A 32-year-old patient has a tension pneumothorax that can be treated with needle aspiration. To avoid an injury of the intercostal neurovascular bundle, the needle may be inserted in which of the following locations?",
      a: [
        "Above the upper border of the ribs",
        "Deep to the upper border of the ribs",
        "Beneath the lower border of the ribs",
        "Between the external and internal intercostals",
        "Through the transversus thoracis muscle",
      ],
      correct: 0,
    },
    {
      q: "A 9-month-old girl was admitted to the children’s hospital with tachypnea (fast breathing) and shortness of breath. Physical examination further exhibits tachycardia (fast heart rate), a bounding peripheral pulse, and her angiographs reveal a patent ductus arteriosus. Which of the following embryonic arterial structures is most likely responsible for the origin of the patent ductus arteriosus?",
      a: [
        "Right fourth arch",
        "Left fifth arch",
        "Right fifth arch",
        "Left sixth arch",
        "Right sixth arch",
      ],
      correct: 3,
    },
    {
      q: "A 7-day-old baby is diagnosed as having congenital neonatal emphysema, which is caused by collapsed bronchi because of failure of bronchial cartilage development. Bronchial cartilages are derived from which of the following derivations?",
      a: ["Ectoderm", "Mesoderm", "Endoderm", "Proctodeum", "Neuroectoderm"],
      correct: 1,
    },
  ],
  chapter4: [
    {
      q: "A 63-year-old man comes to the emergency department with back pain, weakness, and shortness of breath. On examination, he has an aneurysm of the abdominal aorta at the aortic hiatus of the diaphragm. Which of the following pairs of structures would most likely be compressed?",
      a: [
        "Vagus nerve and azygos vein",
        "Esophagus and vagus nerve",
        "Azygos vein and thoracic duct",
        "Thoracic duct and vagus nerve",
        "Inferior vena cava (IVC) and phrenic nerve",
      ],
      correct: 2,
    },
    {
      q: "A 36-year-old woman with yellow pigmentation of the skin and sclerae presents at the outpatient clinic. Which of the following conditions most likely is the cause of her obstructive jaundice?",
      a: [
        "Aneurysm of the splenic artery",
        "Perforated ulcer of the stomach",
        "Obstruction of the main pancreatic duct",
        "Cancer in the head of the pancreas",
        "Cancer in the body of the pancreas",
      ],
      correct: 3,
    },
    {
      q: "A 2-year-old boy presents with pain in his groin that has been increasing in nature over the past few weeks. He is found to have a degenerative malformation of the transversalis fascia during development. Which of the following structures on the anterior abdominal wall is likely defective?",
      a: [
        "Superficial inguinal ring",
        "Deep inguinal ring",
        "Inguinal ligament",
        "Sac of a direct inguinal hernia",
        "Anterior wall of the inguinal canal",
      ],
      correct: 1,
    },
    {
      q: "A 29-year-old man comes to a local hospital with duodenal peptic ulcer and complains of cramping epigastric pain. Which of the following structures harbors the cell bodies of abdominal pain fibers?",
      a: [
        "Lateral horn of the spinal cord",
        "Anterior horn of the spinal cord",
        "Dorsal root ganglion",
        "Sympathetic chain ganglion",
        "Celiac ganglion",
      ],
      correct: 2,
    },
    {
      q: "A 42-year-old obese woman with seven children is brought to a local hospital by her daughter. Physical examination and her radiograph reveal that large gallstones have ulcerated through the posterior wall of the fundus of the gallbladder into the intestine. Which of the following parts of the intestine is most likely to initially contain gallstones?",
      a: [
        "Cecum",
        "Ascending colon",
        "Transverse colon",
        "Descending colon",
        "Sigmoid colon",
      ],
      correct: 2,
    },
    {
      q: "A 35-year-old woman comes to a local hospital with abdominal tenderness and acute pain. On examination, her physician observes that an abdominal infection has spread retroperitoneally. Which of the following structures is most likely affected?",
      a: [
        "Stomach",
        "Transverse colon",
        "Jejunum",
        "Descending colon",
        "Spleen",
      ],
      correct: 3,
    },
    {
      q: "During an annual health examination of a 46-year-old woman, a physician finds hypersecretion of norepinephrine from her suprarenal medulla. Which of the following types of nerve fibers are most likely overstimulated?",
      a: [
        "Preganglionic sympathetic fibers",
        "Postganglionic sympathetic fibers",
        "Somatic motor fibers",
        "Postganglionic parasympathetic fibers",
        "Preganglionic parasympathetic fibers",
      ],
      correct: 0,
    },
    {
      q: "A 6-year-old girl comes to her pediatrician with constipation, abdominal distention, and vomiting. After thorough examination, she is diagnosed as having Hirschsprung disease (aganglionic megacolon), which is a congenital disease and leads to dilation of the colon. This condition is caused by an absence of which of the following kinds of neural cell bodies?",
      a: [
        "Sympathetic preganglionic neuron cell bodies",
        "Sympathetic postganglionic neuron cell bodies",
        "Parasympathetic preganglionic neuron cell bodies",
        "Parasympathetic postganglionic neuron cell bodies",
        "Sensory neuron cell bodies",
      ],
      correct: 3,
    },
    {
      q: "A pediatric surgeon is resecting a possible malignant mass from the liver of a neonate with cerebral palsy. The surgeon divides the round ligament of the liver during surgery. A fibrous remnant of which of the following fetal vessels is severed?",
      a: [
        "Ductus venosus",
        "Ductus arteriosus",
        "Left umbilical vein",
        "Right umbilical vein",
        "Umbilical artery",
      ],
      correct: 2,
    },
    {
      q: "A 27-year-old woman has suffered a gunshot wound to her midabdomen. After examining the patient’s angiogram, a trauma surgeon locates the source of bleeding from pairs of veins that typically terminate in the same vein. Which of the following veins are damaged?",
      a: [
        "Left and right ovarian veins",
        "Left and right gastroepiploic veins",
        "Left and right colic veins",
        "Left and right suprarenal veins",
        "Left and right hepatic veins",
      ],
      correct: 4,
    },
    {
      q: "A 43-year-old man complains of abdominal pain just above his umbilicus. On examination, a tumor is found anterior to the IVC. Which of the following structures would most likely be compressed by this tumor?",
      a: [
        "Right sympathetic trunk",
        "Left third lumbar artery",
        "Third part of the duodenum",
        "Left renal artery",
        "Cisterna chyli",
      ],
      correct: 2,
    },
    {
      q: "A 33-year-old man with a perforated gastric ulcer complains of excruciating pain in his stomach. It is observed that the pain comes from peritoneal irritation by gastric contents in the lesser sac. Which of the following nerves contain sensory nerve fibers that convey this sharp, stabbing pain?",
      a: [
        "Vagus nerves",
        "Greater splanchnic nerves",
        "Lower intercostal nerves",
        "White rami communicantes",
        "Gray rami communicantes",
      ],
      correct: 2,
    },
    {
      q: "A young boy is brought to the hospital after a bicycle accident and possible pelvic fracture. While awaiting a computed tomography (CT) scan of his pelvis, a physician proceeds with a focal neurologic examination. In testing the child’s reflexes, which of the following nerves would carry afferent impulses of the cremasteric reflex?",
      a: [
        "Subcostal nerve",
        "Lateral femoral cutaneous nerve",
        "Genitofemoral nerve",
        "Iliohypogastric nerve",
        "Femoral nerve",
      ],
      correct: 2,
    },
    {
      q: "A 21-year-old man receives a penetrating knife wound in the abdomen and is injured in both the superior mesenteric artery and the vagus nerve. Which portion of the colon would most likely be impaired by this injury?",
      a: [
        "Ascending and descending colons",
        "Transverse and sigmoid colons",
        "Descending and sigmoid colons",
        "Ascending and transverse colons",
        "Transverse and descending colons",
      ],
      correct: 3,
    },
    {
      q: "A 42-year-old man with portal hypertension secondary to cirrhosis of the liver and subsequent massive ascites presents to the emergency department. He refuses to have a transjugular intrahepatic portosystemic shunt (TIPS) procedure and prefers surgery. Which of the following surgical connections is involved in the most practical method of shunting portal blood around the liver?",
      a: [
        "Superior mesenteric vein to the inferior mesenteric vein",
        "Portal vein to the superior vena cava",
        "Portal vein to the left renal vein",
        "Splenic vein to the left renal vein",
        "Superior rectal vein to the left colic vein",
      ],
      correct: 3,
    },
    {
      q: "A 78-year-old man is suffering from ischemia of the suprarenal glands. This condition results from rapid occlusion of direct branches of which of the following arteries?",
      a: [
        "Aorta, splenic, and inferior phrenic arteries",
        "Renal, splenic, and inferior mesenteric arteries",
        "Aorta, inferior phrenic, and renal arteries",
        "Superior mesenteric, inferior mesenteric, and renal arteries",
        "Aorta and hepatic and renal arteries",
      ],
      correct: 2,
    },
    {
      q: "A radiograph of a 32-year-old woman reveals a perforation in the posterior wall of the stomach in which the gastric contents have spilled into the lesser sac. The general surgeon has opened the lienogastric (gastrosplenic) ligament to reach the lesser sac and notes erosion of the ulcer into an artery. Which of the following vessels is most likely involved?",
      a: [
        "Splenic artery",
        "Gastroduodenal artery",
        "Left gastric artery",
        "Right gastric artery",
        "Left gastroepiploic artery",
      ],
      correct: 0,
    },
    {
      q: "A 35-year-old woman with a history of cholecystectomy arrives in the emergency department with intractable hiccups most likely caused by an abdominal abscess secondary to surgical infection. Which of the following nerves carries pain sensation caused by irritation of the peritoneum on the central portion of the inferior surface of the diaphragm?",
      a: [
        "Vagus nerve",
        "Lower intercostal nerve",
        "Phrenic nerve",
        "Greater splanchnic nerve",
        "Subcostal nerve",
      ],
      correct: 2,
    },
    {
      q: "A 16-year-old boy with a ruptured spleen comes to the emergency department for splenectomy. Soon after ligation of the splenic artery just distal to its origin, a surgical resident observes that the patient is healing normally. Normal blood flow would occur in which of the following arteries?",
      a: [
        "Short gastric arteries",
        "Dorsal pancreatic artery",
        "Inferior pancreaticoduodenal artery",
        "Left gastroepiploic artery",
        "Artery in the lienorenal ligament",
      ],
      correct: 0,
    },
    {
      q: "A 9-year-old boy was admitted to the emergency department complaining of nausea, vomiting, fever, and loss of appetite. On examination, he was found to have tenderness and pain on the right lower quadrant. Based on signs and symptoms, the diagnosis of acute appendicitis was made. During an appendectomy performed at McBurney point, which of the following structures is most likely to be injured?",
      a: [
        "Deep circumflex femoral artery",
        "Inferior epigastric artery",
        "Iliohypogastric nerve",
        "Genitofemoral nerve",
        "Spermatic cord",
      ],
      correct: 2,
    },
    {
      q: "A 54-year-old man with a long history of alcohol abuse presents to the emergency department with rapidly increasing abdominal distention most likely resulting from an alteration in portal systemic blood flow. Which of the following characteristics is associated with the portal vein or the portal venous system?",
      a: [
        "Lower blood pressure than in the IVC",
        "Least risk of venous varices because of portal hypertension",
        "Distention of the portal vein resulting from its numerous valves",
        "Caput medusae and hemorrhoids caused by portal hypertension",
        "Less blood flow than in the hepatic artery",
      ],
      correct: 3,
    },
    {
      q: "While examining radiographs and angiograms of a 52-year-old patient, a physician is trying to distinguish the jejunum from the ileum. He has observed that the jejunum has:",
      a: [
        "Fewer plicae circulares",
        "Fewer mesenteric arterial arcades",
        "Less digestion and absorption of nutrients",
        "Shorter vasa recta",
        "More fat in its mesentery",
      ],
      correct: 1,
    },
    {
      q: "A 67-year-old woman with a long history of liver cirrhosis was seen in the emergency department. In this patient with portal hypertension, which of the following veins is most likely to be dilated?",
      a: [
        "Right colic vein",
        "Inferior epigastric vein",
        "Inferior phrenic vein",
        "Suprarenal vein",
        "Ovarian vein",
      ],
      correct: 1,
    },
    {
      q: "A 26-year-old patient is admitted to a local hospital with a retroperitoneal infection. Which of the following arteries is most likely to be infected?",
      a: [
        "Left gastric artery",
        "Proper hepatic artery",
        "Middle colic artery",
        "Sigmoid arteries",
        "Dorsal pancreatic artery",
      ],
      correct: 4,
    },
    {
      q: "A pediatric surgeon has resected a structure that is a fibrous remnant of an embryonic or fetal artery in a 5-year-old child. Which of the following structures is most likely to be divided?",
      a: [
        "Lateral umbilical fold",
        "Medial umbilical fold",
        "Median umbilical fold",
        "Ligamentum teres hepatis",
        "Ligamentum venosum",
      ],
      correct: 1,
    },
    {
      q: "A 57-year-old patient has a tumor in the body of the pancreas that obstructs the inferior mesenteric vein just before joining the splenic vein. Which of the following veins is most likely to be enlarged?",
      a: [
        "Middle colic vein",
        "Left gastroepiploic vein",
        "Inferior pancreaticoduodenal vein",
        "Ileocolic vein",
        "Left colic vein",
      ],
      correct: 4,
    },
    {
      q: "An elderly man with prostatic hypertrophy returns to his urologist with another case of epididymitis. An acute infection involving the dartos muscle layer of the scrotum most likely leads to an enlargement of which of the following lymph nodes?",
      a: [
        "Preaortic nodes",
        "Lumbar nodes",
        "External iliac nodes",
        "Superficial inguinal nodes",
        "Common iliac nodes",
      ],
      correct: 3,
    },
    {
      q: "A patient with cirrhosis is scheduled for liver transplant surgery. During the operation rounds, the transplant physician explains to his residents that one of the reasons a surgeon must pay close attention to the anatomic location of the liver is that this organ:",
      a: [
        "Receives blood only from the hepatic arteries",
        "Manufactures red blood cells in an adult",
        "Drains bile from the quadrate lobe into the right hepatic duct",
        "Drains venous blood into the hepatic veins",
        "Functions to concentrate and store bile",
      ],
      correct: 3,
    },
    {
      q: "A 41-year-old woman is brought to the emergency department by her family because of acute onset of right upper quadrant pain, nausea, and vomiting. For this case, it is important to remember that the bile duct:",
      a: [
        "Drains bile into the second part of the duodenum",
        "Can be blocked by cancer in the body of the pancreas",
        "Joins the main pancreatic duct, which carries hormones",
        "Is formed by union of the right and left hepatic duct",
        "Lies posterior to the portal vein in the right free edge of the lesser omentum",
      ],
      correct: 0,
    },
    {
      q: "A patient with diverticulosis of the colon presents for follow-up to his primary care physician with ongoing complaints of left lower quadrant pain and occasionally bloody stools. His physician begins workup with appropriating test by recalling that the sigmoid colon:",
      a: [
        "Is drained by systemic veins",
        "Is a retroperitoneal organ",
        "Receives parasympathetic fibers from the vagus nerve",
        "Receives its blood from the superior mesenteric artery",
        "Has teniae coli and epiploic appendages",
      ],
      correct: 4,
    },
    {
      q: "A 19-year-old man with a ruptured appendix is sent to the emergency department for surgery. To cut off the blood supply to the appendix (if collateral circulation is discounted), a surgeon should ligate which of the following arteries?",
      a: [
        "Middle colic artery",
        "Right colic artery",
        "Ileocolic artery",
        "Inferior mesenteric artery",
        "Common iliac artery",
      ],
      correct: 2,
    },
    {
      q: "Because of an inflammatory bowel disease (Crohn disease) and a small bowel obstruction leading to bowel ischemia, an elderly woman requires bypass of her ileum and jejunum and is scheduled for a gastrocolostomy. The surgeon will ligate all arteries that send branches to the stomach. Which of the following arteries may be spared?",
      a: [
        "Splenic artery",
        "Gastroduodenal artery",
        "Inferior pancreaticoduodenal artery",
        "Left gastroepiploic artery",
        "Proper hepatic artery",
      ],
      correct: 2,
    },
    {
      q: "A 38-year-old woman with peptic ulcer disease of the stomach experiences severe abdominal pain. Which of the following nervous structures is most likely involved?",
      a: [
        "Greater splanchnic nerve",
        "Ventral roots of the spinal nerve",
        "Lower intercostal nerve",
        "Vagus nerve",
        "Gray ramus communicans",
      ],
      correct: 0,
    },
    {
      q: "A 3-year-old boy is diagnosed as having a persistent processus vaginalis in its middle portion. Which of the following conditions is most likely to be associated with this developmental anomaly?",
      a: [
        "Direct inguinal hernia",
        "Gubernaculum testis",
        "Hematocele",
        "Hydrocele",
        "Cryptorchidism",
      ],
      correct: 3,
    },
    {
      q: "Examination of a 54-year-old man reveals an isolated tumor located at the porta hepatis. This tumor most likely compresses which of the following structures?",
      a: [
        "Cystic duct",
        "Hepatic veins",
        "Common hepatic artery",
        "Left gastric artery",
        "Branches of the portal vein",
      ],
      correct: 4,
    },
    {
      q: "A patient is rushed to the operating room for an emergent cholecystectomy (resection of a gallbladder) because of cholecystitis. While locating landmarks before surgical resection of an infected gallbladder, the surgeon recalls a portal–caval anastomosis. Which of the following pairs of veins form a portal–caval anastomosis?",
      a: [
        "Hepatic veins and IVC",
        "Superior and middle rectal vein",
        "Left and right gastric vein",
        "Inferior and superficial epigastric veins",
        "Suprarenal and renal veins",
      ],
      correct: 3,
    },
    {
      q: "Mrs. Jones is undergoing a routine colonoscopy for colon cancer prevention. The gastroenterologist finds a Meckel diverticulum. Which of the following statements is true about the diverticulum?",
      a: [
        "It is found 2 ft distal to the ileocecal junction",
        "It is located on the mesenteric side of the ileum",
        "It occurs in approximately 20% of the population",
        "It is a persistent remnant of the embryonic yolk stalk",
        "It may contain renal and suprarenal tissues",
      ],
      correct: 3,
    },
    {
      q: "A 54-year-old man comes to a hospital with abdominal pain, jaundice, loss of appetite, and weight loss. On examination of his radiograms and CT scans, a physician finds a slowly growing tumor in the uncinate process of the pancreas. Which of the following structures is most likely compressed by this tumor?",
      a: [
        "Main pancreatic duct",
        "Splenic artery",
        "Portal vein",
        "Superior mesenteric artery",
        "Superior pancreaticoduodenal artery",
      ],
      correct: 0,
    },
    {
      q: "A 6-year-old boy comes to his pediatrician with a lump in the groin near the thigh and pain in the groin. On examination, the physician makes a diagnosis of a direct inguinal hernia because the herniated tissue:",
      a: [
        "Enters the deep inguinal ring",
        "Lies lateral to the inferior epigastric artery",
        "Is covered by spermatic fasciae",
        "Descends into the scrotum",
        "Develops after birth",
      ],
      correct: 3,
    },
    {
      q: "A 21-year-old man developed a hernia after lifting heavy boxes while moving into his new house. During the repair of his resulting hernia, the urologist recalls that the genitofemoral nerve:",
      a: [
        "Runs in front of the quadratus lumborum",
        "Is a branch of the femoral nerve",
        "Supplies the testis",
        "Passes through the deep inguinal ring",
        "Gives rise to an anterior scrotal branch",
      ],
      correct: 3,
    },
    {
      q: "An oncologist is reviewing a CT scan of a 74-year-old man with newly diagnosed hepatocellular carcinoma. He locates the affected quadrate lobe of the liver that:",
      a: [
        "Lies between the IVC and ligamentum venosum",
        "Receives blood from the right hepatic artery",
        "Drains bile into the left hepatic duct",
        "Is a medial superior segment",
        "Is functionally a part of the right lobe",
      ],
      correct: 2,
    },
    {
      q: "A 58-year-old man is presented with edema of the lower limb and enlarged superficial veins of the abdominal wall. Examination of radiographs and angiograms reveals obstruction of the IVC just proximal to the entrance of the renal vein. This venous blockage may result in dilation of which of the following veins?",
      a: [
        "Left suprarenal vein",
        "Right inferior phrenic vein",
        "Right hepatic vein",
        "Left gastric vein",
        "Portal vein",
      ],
      correct: 0,
    },
    {
      q: "A physical fitness trainer for a young Hollywood movie star explains the reasons for 100 stomach crunches a day. The young star, a medical student before ‘hitting it big,’ reaffirms to his trainer that the lateral margin of the rectus abdominis, the muscle responsible for a washboard stomach, defines which of the following structures?",
      a: [
        "Linea alba",
        "Linea semilunaris",
        "Linea semicircularis",
        "Transversalis fascia",
        "Falx inguinalis",
      ],
      correct: 1,
    },
    {
      q: "During surgical treatment of portal hypertension in a 59-year-old man with liver cirrhosis, a surgeon inadvertently lacerates the dilated paraumbilical veins. The veins must be repaired to allow collateral flow. Which of the following ligaments is most likely severed?",
      a: [
        "Lienorenal ligament",
        "Lienogastric ligament",
        "Gastrophrenic ligament",
        "Ligamentum teres hepatis",
        "Ligamentum venosum",
      ],
      correct: 3,
    },
    {
      q: "A 43-year-old woman is admitted to the hospital because of deep abdominal pain in her epigastric region. On examination, it is observed that a retroperitoneal infection erodes an artery that runs along the superior border of the pancreas. Which of the following arteries is likely injured?",
      a: [
        "Right gastric artery",
        "Left gastroepiploic artery",
        "Splenic artery",
        "Gastroduodenal artery",
        "Dorsal pancreatic artery",
      ],
      correct: 4,
    },
    {
      q: "A 19-year-old young woman with a long history of irritable bowel syndrome presents for the possibility of surgical resection of the gastrointestinal (GI) tract where the vagal parasympathetic innervation terminates. Which of the following sites is most appropriate for surgical resection?",
      a: [
        "Duodenojejunal junction",
        "Ileocecal junction",
        "Right colic flexure",
        "Left colic flexure",
        "Anorectal junction",
      ],
      correct: 3,
    },
    {
      q: "A 58-year-old man is admitted to the hospital with severe abdominal pain, nausea, and vomiting resulting in dehydration. Emergency CT scan reveals a tumor located between the celiac trunk and the superior mesenteric artery. Which of the following structures is likely compressed by this tumor?",
      a: [
        "Fundus of the stomach",
        "Neck of the pancreas",
        "Transverse colon",
        "Hepatopancreatic ampulla",
        "Duodenojejunal junction",
      ],
      correct: 1,
    },
    {
      q: "An emergent hernia repair is scheduled. As the attending physician is driving to the hospital, the medical student assisting on the case quickly reviews his anatomy atlas and is trying to commit to memory that the internal oblique abdominis muscle contributes to the formation of which of the following structures?",
      a: [
        "Inguinal ligament",
        "Deep inguinal ring",
        "Falx inguinalis (conjoint tendon)",
        "Internal spermatic fascia",
        "Reflected inguinal ligament",
      ],
      correct: 2,
    },
    {
      q: "A 9-year-old girl has crashed into her neighbor’s brick fence while riding her bike and is brought to the emergency department with a great deal of abdominal pain. Her radiogram and angiogram show laceration of the superior mesenteric artery immediately distal to the origin of the middle colic artery. If collateral circulation is discounted, which of the following organs may become ischemic?",
      a: [
        "Descending colon",
        "Duodenum",
        "Pancreas",
        "Ascending colon",
        "Transverse colon",
      ],
      correct: 4,
    },
    {
      q: "A 53-year-old woman with known kidney disease presents to a hospital because her pain has become increasingly more severe. A physician performing kidney surgery must remember that:",
      a: [
        "The left kidney lies a bit lower than the right one",
        "The perirenal fat lies external to the renal fascia",
        "The renal fascia does not surround the suprarenal gland",
        "The left renal vein runs anterior to both the aorta and the left renal artery",
        "The right renal artery is shorter than the left renal artery",
      ],
      correct: 3,
    },
    {
      q: "A neonatal baby was born with diabetes mellitus due to an inadequate production of insulin. Cells in the endocrine portion of the pancreas that secrete insulin, glucagon, and somatostatin are derived from which of the following?",
      a: [
        "Ectoderm",
        "Mesoderm",
        "Endoderm",
        "Proctodeum",
        "Neural crest cells",
      ],
      correct: 2,
    },
    {
      q: "During development, the midgut artery appears to be markedly narrowed at its origin. Which of the following structures is derived from the midgut and may receive inadequate blood supply?",
      a: [
        "Gallbladder",
        "Stomach",
        "Descending colon",
        "Ascending colon",
        "Rectum",
      ],
      correct: 3,
    },
    {
      q: "A 3-year-old boy is admitted to the children’s hospital with complaints of restlessness, abdominal pain, and fever. An MRI examination reveals that he has a double ureter. Which of the following embryonic structures is most likely failed to develop normally?",
      a: [
        "Mesonephric (Wolffian) duct",
        "Paramesonephric (Müllerian) duct",
        "Ureteric bud",
        "Metanephros",
        "Pronephros",
      ],
      correct: 2,
    },
    {
      q: "A neonate has a small reducible protrusion through a defined ring at the umbilicus. His pediatrician indicates to the parents that this will likely close spontaneously. Which of the following congenital malformations is present?",
      a: [
        "Umbilical hernia",
        "Symptomatic patent urachus",
        "Patent omphalomesenteric duct",
        "Omphalocele",
        "Gastroschisis",
      ],
      correct: 0,
    },
  ],
  cases1: [
    {
      q: "A 23-year-old jockey falls from her horse and complains of headache, backache, and weakness. Radiologic examination would reveal blood in which of the following spaces if the internal vertebral venous plexus was ruptured?",
      a: [
        "Space deep to the pia mater",
        "Space between the arachnoid and dura maters",
        "Subdural space",
        "Epidural space",
        "Subarachnoid space",
      ],
      correct: 3,
    },
    {
      q: "A 7-year-old girl comes to the emergency department with severe diarrhea. Tests show that the diarrhea is due to decreased capacity of normal absorption in one of her organs. Which of the following organs is involved?",
      a: ["Stomach", "Gallbladder", "Large intestine", "Liver", "Pancreas"],
      correct: 2,
    },
    {
      q: "A 16-year-old girl with urinary diseases comes to a local hospital. Her urologist’s examination and laboratory test results reveal that she has difficulty in removing wastes from the blood and in producing urine. Which of the following organs may have abnormal functions?",
      a: ["Ureter", "Spleen", "Urethra", "Bladder", "Kidney"],
      correct: 4,
    },
    {
      q: "A 29-year-old man comes to a local hospital with duodenal peptic ulcer and complains of cramping epigastric pain. Which of the following structures harbors the cell bodies of abdominal pain fibers?",
      a: [
        "Lateral horn of the spinal cord",
        "Anterior horn of the spinal cord",
        "Dorsal root ganglion",
        "Sympathetic chain ganglion",
        "Celiac ganglion",
      ],
      correct: 2,
    },
    {
      q: "A 42-year-old obese woman with seven children is brought to a local hospital by her daughter. Physical examination and her radiograph reveal that large gallstones have ulcerated through the posterior wall of the fundus of the gallbladder into the intestine. Which of the following parts of the intestine is most likely to initially contain gallstones?",
      a: [
        "Cecum",
        "Ascending colon",
        "Transverse colon",
        "Descending colon",
        "Sigmoid colon",
      ],
      correct: 2,
    },
  ],
  cases2: [
    {
      q: "A 53-year-old man with a known history of emphysema is examined in the emergency department. Laboratory findings along with examination indicate that the patient is unable to exchange oxygen in the air and carbon dioxide in the blood. This exchange occurs in which portion of the respiratory system?",
      a: ["Bronchi", "Alveolar (air) sac", "Nasal cavity", "Larynx", "Trachea"],
      correct: 1,
    },
    {
      q: "A 37-year-old patient with severe chest pain, shortness of breath, and congestive heart failure was admitted to a local hospital. His coronary angiograms reveal a thrombosis in the circumflex branch of the left coronary artery. Which of the following conditions could result from the blockage of blood flow in the circumflex branch?",
      a: [
        "Tricuspid valve insufficiency",
        "Mitral valve insufficiency",
        "Ischemia of AV node",
        "Paralysis of pectinate muscle",
        "Necrosis of septomarginal trabecula",
      ],
      correct: 1,
    },
    {
      q: "A 2-year-old boy presents with pain in his groin that has been increasing in nature over the past few weeks. He is found to have a degenerative malformation of the transversalis fascia during development. Which of the following structures on the anterior abdominal wall is likely defective?",
      a: [
        "Superficial inguinal ring",
        "Deep inguinal ring",
        "Inguinal ligament",
        "Sac of a direct inguinal hernia",
        "Anterior wall of the inguinal canal",
      ],
      correct: 1,
    },
    {
      q: "A crush injury of the vertebral column can cause the spinal cord to swell. Which structure would be trapped between the dura and the vertebral body by the swelling spinal cord?",
      a: [
        "Anterior longitudinal ligament",
        "Alar ligament",
        "Posterior longitudinal ligament",
        "Cruciform ligament",
        "Ligamentum nuchae",
      ],
      correct: 2,
    },
    {
      q: "A 29-year-old woman with abdominal pain was admitted to a local hospital, and examination shows that a retroperitoneal infection is affecting a purely endocrine gland. Which of the following structures is infected?",
      a: ["Ovary", "Suprarenal gland", "Pancreas", "Liver", "Stomach"],
      correct: 1,
    },
  ],
  case_bio: [
    {
      q: "A 3-month-old infant with developmental delay, hepatosplenomegaly, and coarse facial features shows accumulation of undigested macromolecules in membrane-bound vesicles due to acid hydrolase deficiency. Which organelle is affected?",
      a: [
        "Lysosome",
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Peroxisome",
        "Mitochondria",
      ],
      correct: 0,
    },
    {
      q: "A point mutation changes a codon from UAU to UAA. What type of mutation is this?",
      a: [
        "Nonsense mutation",
        "Missense mutation",
        "Silent mutation",
        "Frameshift mutation",
        "Insertion mutation",
      ],
      correct: 0,
    },
    {
      q: "Eukaryotic mRNA contains a poly-A tail. What is its primary function?",
      a: [
        "Protection from exonuclease degradation",
        "Initiation of transcription",
        "Splicing of introns",
        "RNA polymerase binding",
        "Ribosome assembly",
      ],
      correct: 0,
    },
    {
      q: "A drug inhibits the enzyme that removes RNA primers during eukaryotic DNA replication. Which process is directly affected?",
      a: [
        "Removal of RNA primers",
        "DNA unwinding",
        "Okazaki fragment elongation",
        "Joining of Okazaki fragments",
        "Leading strand synthesis",
      ],
      correct: 0,
    },
    {
      q: "Loss of function of a gene that halts the cell cycle at the G1/S checkpoint after DNA damage is found in colon cancer cells. Which gene is mutated?",
      a: ["p53", "RAS", "MYC", "BCL-2", "EGFR"],
      correct: 0,
    },
    {
      q: "A teenage girl with stroke-like episodes, seizures, lactic acidosis, hearing loss, and ragged-red fibers on muscle biopsy. What is the underlying cause?",
      a: [
        "Mitochondrial DNA mutation impairing oxidative phosphorylation",
        "Autosomal recessive nuclear mutation",
        "X-linked dystrophin mutation",
        "Somatic oncogene mutation",
        "Lysosomal enzyme targeting defect",
      ],
      correct: 0,
    },
    {
      q: "A newborn with hypotonia, seizures, hepatomegaly, elevated very-long-chain fatty acids, and decreased plasmalogens dies in infancy. Which organelle is dysfunctional?",
      a: [
        "Peroxisome",
        "Mitochondria",
        "Lysosome",
        "Golgi apparatus",
        "Endoplasmic reticulum",
      ],
      correct: 0,
    },
    {
      q: "A child with frequent fractures, blue sclerae, hearing loss, joint hypermobility, and fragile teeth. What is the underlying defect?",
      a: [
        "Type I collagen mutation affecting triple helix formation",
        "Defective elastin synthesis",
        "Impaired bone mineralization",
        "Vitamin D activation defect",
        "Osteoclast dysfunction",
      ],
      correct: 0,
    },
    {
      q: "A child with blue sclerae and brittle, translucent teeth with obliterated pulp chambers. What causes the dental findings?",
      a: [
        "Abnormal dentin formation due to type I collagen mutation",
        "Enamel formation defect",
        "Vitamin D deficiency",
        "Defective calcium absorption",
        "Impaired osteoclast activity",
      ],
      correct: 0,
    },
    {
      q: "A young woman with hyperextensible skin, hypermobile joints, easy bruising, and atrophic scars. What is the molecular defect?",
      a: [
        "Defective collagen synthesis or processing",
        "Decreased fibrillin-1 synthesis",
        "Impaired elastin cross-linking",
        "Abnormal bone mineralization",
        "Autoimmune connective tissue destruction",
      ],
      correct: 0,
    },
    {
      q: "A woman with thin translucent skin, spontaneous arterial rupture, and family history of sudden death. Which genetic defect is responsible?",
      a: [
        "COL3A1 mutation causing defective type III collagen",
        "Fibrillin-1 mutation",
        "Type I collagen synthesis defect",
        "Lysyl oxidase deficiency",
        "Abnormal elastin degradation",
      ],
      correct: 0,
    },
    {
      q: "An infant with kinky hair, hypotonia, hypothermia, low copper, and low ceruloplasmin levels. What is the molecular defect?",
      a: [
        "X-linked defect in copper transport from intestinal cells",
        "Autosomal recessive iron absorption defect",
        "Mitochondrial DNA mutation",
        "Lysosomal enzyme targeting defect",
        "Type I collagen mutation",
      ],
      correct: 0,
    },
    {
      q: "A malnourished child with bleeding gums, petechiae, corkscrew hairs, and normal coagulation tests. What is the underlying defect?",
      a: [
        "Vitamin C deficiency impairing collagen synthesis",
        "Vitamin K deficiency",
        "Iron deficiency",
        "Vitamin D deficiency",
        "Lysyl oxidase deficiency",
      ],
      correct: 0,
    },
    {
      q: "A tall young man with arachnodactyly, pectus excavatum, scoliosis, ectopia lentis, and aortic root dilation. What is the molecular defect?",
      a: [
        "Fibrillin-1 mutation affecting microfibril formation",
        "Type III collagen defect",
        "Lysyl oxidase deficiency",
        "Type I collagen mutation",
        "ATP7A mutation",
      ],
      correct: 0,
    },
  ],
};
